In [17]:
from pathlib import Path

import numpy as np
import pandas as pd
import tifffile as tiff
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.colors import ListedColormap, Normalize
from IPython.display import display
from skimage.measure import regionprops, label as cc_label
from skimage.morphology import binary_erosion, remove_small_holes

from tqdm.auto import tqdm

# =============================
# Constants
# =============================
PIXEL_SIZE_NM = 1.751
ERODE_PIXELS = 1
TARGET_STACK_SHAPE = (256, 256)

GLOBAL_VMIN = 0.0037
GLOBAL_VMAX = 0.6
NORM_15N = Normalize(vmin=GLOBAL_VMIN, vmax=GLOBAL_VMAX)

DISPLAY_NORM = Normalize(vmin=0.0, vmax=3.0)

SHOW_PLOTS = False

EXPECTED_CHANNELS_7 = [
    "16O",
    "12C21H",
    "12C14N",
    "12C15N",
    "29Si",
    "31P",
    "32S",
]

EXPECTED_CHANNELS_6 = [
    "16O",
    "12C21H",
    "12C14N",
    "12C15N",
    "31P",
    "32S",
]

# Illustrator-friendly PDF text
mpl.rcParams["pdf.fonttype"] = 42
mpl.rcParams["ps.fonttype"] = 42
mpl.rcParams["savefig.facecolor"] = "white"
mpl.rcParams["savefig.transparent"] = False

# =============================
# Root paths
# =============================
INPUT_ROOT = Path("input")
OUTPUT_ROOT = Path("output")
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

if not INPUT_ROOT.exists():
    raise FileNotFoundError(f"Input root not found: {INPUT_ROOT.resolve()}")

# =============================
# NPZ output (shared across samples)
# =============================
NPZ_ROOT = Path.cwd() / "output_npz"
NPZ_ROOT.mkdir(parents=True, exist_ok=True)


# =============================
# LUT loading
# =============================
def load_fiji_lut_try(paths=(Path("LUT.csv"), Path.cwd() / "LUT.csv", Path("/mnt/data/LUT.csv"))):
    for p in paths:
        try:
            if not p.exists():
                continue

            df = pd.read_csv(p)
            cols = [c.strip().lower() for c in df.columns]

            if "red" in cols and "green" in cols and "blue" in cols:
                r_idx = cols.index("red")
                g_idx = cols.index("green")
                b_idx = cols.index("blue")
            elif "r" in cols and "g" in cols and "b" in cols:
                r_idx = cols.index("r")
                g_idx = cols.index("g")
                b_idx = cols.index("b")
            else:
                r_idx, g_idx, b_idx = 1, 2, 3

            rgb = df.iloc[:, [r_idx, g_idx, b_idx]].to_numpy(dtype=float) / 255.0
            rgb = np.clip(rgb, 0.0, 1.0)
            cmap = ListedColormap(rgb, name="fiji_lut_from_csv")

            try:
                mpl.colormaps.register(cmap, name="fiji_lut_from_csv", force=True)
            except Exception:
                try:
                    mpl.cm.register_cmap(name="fiji_lut_from_csv", cmap=cmap)
                except Exception:
                    pass

            if hasattr(cmap, "with_extremes"):
                cmap = cmap.with_extremes(bad=(0, 0, 0, 0))

            print(f"Loaded LUT from {p} ({rgb.shape[0]} entries).")
            return cmap

        except Exception as e:
            print(f"Failed to load LUT from {p}: {e}")

    return None


CUSTOM_15N_CMAP = load_fiji_lut_try()
if CUSTOM_15N_CMAP is None:
    CUSTOM_15N_CMAP = plt.get_cmap("viridis")
    print("No LUT found; using viridis for 15N display.")

# =============================
# Helpers
# =============================

def whole_field_mean_norm(stack, channel_names):
    """
    Mean-normalize each channel using all finite pixels in the full image.
    """
    n_channels = stack.shape[0]
    if len(channel_names) != n_channels:
        raise ValueError(
            f"Channel-name count ({len(channel_names)}) does not match stack channels ({n_channels})."
        )

    means = np.empty(n_channels, dtype=float)
    for ch, name in enumerate(channel_names):
        vals = stack[ch]
        finite_vals = vals[np.isfinite(vals)]
        if finite_vals.size == 0:
            print(f"Warning: channel {name} has no finite pixels. Using normalization factor 1.0.")
            means[ch] = 1.0
        else:
            mu = float(np.mean(finite_vals))
            if not np.isfinite(mu) or mu == 0:
                print(f"Warning: channel {name} has invalid mean {mu}. Using normalization factor 1.0.")
                means[ch] = 1.0
            else:
                means[ch] = mu

    return stack / means[:, None, None], means

def save_label_data_npz(
    npz_root,
    label_stem,
    lab,
    sample,
    source_label_file,
    strict_bbox,
    original_bbox,
    stack,
    stack_mean_norm,
    summed,
    fractional_15N,
    em_img,
    strict_mask_crop,
    channel_names,
    field_means,
    cell_label_id=None,
    source_cell_file=None,
):
    """
    Save reconstructable data for one label as a compressed NPZ.
    """

    sy0, sy1, sx0, sx1 = strict_bbox
    oy0, oy1, ox0, ox1 = original_bbox

    raw_stack_crop = stack[:, sy0:sy1, sx0:sx1]
    mean_norm_crop = stack_mean_norm[:, sy0:sy1, sx0:sx1]
    frac_crop = fractional_15N[sy0:sy1, sx0:sx1]
    sum_crop = summed[sy0:sy1, sx0:sx1]
    em_crop = em_img[oy0:oy1, ox0:ox1]

    raw_masked = np.full_like(raw_stack_crop, np.nan, dtype=np.float32)
    mean_norm_masked = np.full_like(mean_norm_crop, np.nan, dtype=np.float32)

    for ch in range(raw_stack_crop.shape[0]):
        raw_masked[ch][strict_mask_crop] = raw_stack_crop[ch][strict_mask_crop]
        mean_norm_masked[ch][strict_mask_crop] = mean_norm_crop[ch][strict_mask_crop]

    frac_masked = np.full_like(frac_crop, np.nan, dtype=np.float32)
    frac_masked[strict_mask_crop] = frac_crop[strict_mask_crop]

    sum_masked = np.full_like(sum_crop, np.nan, dtype=np.float32)
    sum_masked[strict_mask_crop] = sum_crop[strict_mask_crop]

    npz_path = npz_root / f"{sample}_{label_stem}_label{lab:03d}.npz"

    np.savez_compressed(
        npz_path,
        sample=sample,
        label_id=lab,
        source_label_file=source_label_file,
        source_cell_file=source_cell_file if source_cell_file is not None else "",
        cell_label_id=-1 if cell_label_id is None else int(cell_label_id),
        bbox_strict=np.array([sy0, sy1, sx0, sx1], dtype=np.int32),
        bbox_original=np.array([oy0, oy1, ox0, ox1], dtype=np.int32),
        channel_names=np.array(channel_names, dtype=object),
        field_means=np.array(field_means, dtype=np.float32),
        raw_channels=raw_masked,
        mean_norm_channels=mean_norm_masked,
        fractional_15N=frac_masked,
        sum_12C14N_12C15N=sum_masked,
        em=em_crop.astype(np.float32),
    )

    return npz_path

def clean_cell_labels(cell_img):
    """
    For each positive label:
      1) fill holes
      2) keep only the largest connected component
      3) preserve the original label value
    """
    cell_img = np.rint(cell_img).astype(np.int32)
    cleaned = np.zeros_like(cell_img, dtype=np.int32)

    for lab in np.unique(cell_img):
        lab = int(lab)
        if lab <= 0:
            continue

        mask = cell_img == lab
        if not np.any(mask):
            continue

        mask = remove_small_holes(mask, area_threshold=mask.size)

        cc = cc_label(mask, connectivity=2)
        if cc.max() == 0:
            continue

        counts = np.bincount(cc.ravel())
        counts[0] = 0
        keep = int(np.argmax(counts))
        cleaned[cc == keep] = lab

    return cleaned


def load_cell_labels(cell_path: Path):
    """
    Load a cell-label TIFF and clean it.
    Binary masks are converted to connected components first.
    """
    cell_img = tiff.imread(str(cell_path))
    if cell_img.ndim != 2:
        raise ValueError(f"Expected a 2D cell label TIFF, got shape {cell_img.shape} for {cell_path.name}")

    cell_img = np.rint(cell_img).astype(np.int32)

    if np.max(cell_img) <= 1:
        print(f"Detected binary cell mask in {cell_path.name}; converting connected components to labels.")
        cell_img = cc_label(cell_img > 0, connectivity=2).astype(np.int32)

    return clean_cell_labels(cell_img)


def whole_field_mean_norm_masked(stack, channel_names, mask):
    """
    Mean-normalize each channel using only pixels inside `mask`.
    """
    n_channels = stack.shape[0]
    if len(channel_names) != n_channels:
        raise ValueError(
            f"Channel-name count ({len(channel_names)}) does not match stack channels ({n_channels})."
        )

    mask = np.asarray(mask, dtype=bool)
    if mask.shape != stack.shape[1:]:
        raise ValueError(f"Mask shape {mask.shape} does not match stack spatial shape {stack.shape[1:]}.")

    means = np.empty(n_channels, dtype=float)
    for ch, name in enumerate(channel_names):
        vals = stack[ch][mask]
        finite_vals = vals[np.isfinite(vals)]
        if finite_vals.size == 0:
            print(f"Warning: cell-normalization channel {name} has no finite pixels. Using 1.0.")
            means[ch] = 1.0
        else:
            mu = float(np.mean(finite_vals))
            if not np.isfinite(mu) or mu == 0:
                print(f"Warning: cell-normalization channel {name} has invalid mean {mu}. Using 1.0.")
                means[ch] = 1.0
            else:
                means[ch] = mu

    return stack / means[:, None, None], means


def infer_channel_names(n_channels):
    """
    Return the expected channel-name list for the TIFF stack.

    Supported:
      - 7-channel stacks: full channel list
      - 6-channel stacks: assumes 29Si is missing
    """
    if n_channels == 7:
        return EXPECTED_CHANNELS_7.copy()
    if n_channels == 6:
        print("Detected 6-channel TIFF; assuming '29Si' is the missing channel.")
        return EXPECTED_CHANNELS_6.copy()
    raise ValueError(f"Unsupported channel count: {n_channels}. Expected 6 or 7 channels.")


def strict_reduce_mask_to_shape(original_mask, out_shape):
    """
    Keep a reduced pixel only if ALL source pixels in that block are True.
    """
    in_h, in_w = original_mask.shape
    out_h, out_w = out_shape
    y_edges = np.linspace(0, in_h, out_h + 1).astype(int)
    x_edges = np.linspace(0, in_w, out_w + 1).astype(int)

    out = np.zeros((out_h, out_w), dtype=bool)

    for i in range(out_h):
        y0, y1 = y_edges[i], y_edges[i + 1]
        if y1 <= y0:
            y1 = min(y0 + 1, in_h)
        for j in range(out_w):
            x0, x1 = x_edges[j], x_edges[j + 1]
            if x1 <= x0:
                x1 = min(x0 + 1, in_w)

            block = original_mask[y0:y1, x0:x1]
            out[i, j] = bool(block.size > 0 and np.all(block))

    return out


def expand_reduced_mask_to_fullres(reduced_mask, full_shape):
    """
    Back-project a reduced mask to full resolution using the same bin edges.
    """
    full_h, full_w = full_shape
    red_h, red_w = reduced_mask.shape
    y_edges = np.linspace(0, full_h, red_h + 1).astype(int)
    x_edges = np.linspace(0, full_w, red_w + 1).astype(int)

    out = np.zeros((full_h, full_w), dtype=bool)

    for i in range(red_h):
        y0, y1 = y_edges[i], y_edges[i + 1]
        if y1 <= y0:
            y1 = min(y0 + 1, full_h)
        for j in range(red_w):
            if not reduced_mask[i, j]:
                continue
            x0, x1 = x_edges[j], x_edges[j + 1]
            if x1 <= x0:
                x1 = min(x0 + 1, full_w)
            out[y0:y1, x0:x1] = True

    return out


def bbox_of_mask(mask):
    coords = np.argwhere(mask)
    if coords.size == 0:
        return None
    y0, x0 = coords.min(axis=0)
    y1, x1 = coords.max(axis=0) + 1
    return y0, y1, x0, x1


def crop_to_bbox(arr, bbox):
    y0, y1, x0, x1 = bbox
    return arr[y0:y1, x0:x1]


def show_square_image(ax, img, title="", cmap=None, norm=None):
    ax.imshow(img, cmap=cmap, norm=norm, aspect="equal", interpolation="nearest")
    ax.set_title(title)
    ax.set_aspect("equal", adjustable="box")
    ax.axis("off")


def finite_values(values):
    values = np.asarray(values, dtype=float).ravel()
    return values[np.isfinite(values)]


def summarize(values):
    vals = finite_values(values)
    if vals.size == 0:
        return {
            "n": 0,
            "mean": np.nan,
            "median": np.nan,
            "std": np.nan,
            "min": np.nan,
            "max": np.nan,
            "q1": np.nan,
            "q3": np.nan,
            "iqr": np.nan,
        }

    q1 = float(np.percentile(vals, 25))
    q3 = float(np.percentile(vals, 75))
    return {
        "n": int(vals.size),
        "mean": float(np.mean(vals)),
        "median": float(np.median(vals)),
        "std": float(np.std(vals)),
        "min": float(np.min(vals)),
        "max": float(np.max(vals)),
        "q1": q1,
        "q3": q3,
        "iqr": float(q3 - q1),
    }


def add_stats(row, prefix, values):
    s = summarize(values)
    for k, v in s.items():
        row[f"{prefix}_{k}"] = v


def sample_nearest(img, yx):
    """
    Sample an image at the nearest pixel to yx = (row, col).
    """
    img = np.asarray(img)
    y = int(np.rint(yx[0]))
    x = int(np.rint(yx[1]))
    y = int(np.clip(y, 0, img.shape[0] - 1))
    x = int(np.clip(x, 0, img.shape[1] - 1))
    return float(img[y, x])


def safe_contour(ax, mask, color="red", linewidth=1.5):
    if mask is None:
        return
    if mask.shape[0] >= 2 and mask.shape[1] >= 2 and np.any(mask):
        ax.contour(mask.astype(float), levels=[0.5], colors=color, linewidths=linewidth)



def median_line(ax, values, color="black"):
    values = finite_values(values)
    if values.size:
        ax.axvline(np.median(values), color=color, linestyle=":", linewidth=2)


def rel_xy(xy, bbox):
    """
    Convert full-image (row, col) coordinates to crop-relative coordinates.
    bbox is (y0, y1, x0, x1).
    """
    if xy is None or bbox is None:
        return None
    row, col = xy
    y0, y1, x0, x1 = bbox
    return (row - y0, col - x0)


def draw_centroid_square(ax, xy, color="red", size_points=36, linewidth=1.5):
    """
    Draw a small square marker at xy = (row, col).
    The square size is in display points, so it looks similar across panels.
    """
    if xy is None:
        return

    row, col = xy
    ax.scatter(
        [col],
        [row],
        marker="s",
        s=size_points,
        facecolors="none",
        edgecolors=color,
        linewidths=linewidth,
        zorder=20,
        clip_on=False,
    )


def centroid_in_mask(mask, yx):
    """
    Check if a (row, col) coordinate falls inside a boolean mask.
    Uses nearest pixel sampling.
    """
    if mask is None or yx is None:
        return False

    y = int(np.rint(yx[0]))
    x = int(np.rint(yx[1]))

    if y < 0 or x < 0 or y >= mask.shape[0] or x >= mask.shape[1]:
        return False

    return bool(mask[y, x])


def plot_section_clean(
    fig_title,
    mask_crop,
    channel_crops,
    hist_values,
    channel_display_names,
    em_crop=None,
    em_mask_crop=None,
    lut_crop=None,
    lut_mask_crop=None,
    lut_values=None,
    summary_text="",
    norm_xlim_max=3.0,
    show_inline=False,
    centroid_red_xy=None,
    centroid_full_xy=None,
):
    """
    Layout:
      - summary + mean-normalized channels + LUT + EM

    IMPORTANT CHANGE:
      - Composite images are ONLY saved if they are also shown (show_inline=True)
      - This reduces output file size dramatically
    """

    if not SHOW_PLOTS:
        return

    n_main_cols = len(channel_display_names) + 3
    em_col = len(channel_display_names) + 2
    lut_col = len(channel_display_names) + 1

    fig = plt.figure(figsize=(4 * n_main_cols, 12))
    fig.suptitle(fig_title, y=0.995)

    gs = fig.add_gridspec(
        3,
        n_main_cols,
        left=0.04,
        right=0.97,
        top=0.94,
        bottom=0.06,
        wspace=0.25,
        hspace=0.30,
    )

    ax0 = fig.add_subplot(gs[0, 0])
    show_square_image(ax0, mask_crop, fig_title, cmap="gray")

    ax1 = fig.add_subplot(gs[1, 0])
    ax1.axis("off")
    ax1.text(0.0, 0.95, summary_text, fontsize=10, va="top")

    ax2 = fig.add_subplot(gs[2, 0])
    ax2.axis("off")

    for ch, name in enumerate(channel_display_names):
        axr = fig.add_subplot(gs[0, ch + 1])
        show_square_image(
            axr,
            channel_crops[ch],
            f"{name}\nraw bbox",
            cmap="viridis",
            norm=DISPLAY_NORM,
        )
        draw_centroid_square(axr, centroid_red_xy)
        safe_contour(axr, mask_crop)

        axm = fig.add_subplot(gs[1, ch + 1])
        masked = np.full_like(channel_crops[ch], np.nan, dtype=np.float64)
        masked[mask_crop] = channel_crops[ch][mask_crop]
        show_square_image(
            axm,
            masked,
            f"{name}\nmasked",
            cmap="viridis",
            norm=DISPLAY_NORM,
        )
        draw_centroid_square(axm, centroid_red_xy)
        safe_contour(axm, mask_crop)

        axh = fig.add_subplot(gs[2, ch + 1])
        vals = finite_values(hist_values[ch])
        if vals.size:
            axh.hist(vals, bins=30)
        axh.set_title(f"{name}\nhistogram")
        axh.set_xlabel("Normalized value")
        axh.set_ylabel("Count")
        axh.set_xlim(0, norm_xlim_max)
        median_line(axh, vals, color="black")

    if lut_crop is not None:
        ax_lut0 = fig.add_subplot(gs[0, lut_col])
        show_square_image(
            ax_lut0,
            lut_crop,
            "15N LUT raw bbox",
            cmap=CUSTOM_15N_CMAP,
            norm=NORM_15N,
        )
        draw_centroid_square(ax_lut0, centroid_red_xy)
        if lut_mask_crop is not None:
            safe_contour(ax_lut0, lut_mask_crop)

        ax_lut1 = fig.add_subplot(gs[1, lut_col])
        lut_masked = np.full_like(lut_crop, np.nan, dtype=np.float64)
        if lut_mask_crop is not None:
            lut_masked[lut_mask_crop] = lut_crop[lut_mask_crop]
        show_square_image(
            ax_lut1,
            lut_masked,
            "15N LUT masked",
            cmap=CUSTOM_15N_CMAP,
            norm=NORM_15N,
        )
        draw_centroid_square(ax_lut1, centroid_red_xy)
        if lut_mask_crop is not None:
            safe_contour(ax_lut1, lut_mask_crop)

        ax_lut2 = fig.add_subplot(gs[2, lut_col])
        vals = finite_values(lut_values if lut_values is not None else [])
        if vals.size:
            counts, bin_edges = np.histogram(vals, bins=30)
            widths = bin_edges[1:] - bin_edges[:-1]
            centers = 0.5 * (bin_edges[1:] + bin_edges[:-1])
            for c, center, width in zip(counts, centers, widths):
                ax_lut2.bar(
                    center,
                    c,
                    width=width,
                    align="center",
                    color=CUSTOM_15N_CMAP(NORM_15N(center)),
                    edgecolor="none",
                )
        ax_lut2.set_title("15N LUT\nhistogram")
        ax_lut2.set_xlabel("15N incorporation")
        ax_lut2.set_ylabel("Count")
        ax_lut2.set_xlim(GLOBAL_VMIN, GLOBAL_VMAX)
        median_line(ax_lut2, vals, color="black")

    if em_crop is not None:
        ax_em0 = fig.add_subplot(gs[0, em_col])
        show_square_image(ax_em0, em_crop, "EM raw bbox", cmap="gray")
        draw_centroid_square(ax_em0, centroid_full_xy)
        if em_mask_crop is not None:
            safe_contour(ax_em0, em_mask_crop)

        ax_em1 = fig.add_subplot(gs[1, em_col])
        em_masked = np.full_like(em_crop, np.nan, dtype=np.float64)
        if em_mask_crop is not None:
            em_masked[em_mask_crop] = em_crop[em_mask_crop]
        show_square_image(ax_em1, em_masked, "EM masked", cmap="gray")
        draw_centroid_square(ax_em1, centroid_full_xy)
        if em_mask_crop is not None:
            safe_contour(ax_em1, em_mask_crop)

        ax_em2 = fig.add_subplot(gs[2, em_col])
        ax_em2.remove()

    # Figures are displayed only (no file output)
    if show_inline and SHOW_PLOTS:
        plt.show()

    plt.close(fig)


def find_first_tiff(folder: Path):
    files = sorted(list(folder.glob("*.tif")) + list(folder.glob("*.tiff")))
    if not files:
        raise FileNotFoundError(f"No TIFF files found in {folder}")
    if len(files) > 1:
        print(f"Warning: multiple TIFF files found in {folder}, using {files[0].name}")
    return files[0]


def load_stack(stack_path: Path):
    stack = tiff.imread(str(stack_path))
    if stack.ndim != 3:
        raise ValueError(f"Expected a 3D TIFF stack, got shape {stack.shape}")

    if stack.shape[1:] == TARGET_STACK_SHAPE:
        pass
    elif stack.shape[:2] == TARGET_STACK_SHAPE:
        stack = np.moveaxis(stack, -1, 0)
    else:
        raise ValueError(f"Stack spatial shape {stack.shape[-2:]} does not match {TARGET_STACK_SHAPE}")

    if stack.shape[0] not in (6, 7):
        raise ValueError(f"Unsupported channel count after loading: {stack.shape[0]}. Expected 6 or 7.")

    return stack.astype(np.float64)


def process_sample(sample_dir: Path):
    label_dir = sample_dir / "label_images"
    stack_dir = sample_dir / "nanosims_stack"
    em_dir = sample_dir / "input_em"
    output_dir = OUTPUT_ROOT / sample_dir.name
    output_dir.mkdir(parents=True, exist_ok=True)

    label_files = sorted(list(label_dir.glob("*.tif")) + list(label_dir.glob("*.tiff")))
    if len(label_files) == 0:
        raise FileNotFoundError(f"No label TIFFs found in {label_dir}")

    stack_path = find_first_tiff(stack_dir)
    em_path = find_first_tiff(em_dir)

    print(f"\n=== Sample: {sample_dir.name} ===")
    print(f"Using stack: {stack_path.name}")
    print(f"Using EM image: {em_path.name}")
    print(f"Outputs will be saved to: {output_dir.resolve()}")

    stack = load_stack(stack_path)
    n_channels = stack.shape[0]
    print(f"Stack shape: {stack.shape}")
    print(f"Number of original channels: {n_channels}")

    em_img = tiff.imread(str(em_path))
    if em_img.ndim != 2:
        raise ValueError(f"Expected a 2D EM image, got shape {em_img.shape}")

    print(f"EM shape: {em_img.shape}")

    cell_dir = sample_dir / "label_cells"
    if not cell_dir.exists():
        raise FileNotFoundError(f"Cell label folder not found: {cell_dir}")

    cell_path = find_first_tiff(cell_dir)
    cell_img = load_cell_labels(cell_path)

    if cell_img.shape != em_img.shape:
        raise ValueError(
            f"Cell label image shape {cell_img.shape} does not match EM shape {em_img.shape} "
            f"for {cell_path.name}"
        )

    print(f"Using cell labels: {cell_path.name}")

    cell_norm_cache = {}


    raw_channel_names = infer_channel_names(n_channels)
    channel_index = {name: i for i, name in enumerate(raw_channel_names)}

    if "12C14N" not in channel_index or "12C15N" not in channel_index:
        raise ValueError("Required channels 12C14N and 12C15N were not found in the TIFF stack.")

    ch2_idx = channel_index["12C14N"]
    ch3_idx = channel_index["12C15N"]

    stack_mean_norm, field_means = whole_field_mean_norm(stack, raw_channel_names)
    mean_norm_channel_names = [f"{name}_mean_norm" for name in raw_channel_names]

    print("\nWhole-field mean normalization factors:")
    for name, mu in zip(raw_channel_names, field_means):
        print(f"{name}: {mu:.6f}")

    summed = stack[ch2_idx] + stack[ch3_idx]
    fractional_15N = np.full_like(summed, np.nan, dtype=np.float64)
    np.divide(stack[ch3_idx], summed, out=fractional_15N, where=(summed != 0))

    sum_finite = summed[np.isfinite(summed)]
    sum_mean = float(np.mean(sum_finite)) if sum_finite.size else 1.0
    if not np.isfinite(sum_mean) or sum_mean == 0:
        print(f"Warning: summed 12C14N+12C15N channel has invalid mean {sum_mean}. Using 1.0.")
        sum_mean = 1.0

    summed_mean_norm = summed / sum_mean
    summed_mean_norm = np.asarray(summed_mean_norm, dtype=np.float64)
    sum_channel_name = "sum_12C14N_12C15N_mean_norm"

    plot_stack = np.concatenate([stack_mean_norm, summed_mean_norm[None]], axis=0)
    plot_channel_names = mean_norm_channel_names + [sum_channel_name]

    qc_row = {
        "sample": sample_dir.name,
        "stack": stack_path.name,
        "em": em_path.name,
        "fractional_15N_pixels": int(np.isfinite(fractional_15N).sum()),
        "sum_12C14N_12C15N_mean": sum_mean,
    }
    for k, v in summarize(fractional_15N).items():
        qc_row[f"fractional_15N_{k}"] = v

    for i, name in enumerate(raw_channel_names):
        raw_s = summarize(stack[i])
        mean_s = summarize(stack_mean_norm[i])
        for k, v in raw_s.items():
            qc_row[f"whole_field_raw_{name}_{k}"] = v
        for k, v in mean_s.items():
            qc_row[f"whole_field_mean_norm_{name}_{k}"] = v

    sum_mean_s = summarize(summed_mean_norm)
    for k, v in sum_mean_s.items():
        qc_row[f"sum_12C14N_12C15N_mean_norm_{k}"] = v

    print("\nQC Whole-field 15N:")
    print(f"Pixels: {qc_row['fractional_15N_pixels']}")
    print(f"Mean:   {qc_row['fractional_15N_mean']:.6f}")
    print(f"Median: {qc_row['fractional_15N_median']:.6f}")
    print(f"Std:    {qc_row['fractional_15N_std']:.6f}")

    display(pd.DataFrame([qc_row]))

    all_rows = []

    for label_path in tqdm(label_files, desc=f"{sample_dir.name} label images"):
        print(f"\nProcessing {label_path.name}")
        labels = tiff.imread(str(label_path))
        if labels.ndim != 2:
            raise ValueError(f"Expected 2D label TIFF, got shape {labels.shape} for {label_path.name}")

        label_vals = np.unique(labels)
        label_vals = label_vals[(label_vals != 0) & np.isfinite(label_vals)]
        label_vals = np.rint(label_vals).astype(int)
        print(f"Labels in {label_path.name}: {label_vals}")

        scale_y = round(labels.shape[0] / TARGET_STACK_SHAPE[0])
        scale_x = round(labels.shape[1] / TARGET_STACK_SHAPE[1])
        if scale_y != scale_x:
            raise ValueError(f"Inconsistent inferred scale for {label_path.name}: {scale_y} vs {scale_x}")
        scale = int(scale_y)
        print(f"Inferred full-res scale: {scale}x")

        group_rows = []


        for label_idx, lab in enumerate(tqdm(label_vals, desc=f"{label_path.stem}", leave=False)):
            lab = int(lab)
            original_mask = labels == lab
            if not np.any(original_mask):
                continue

            strict_reduced_mask = strict_reduce_mask_to_shape(original_mask, TARGET_STACK_SHAPE)
            if not np.any(strict_reduced_mask):
                continue

            footprint = np.ones((2 * ERODE_PIXELS + 1, 2 * ERODE_PIXELS + 1), dtype=bool)
            eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)

            strict_bbox = bbox_of_mask(strict_reduced_mask)
            if strict_bbox is None:
                continue
            sy0, sy1, sx0, sx1 = strict_bbox
            strict_mask_crop = strict_reduced_mask[sy0:sy1, sx0:sx1]

            original_bbox = bbox_of_mask(original_mask)
            if original_bbox is None:
                continue
            oy0, oy1, ox0, ox1 = original_bbox
            em_crop = em_img[oy0:oy1, ox0:ox1]

            strict_fullres_mask = expand_reduced_mask_to_fullres(strict_reduced_mask, labels.shape)
            strict_fullres_mask_crop = strict_fullres_mask[oy0:oy1, ox0:ox1]

            props = regionprops(original_mask.astype(np.uint8))
            if len(props) == 0:
                continue
            prop = props[0]

            major_px = float(prop.major_axis_length)
            minor_px = float(prop.minor_axis_length)

            centroid_y_full = float(prop.centroid[0])
            centroid_x_full = float(prop.centroid[1])
            centroid_y_red = centroid_y_full / scale
            centroid_x_red = centroid_x_full / scale

            centroid_red_xy = (centroid_y_red, centroid_x_red)
            centroid_full_xy = (centroid_y_full, centroid_x_full)

            centroid_in_strict_mask = centroid_in_mask(strict_reduced_mask, centroid_red_xy)

            # Cell assignment from centroid overlap
            cell_label_id = int(sample_nearest(cell_img, centroid_full_xy))
            if cell_label_id > 0:
                cell_region_mask_full = (cell_img == cell_label_id)
                cell_region_pixel_count = int(np.count_nonzero(cell_region_mask_full))
                centroid_in_cell_mask = centroid_in_mask(cell_region_mask_full, centroid_full_xy)

                # Downsample the full-res cell mask to stack resolution for normalization
                # so it matches the 256 x 256 NanoSIMS images.
                cell_region_mask = strict_reduce_mask_to_shape(
                    cell_region_mask_full, TARGET_STACK_SHAPE
                )
                if not np.any(cell_region_mask):
                    cell_region_mask = None
            else:
                cell_region_mask_full = None
                cell_region_mask = None
                cell_region_pixel_count = 0
                centroid_in_cell_mask = False

            # Cell-based normalization cache
            if cell_label_id > 0 and cell_region_mask is not None and np.any(cell_region_mask):
                if cell_label_id not in cell_norm_cache:
                    cell_stack_mean_norm, cell_field_means = whole_field_mean_norm_masked(
                        stack, raw_channel_names, cell_region_mask
                    )

                    cell_summed = stack[ch2_idx] + stack[ch3_idx]
                    cell_sum_vals = cell_summed[cell_region_mask]
                    cell_sum_mean = float(np.mean(cell_sum_vals)) if cell_sum_vals.size else 1.0
                    if not np.isfinite(cell_sum_mean) or cell_sum_mean == 0:
                        print(
                            f"Warning: cell summed 12C14N+12C15N channel has invalid mean {cell_sum_mean}. Using 1.0."
                        )
                        cell_sum_mean = 1.0

                    cell_summed_mean_norm = cell_summed / cell_sum_mean

                    cell_norm_cache[cell_label_id] = (
                        cell_stack_mean_norm,
                        cell_field_means,
                        cell_summed_mean_norm,
                        cell_sum_mean,
                    )

                cell_stack_mean_norm, cell_field_means, cell_summed_mean_norm, cell_sum_mean = cell_norm_cache[cell_label_id]
            else:
                cell_stack_mean_norm = None
                cell_field_means = None
                cell_summed_mean_norm = None
                cell_sum_mean = np.nan


            strict_centroid_red_local = rel_xy(centroid_red_xy, strict_bbox)
            strict_centroid_full_local = rel_xy(centroid_full_xy, original_bbox)

            # --- stats (field-based) ---
            strict_raw_vals_per_channel = [stack[ch][strict_reduced_mask] for ch in range(n_channels)]
            strict_mean_norm_vals_per_channel = [stack_mean_norm[ch][strict_reduced_mask] for ch in range(n_channels)]
            strict_sum_vals = summed[strict_reduced_mask]
            strict_sum_mean_norm_vals = summed_mean_norm[strict_reduced_mask]
            strict_frac_vals = fractional_15N[strict_reduced_mask]

            eroded_raw_vals_per_channel = (
                [stack[ch][eroded_mask] for ch in range(n_channels)]
                if np.any(eroded_mask)
                else [np.array([]) for _ in range(n_channels)]
            )
            eroded_mean_norm_vals_per_channel = (
                [stack_mean_norm[ch][eroded_mask] for ch in range(n_channels)]
                if np.any(eroded_mask)
                else [np.array([]) for _ in range(n_channels)]
            )
            eroded_sum_vals = summed[eroded_mask] if np.any(eroded_mask) else np.array([])
            eroded_sum_mean_norm_vals = summed_mean_norm[eroded_mask] if np.any(eroded_mask) else np.array([])
            eroded_frac_vals = fractional_15N[eroded_mask] if np.any(eroded_mask) else np.array([])

            # --- stats (cell-based) ---
            if cell_stack_mean_norm is not None:
                strict_cell_norm_vals_per_channel = [
                    cell_stack_mean_norm[ch][strict_reduced_mask] for ch in range(n_channels)
                ]
                strict_cell_sum_mean_norm_vals = cell_summed_mean_norm[strict_reduced_mask]

                eroded_cell_norm_vals_per_channel = (
                    [cell_stack_mean_norm[ch][eroded_mask] for ch in range(n_channels)]
                    if np.any(eroded_mask)
                    else [np.array([]) for _ in range(n_channels)]
                )
                eroded_cell_sum_mean_norm_vals = (
                    cell_summed_mean_norm[eroded_mask] if np.any(eroded_mask) else np.array([])
                )
            else:
                strict_cell_norm_vals_per_channel = [np.array([]) for _ in range(n_channels)]
                strict_cell_sum_mean_norm_vals = np.array([])
                eroded_cell_norm_vals_per_channel = [np.array([]) for _ in range(n_channels)]
                eroded_cell_sum_mean_norm_vals = np.array([])

            # --- row metadata ---
            row = {
                "sample": sample_dir.name,
                "label_id": int(lab),
                "source_label_file": label_path.name,
                "source_stack_file": stack_path.name,
                "source_em_file": em_path.name,
                "source_cell_file": cell_path.name,
                "cell_label_id": int(cell_label_id),
                "cell_region_pixel_count": cell_region_pixel_count,
                "centroid_in_cell_mask": centroid_in_cell_mask,
                "pixel_size_nm": PIXEL_SIZE_NM,
                "normalization_method": "whole_field_mean",
                "cell_normalization_method": "cell_mean" if cell_label_id > 0 else "none",
                "original_label_pixel_count": int(np.count_nonzero(original_mask)),
                "strict_reduced_pixel_count": int(np.count_nonzero(strict_reduced_mask)),
                "strict_eroded_pixel_count": int(np.count_nonzero(eroded_mask)),
                "area_nm2": float(prop.area * PIXEL_SIZE_NM**2),
                "perimeter_nm": float(prop.perimeter * PIXEL_SIZE_NM),
                "aspect_ratio": float(major_px / minor_px) if minor_px > 0 else np.nan,
                "major_axis_length_px": major_px,
                "minor_axis_length_px": minor_px,
                "major_axis_length_nm": float(major_px * PIXEL_SIZE_NM),
                "minor_axis_length_nm": float(minor_px * PIXEL_SIZE_NM),
                "centroid_x_px_fullres": centroid_x_full,
                "centroid_y_px_fullres": centroid_y_full,
                "centroid_x_px_reduced": centroid_x_red,
                "centroid_y_px_reduced": centroid_y_red,
                "centroid_in_strict_reduced_mask": centroid_in_strict_mask,
                "cell_12C14N_12C15N_mean": cell_sum_mean,
            }

            # --- stats writing (field-based) ---
            for ch, name in enumerate(raw_channel_names):
                add_stats(row, f"strict_reduced_raw_{name}", strict_raw_vals_per_channel[ch])
                add_stats(row, f"strict_reduced_mean_norm_{name}", strict_mean_norm_vals_per_channel[ch])
                add_stats(row, f"strict_eroded_raw_{name}", eroded_raw_vals_per_channel[ch])
                add_stats(row, f"strict_eroded_mean_norm_{name}", eroded_mean_norm_vals_per_channel[ch])

            add_stats(row, "strict_reduced_raw_sum_12C14N_12C15N", strict_sum_vals)
            add_stats(row, "strict_reduced_mean_norm_sum_12C14N_12C15N", strict_sum_mean_norm_vals)
            add_stats(row, "strict_reduced_raw_fractional_15N", strict_frac_vals)

            add_stats(row, "strict_eroded_raw_sum_12C14N_12C15N", eroded_sum_vals)
            add_stats(row, "strict_eroded_mean_norm_sum_12C14N_12C15N", eroded_sum_mean_norm_vals)
            add_stats(row, "strict_eroded_raw_fractional_15N", eroded_frac_vals)

            # --- stats writing (cell-based) ---
            for ch, name in enumerate(raw_channel_names):
                add_stats(row, f"strict_reduced_cell_norm_{name}", strict_cell_norm_vals_per_channel[ch])
                add_stats(row, f"strict_eroded_cell_norm_{name}", eroded_cell_norm_vals_per_channel[ch])

                row[f"centroid_strict_reduced_cell_norm_{name}"] = (
                    sample_nearest(cell_stack_mean_norm[ch], centroid_full_xy)
                    if cell_stack_mean_norm is not None
                    else np.nan
                )
                row[f"centroid_strict_eroded_cell_norm_{name}"] = (
                    sample_nearest(cell_stack_mean_norm[ch], centroid_full_xy)
                    if cell_stack_mean_norm is not None
                    else np.nan
                )

            add_stats(row, "strict_reduced_cell_norm_sum_12C14N_12C15N", strict_cell_sum_mean_norm_vals)
            add_stats(row, "strict_eroded_cell_norm_sum_12C14N_12C15N", eroded_cell_sum_mean_norm_vals)

            row["strict_reduced_cell_norm_sum_12C14N_12C15N_values"] = strict_cell_sum_mean_norm_vals.tolist()
            row["strict_eroded_cell_norm_sum_12C14N_12C15N_values"] = eroded_cell_sum_mean_norm_vals.tolist()

            row["centroid_strict_reduced_cell_norm_sum_12C14N_12C15N"] = (
                sample_nearest(cell_summed_mean_norm, centroid_full_xy)
                if cell_summed_mean_norm is not None
                else np.nan
            )
            row["centroid_strict_eroded_cell_norm_sum_12C14N_12C15N"] = (
                sample_nearest(cell_summed_mean_norm, centroid_full_xy)
                if cell_summed_mean_norm is not None
                else np.nan
            )

            npz_path = save_label_data_npz(
                npz_root=NPZ_ROOT,
                label_stem=label_path.stem,
                lab=lab,
                sample=sample_dir.name,
                source_label_file=label_path.name,
                strict_bbox=(sy0, sy1, sx0, sx1),
                original_bbox=(oy0, oy1, ox0, ox1),
                stack=stack,
                stack_mean_norm=stack_mean_norm,
                summed=summed,
                fractional_15N=fractional_15N,
                em_img=em_img,
                strict_mask_crop=strict_mask_crop,
                channel_names=raw_channel_names,
                field_means=field_means,
                cell_label_id=cell_label_id,
                source_cell_file=cell_path.name,
            )

            row["npz_file"] = npz_path.name

            # Add the completed row to both accumulators
            group_rows.append(row.copy())
            all_rows.append(row.copy())


            # =============================
            # plotting (unchanged)
            # =============================
            strict_channel_crops = [plot_stack[ch][sy0:sy1, sx0:sx1] for ch in range(len(plot_channel_names))]
            strict_hist_values = strict_mean_norm_vals_per_channel + [strict_sum_mean_norm_vals]

            strict_summary = (
                f"Label {lab}\n"
                f"Strict reduced pixels: {row['strict_reduced_pixel_count']}\n"
                f"Strict 15N mean: {summarize(strict_frac_vals)['mean']:.6f}\n"
                f"Strict 15N median: {summarize(strict_frac_vals)['median']:.6f}\n"
                f"Strict 15N stdev: {summarize(strict_frac_vals)['std']:.6f}"
            )

            out_prefix = None

            plot_section_clean(
                fig_title=f"{label_path.name} — Label {lab} — Strict reduced mask",
                mask_crop=strict_mask_crop,
                channel_crops=strict_channel_crops,
                hist_values=strict_hist_values,
                channel_display_names=plot_channel_names,
                em_crop=em_crop,
                em_mask_crop=strict_fullres_mask_crop,
                lut_crop=crop_to_bbox(fractional_15N, strict_bbox),
                lut_mask_crop=strict_mask_crop,
                lut_values=strict_frac_vals,
                summary_text=strict_summary,
                norm_xlim_max=3.0,
                show_inline=(label_idx < 4),
                centroid_red_xy=strict_centroid_red_local,
                centroid_full_xy=strict_centroid_full_local,
            )


            if np.any(eroded_mask):
                eroded_summary = (
                    f"Label {lab}\n"
                    f"Eroded reduced pixels: {row['strict_eroded_pixel_count']}\n"
                    f"Eroded 15N mean: {summarize(eroded_frac_vals)['mean']:.6f}\n"
                    f"Eroded 15N median: {summarize(eroded_frac_vals)['median']:.6f}\n"
                    f"Eroded 15N stdev: {summarize(eroded_frac_vals)['std']:.6f}"
                )
                if label_idx < 2:
                    eroded_bbox = bbox_of_mask(eroded_mask)
                    if eroded_bbox is not None:
                        ey0, ey1, ex0, ex1 = eroded_bbox
                        eroded_mask_crop = eroded_mask[ey0:ey1, ex0:ex1]
                        eroded_channel_crops = [
                            plot_stack[ch][ey0:ey1, ex0:ex1] for ch in range(len(plot_channel_names))
                        ]

                        eroded_centroid_red_local = rel_xy(centroid_red_xy, eroded_bbox)
                        eroded_centroid_full_local = rel_xy(centroid_full_xy, original_bbox)

                        plot_section_clean(
                            fig_title=f"{label_path.name} — Label {lab} — Eroded reduced mask (QC only)",
                            mask_crop=eroded_mask_crop,
                            channel_crops=eroded_channel_crops,
                            hist_values=eroded_mean_norm_vals_per_channel + [eroded_sum_mean_norm_vals],
                            channel_display_names=plot_channel_names,
                            em_crop=em_crop,
                            em_mask_crop=None,
                            lut_crop=crop_to_bbox(fractional_15N, eroded_bbox),
                            lut_mask_crop=eroded_mask_crop,
                            lut_values=eroded_frac_vals,
                            summary_text=eroded_summary,
                            norm_xlim_max=3.0,
                            show_inline=True,
                            centroid_red_xy=eroded_centroid_red_local,
                            centroid_full_xy=eroded_centroid_full_local,
                        )

        if group_rows:
            group_df = (
                pd.DataFrame(group_rows)
                .sort_values(["sample", "source_label_file", "label_id"])
                .reset_index(drop=True)
            )
        else:
            group_df = pd.DataFrame(
                columns=[
                    "sample",
                    "label_id",
                    "source_label_file",
                    "source_stack_file",
                    "source_em_file",
                ]
            )

        group_csv_path = output_dir / f"{label_path.stem}_measurements.csv"
        group_df.to_csv(group_csv_path, index=False)
        print(f"Saved group dataframe to: {group_csv_path.resolve()}")

    sample_df = pd.DataFrame(all_rows)
    if not sample_df.empty:
        sample_df = sample_df.sort_values(["sample", "source_label_file", "label_id"]).reset_index(drop=True)

    sample_csv_path = output_dir / f"{sample_dir.name}_label_measurements_mean_norm_strict_names.csv"
    sample_df.to_csv(sample_csv_path, index=False)
    print(f"Saved sample dataframe to: {sample_csv_path.resolve()}")

    return qc_row, sample_df


def main():
    sample_dirs = sorted([p for p in INPUT_ROOT.iterdir() if p.is_dir()])
    if not sample_dirs:
        raise FileNotFoundError(f"No sample subfolders found in {INPUT_ROOT.resolve()}")

    all_samples = []
    qc_rows = []

    for sample_dir in sample_dirs:
        label_dir = sample_dir / "label_images"
        stack_dir = sample_dir / "nanosims_stack"
        em_dir = sample_dir / "input_em"

        if not label_dir.exists() or not stack_dir.exists() or not em_dir.exists():
            print(f"Skipping {sample_dir.name}: missing one of input_em / label_images / nanosims_stack")
            continue

        qc_row, sample_df = process_sample(sample_dir)
        qc_rows.append(qc_row)

        if sample_df is not None and not sample_df.empty:
            all_samples.append(sample_df)

    if len(all_samples) == 0:
        print("No valid rows were produced across samples.")
        return pd.DataFrame()

    final_df = pd.concat(all_samples, ignore_index=True)
    final_df = final_df.sort_values(["sample", "source_label_file", "label_id"]).reset_index(drop=True)

    display(
        final_df[
            [
                "sample",
                "label_id",
                "source_label_file",
                "source_stack_file",
                "source_em_file",
                "pixel_size_nm",
                "normalization_method",
                "original_label_pixel_count",
                "strict_reduced_pixel_count",
                "strict_eroded_pixel_count",
                "area_nm2",
                "perimeter_nm",
                "aspect_ratio",
                "major_axis_length_px",
                "minor_axis_length_px",
                "major_axis_length_nm",
                "minor_axis_length_nm",
                "centroid_x_px_fullres",
                "centroid_y_px_fullres",
                "centroid_x_px_reduced",
                "centroid_y_px_reduced",
                "strict_reduced_raw_fractional_15N_mean",
                "strict_reduced_raw_fractional_15N_median",
                "strict_reduced_raw_fractional_15N_std",
                "strict_eroded_raw_fractional_15N_mean",
                "strict_eroded_raw_fractional_15N_median",
                "strict_eroded_raw_fractional_15N_std",
                "source_cell_file",
                "cell_label_id",
                "cell_region_pixel_count",
                "centroid_in_cell_mask",
                "cell_12C14N_12C15N_mean",
                "cell_normalization_method",
                "strict_reduced_cell_norm_sum_12C14N_12C15N_mean",
                "strict_eroded_cell_norm_sum_12C14N_12C15N_mean",
            ]
        ]
    )

    csv_path = OUTPUT_ROOT / "all_samples_label_measurements_mean_norm_strict_names.csv"
    final_df.to_csv(csv_path, index=False)
    print(f"\nSaved combined dataframe to: {csv_path.resolve()}")

    qc_df = pd.DataFrame(qc_rows)
    qc_path = OUTPUT_ROOT / "all_samples_qc.csv"
    qc_df.to_csv(qc_path, index=False)
    print(f"Saved combined QC summary to: {qc_path.resolve()}")

    return final_df


if __name__ == "__main__":
    df = main()

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:100: UserWarning: Overwriting the cmap 'fiji_lut_from_csv' that was already in the registry.
  mpl.colormaps.register(cmap, name="fiji_lut_from_csv", force=True)

Loaded LUT from LUT.csv (256 entries).
Skipping old: missing one of input_em / label_images / nanosims_stack

=== Sample: S18_Ar2 ===
Using stack: 030625-DNp3e2c8-S18-ROI2.nrrd.tif
Using EM image: S18 Ar2 EM aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar2
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (8567, 8567)
Detected binary cell mask in Cell_S18_Ar2.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S18_Ar2.tif

Whole-field mean normalization factors:
16O: 417.178131
12C21H: 789.539444
12C14N: 3352.454788
12C15N: 896.260498
29Si: 0.004486
31P: 0.870438
32S: 40.208115

QC Whole-field 15N:
Pixels: 65536
Mean:   0.209932
Median: 0.215821
Std:    0.031936

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S18_Ar2,030625-DNp3e2c8-S18-ROI2.nrrd.tif,S18 Ar2 EM aligned.tif,65536,4248.715286,65536,0.209932,0.215821,0.031936,0.012838,...,0.273577,65536,1.0,1.023839,0.195729,0.014122,3.428566,0.936989,1.093978,0.156989

S18_Ar2 label images:   0%|          | 0/5 [00:00<?, ?it/s]

Processing Mitochondria_S18_Ar2.tif
Labels in Mitochondria_S18_Ar2.tif: [10001 10003 10005 10015 10021 10022 10026 10027 10028 10029 10030 10032
 10034 10035 10039 10042 10056 10058 10060 10062 10063 10064 10066 10067
 10072 10073 10074 10075 10076 10077 10079 10081 10083 10084 10086 10090
 10091 10103 10105 10106 10108 10110 10114 10117 10118 10119 10120 10121
 10122 10123 10124 10126 10130 10135 10143 10147 10150 10155 10159 10160
 10161 10162 10163 10165 10166 10170 10172 10173 10174 10175 10177 10178
 10184 10185 10186 10189 10190 10191 10197 10198 10199 10204 10213 10219
 10225 10226 10227 10231 10232 10235 10236 10237 10241 10246 10255 10262
 10265 10267 10274 10275 10276 10277 10278 10279 10280 10281 10282 10283
 10284 10285 10286 10287 10288 10289 10290 10291 10292 10293 10294 10295
 10296 10297 10298]
Inferred full-res scale: 33x

Mitochondria_S18_Ar2:   0%|          | 0/123 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar2\Mitochondria_S18_Ar2_measurements.csv

Processing Mitophagophore_S18_Ar2.tif
Labels in Mitophagophore_S18_Ar2.tif: [1]
Inferred full-res scale: 33x

Mitophagophore_S18_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar2\Mitophagophore_S18_Ar2_measurements.csv

Processing Mitophahophore1-Contents_S18_Ar2.tif
Labels in Mitophahophore1-Contents_S18_Ar2.tif: [1]
Inferred full-res scale: 33x

Mitophahophore1-Contents_S18_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar2\Mitophahophore1-Contents_S18_Ar2_measurements.csv

Processing Mitoplast_S18_Ar2.tif
Labels in Mitoplast_S18_Ar2.tif: [1]
Inferred full-res scale: 33x

Mitoplast_S18_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar2\Mitoplast_S18_Ar2_measurements.csv

Processing PL-Whorl_S18_Ar2.tif
Labels in PL-Whorl_S18_Ar2.tif: [1]
Inferred full-res scale: 33x

PL-Whorl_S18_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar2\PL-Whorl_S18_Ar2_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar2\S18_Ar2_label_measurements_mean_norm_strict_names.csv

=== Sample: S18_Ar3 ===
Using stack: 030525-DNp3e2c8-S18-ROI3.nrrd.tif
Using EM image: S18 Ar3 EM aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar3
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (6854, 6854)
Detected binary cell mask in Cell_S18_Ar3.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S18_Ar3.tif

Whole-field mean normalization factors:
16O: 516.600067
12C21H: 726.568756
12C14N: 2886.465302
12C15N: 787.928635
29Si: 0.004730
31P: 1.822845
32S: 16.642746

QC Whole-field 15N:
Pixels: 65536
Mean:   0.213060
Median: 0.216853
Std:    0.033463

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S18_Ar3,030525-DNp3e2c8-S18-ROI3.nrrd.tif,S18 Ar3 EM aligned.tif,65536,3674.393936,65536,0.21306,0.216853,0.033463,0.029108,...,0.540776,65536,1.0,1.029013,0.277538,0.018779,2.003051,0.830069,1.200538,0.370469

S18_Ar3 label images:   0%|          | 0/7 [00:00<?, ?it/s]

Processing Mitochondria_S18_Ar3.tif
Labels in Mitochondria_S18_Ar3.tif: [4001 4002 4004 4005 4006 4007 4008 4009 4011 4018 4024 4031 4033 4034
 4035 4039 4040 4042 4046 4047 4048 4053 4064 4065 4066 4069 4071 4075
 4082 4084 4092 4093 4094 4095 4098 4104 4105 4106 4113 4114 4115 4117
 4121 4123 4124 4125 4130 4131 4135 4136 4137 4140 4149 4157 4160 4165
 4169 4174 4176 4178 4180 4186 4190 4191 4192 4193 4194 4199 4201 4202
 4214 4215 4216 4219 4222 4223 4226 4229 4234 4236 4248 4250 4252 4254
 4256 4257 4258 4260 4263 4264 4267 4271 4277 4279 4280 4284 4286 4287
 4290 4291 4292 4294 4297 4298 4299 4300 4302 4303 4304 4305 4306 4307
 4308 4309 4310 4311 4312 4313 4314 4315 4316 4317 4318 4319 4320 4321]
Inferred full-res scale: 27x

Mitochondria_S18_Ar3:   0%|          | 0/126 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar3\Mitochondria_S18_Ar3_measurements.csv

Processing Mitolysosome1-Contents_S18_Ar3.tif
Labels in Mitolysosome1-Contents_S18_Ar3.tif: [1]
Inferred full-res scale: 27x

Mitolysosome1-Contents_S18_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar3\Mitolysosome1-Contents_S18_Ar3_measurements.csv

Processing Mitolysosome_S18_Ar3.tif
Labels in Mitolysosome_S18_Ar3.tif: [1]
Inferred full-res scale: 27x

Mitolysosome_S18_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar3\Mitolysosome_S18_Ar3_measurements.csv

Processing Mitophagophore1-Contents_S18_Ar3.tif
Labels in Mitophagophore1-Contents_S18_Ar3.tif: [1]
Inferred full-res scale: 27x

Mitophagophore1-Contents_S18_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar3\Mitophagophore1-Contents_S18_Ar3_measurements.csv

Processing Mitophagophore_S18_Ar3.tif
Labels in Mitophagophore_S18_Ar3.tif: [1]
Inferred full-res scale: 27x

Mitophagophore_S18_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar3\Mitophagophore_S18_Ar3_measurements.csv

Processing PL-Whorl_S18_Ar3.tif
Labels in PL-Whorl_S18_Ar3.tif: [1]
Inferred full-res scale: 27x

PL-Whorl_S18_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar3\PL-Whorl_S18_Ar3_measurements.csv

Processing Rupture-UW_S18_Ar3.tif
Labels in Rupture-UW_S18_Ar3.tif: [1]
Inferred full-res scale: 27x

Rupture-UW_S18_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar3\Rupture-UW_S18_Ar3_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar3\S18_Ar3_label_measurements_mean_norm_strict_names.csv

=== Sample: S18_Ar4 ===
Using stack: 030525-DNp3e2c8-S18-ROI4.nrrd.tif
Using EM image: S18Ar4 em aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (8567, 8567)
Detected binary cell mask in Cell_S18_Ar4.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S18_Ar4.tif

Whole-field mean normalization factors:
16O: 267.579498
12C21H: 547.689117
12C14N: 2885.928772
12C15N: 719.816986
29Si: 0.001526
31P: 0.464233
32S: 17.403244

QC Whole-field 15N:
Pixels: 65536
Mean:   0.196861
Median: 0.206431
Std:    0.040315

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S18_Ar4,030525-DNp3e2c8-S18-ROI4.nrrd.tif,S18Ar4 em aligned.tif,65536,3605.745758,65536,0.196861,0.206431,0.040315,0.010264,...,0.344763,65536,1.0,1.028636,0.241582,0.011925,2.019554,0.928518,1.122653,0.194135

S18_Ar4 label images:   0%|          | 0/11 [00:00<?, ?it/s]

Processing Mitochondria_S18_Ar4.tif
Labels in Mitochondria_S18_Ar4.tif: [10001 10002 10003 10005 10006 10009 10011 10014 10017 10018 10024 10029
 10032 10037 10038 10039 10040 10042 10044 10045 10050 10052 10053 10059
 10061 10063 10066 10068 10075 10076 10079 10080 10085 10087 10094 10100
 10101 10102 10103 10104 10109 10111 10117 10124 10126 10127 10128 10129
 10136 10139 10141 10143 10144 10148 10150 10151 10152 10153 10154 10155
 10156 10157 10158 10163 10164 10165 10169 10171 10172 10179 10180 10192
 10194 10199 10201 10202 10203 10207 10208 10211 10214 10216 10218 10220
 10222 10229 10231 10236 10237 10238 10239 10247 10249 10254 10255 10256
 10258 10259 10262 10263 10267 10269 10270 10271 10272 10273 10276 10278
 10279 10280 10281 10282 10287 10288 10289 10290 10292 10293 10297 10301
 10305 10306 10307 10308 10309 10312 10314 10323 10324 10326 10327 10331
 10332 10333 10335 10339 10340 10341 10343 10344 10345 10346 10348 10349
 10350 10351 10354 10357 10361 10362 10363 10367 10368 10369 10370 10371
 10372 10373 10374 10375 10376 10377 10378 10379 10380 10381 10382 10383
 10384 10385 10386 10387 10388 10389 10390 10391 10392 10393 10394 10395
 10396 10397 10398 10399 10400 10401 10402 10403 10404 10405 10406 10407
 10408 10409 10410]
Inferred full-res scale: 33x

Mitochondria_S18_Ar4:   0%|          | 0/195 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4\Mitochondria_S18_Ar4_measurements.csv

Processing Mitolysosome1-Contents_S18_Ar4.tif
Labels in Mitolysosome1-Contents_S18_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitolysosome1-Contents_S18_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4\Mitolysosome1-Contents_S18_Ar4_measurements.csv

Processing Mitolysosome2-Contents_S18_Ar4.tif
Labels in Mitolysosome2-Contents_S18_Ar4.tif: [1 2 3 4 5]
Inferred full-res scale: 33x

Mitolysosome2-Contents_S18_Ar4:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4\Mitolysosome2-Contents_S18_Ar4_measurements.csv

Processing Mitolysosome3-Contents_S18_Ar4.tif
Labels in Mitolysosome3-Contents_S18_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitolysosome3-Contents_S18_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4\Mitolysosome3-Contents_S18_Ar4_measurements.csv

Processing Mitolysosome4-Contents_S18_Ar4.tif
Labels in Mitolysosome4-Contents_S18_Ar4.tif: [1 2 3]
Inferred full-res scale: 33x

Mitolysosome4-Contents_S18_Ar4:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4\Mitolysosome4-Contents_S18_Ar4_measurements.csv

Processing Mitolysosome5-Contents_S18_Ar4.tif
Labels in Mitolysosome5-Contents_S18_Ar4.tif: [1 2 3 4]
Inferred full-res scale: 33x

Mitolysosome5-Contents_S18_Ar4:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4\Mitolysosome5-Contents_S18_Ar4_measurements.csv

Processing Mitolysosome_S18_Ar4.tif
Labels in Mitolysosome_S18_Ar4.tif: [2 3 4 5 6]
Inferred full-res scale: 33x

Mitolysosome_S18_Ar4:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4\Mitolysosome_S18_Ar4_measurements.csv

Processing Mitophagophore1-Contents_S18_Ar4.tif
Labels in Mitophagophore1-Contents_S18_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitophagophore1-Contents_S18_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4\Mitophagophore1-Contents_S18_Ar4_measurements.csv

Processing Mitophagophore_S18_Ar4.tif
Labels in Mitophagophore_S18_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitophagophore_S18_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4\Mitophagophore_S18_Ar4_measurements.csv

Processing PL-Whorl_S18_Ar4.tif
Labels in PL-Whorl_S18_Ar4.tif: [1]
Inferred full-res scale: 33x

PL-Whorl_S18_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4\PL-Whorl_S18_Ar4_measurements.csv

Processing Rupture-W_S18_Ar4.tif
Labels in Rupture-W_S18_Ar4.tif: [1]
Inferred full-res scale: 33x

Rupture-W_S18_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4\Rupture-W_S18_Ar4_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar4\S18_Ar4_label_measurements_mean_norm_strict_names.csv

=== Sample: S18_Ar5 ===
Using stack: 030525-DNp3e2c8-S18-ROI5.nrrd.tif
Using EM image: S18 Ar5 EM aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar5
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (8567, 8567)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S18_Ar5.tif

Whole-field mean normalization factors:
16O: 410.283203
12C21H: 674.060242
12C14N: 3372.986954
12C15N: 835.670059
29Si: 0.002472
31P: 1.144943
32S: 19.201279

QC Whole-field 15N:
Pixels: 65536
Mean:   0.196816
Median: 0.203342
Std:    0.040721

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S18_Ar5,030525-DNp3e2c8-S18-ROI5.nrrd.tif,S18 Ar5 EM aligned.tif,65536,4208.657013,65536,0.196816,0.203342,0.040721,0.014514,...,0.364559,65536,1.0,1.016476,0.154644,0.019721,2.196188,0.945432,1.081343,0.13591

S18_Ar5 label images:   0%|          | 0/7 [00:00<?, ?it/s]

Processing Mitochondria_S18_Ar5.tif
Labels in Mitochondria_S18_Ar5.tif: [10001 10002 10003 10004 10006 10007 10008 10009 10010 10014 10023 10025
 10026 10027 10028 10029 10032 10035 10039 10040 10041 10042 10043 10044
 10046 10047 10050 10058 10065 10070 10071 10072 10074 10075 10077 10078
 10079 10086 10092 10093 10103 10106 10109 10110 10111 10118 10119 10120
 10121 10122 10123 10124 10125 10126 10127 10128 10129 10130 10131]
Inferred full-res scale: 33x

Mitochondria_S18_Ar5:   0%|          | 0/59 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar5\Mitochondria_S18_Ar5_measurements.csv

Processing Mitolysosome1-Contents_S18_Ar5.tif
Labels in Mitolysosome1-Contents_S18_Ar5.tif: [1 2 4 5]
Inferred full-res scale: 33x

Mitolysosome1-Contents_S18_Ar5:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar5\Mitolysosome1-Contents_S18_Ar5_measurements.csv

Processing Mitolysosome2-Contents_S18_Ar5.tif
Labels in Mitolysosome2-Contents_S18_Ar5.tif: [1 2 3]
Inferred full-res scale: 33x

Mitolysosome2-Contents_S18_Ar5:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar5\Mitolysosome2-Contents_S18_Ar5_measurements.csv

Processing Mitolysosome2-WMB_S18_Ar5.tif
Labels in Mitolysosome2-WMB_S18_Ar5.tif: [1]
Inferred full-res scale: 33x

Mitolysosome2-WMB_S18_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar5\Mitolysosome2-WMB_S18_Ar5_measurements.csv

Processing Mitolysosome_S18_Ar5.tif
Labels in Mitolysosome_S18_Ar5.tif: [1 2]
Inferred full-res scale: 33x

Mitolysosome_S18_Ar5:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar5\Mitolysosome_S18_Ar5_measurements.csv

Processing Rupture-W1-Contents_S18_Ar5.tif
Labels in Rupture-W1-Contents_S18_Ar5.tif: [1 2 3 4 5]
Inferred full-res scale: 33x

Rupture-W1-Contents_S18_Ar5:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar5\Rupture-W1-Contents_S18_Ar5_measurements.csv

Processing Rupture-W_S18_Ar5.tif
Labels in Rupture-W_S18_Ar5.tif: [1 2]
Inferred full-res scale: 33x

Rupture-W_S18_Ar5:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar5\Rupture-W_S18_Ar5_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar5\S18_Ar5_label_measurements_mean_norm_strict_names.csv

=== Sample: S18_Ar6 ===
Using stack: 030525-DNp3e2c8-S18-ROI6.nrrd.tif
Using EM image: S18Ar6 em aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar6
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (7425, 7425)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S18_Ar6.tif

Whole-field mean normalization factors:
16O: 550.906586
12C21H: 928.168930
12C14N: 3605.578430
12C15N: 983.433395
29Si: 0.001892
31P: 1.537613
32S: 20.146301

QC Whole-field 15N:
Pixels: 65536
Mean:   0.212123
Median: 0.219296
Std:    0.037139

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S18_Ar6,030525-DNp3e2c8-S18-ROI6.nrrd.tif,S18Ar6 em aligned.tif,65536,4589.011826,65536,0.212123,0.219296,0.037139,0.02118,...,0.397095,65536,1.0,1.032248,0.16744,0.006102,1.593589,0.945519,1.09675,0.151231

S18_Ar6 label images:   0%|          | 0/10 [00:00<?, ?it/s]

Processing Mitochondria_S18_Ar6.tif
Labels in Mitochondria_S18_Ar6.tif: [4001 4002 4003 4004 4005 4006 4007 4009 4010 4011 4012 4014 4015 4016
 4018 4019 4024 4028 4029 4031 4035 4036 4037 4040 4043 4047 4048 4049
 4050 4051 4052 4055 4057 4059 4060 4061 4063 4065 4067 4068 4069 4070
 4071 4072 4075 4076 4078 4083 4084 4086 4087 4088 4089 4090 4095 4096
 4097 4100 4104 4111 4114 4115 4118 4119 4125 4130 4133 4137 4140 4143
 4144 4145 4148 4149 4154 4155 4156 4157 4160 4161 4165 4168 4171 4172
 4177 4179 4180 4193 4203 4204 4205 4206 4207 4208 4209 4210 4211 4212
 4213 4214 4215 4216 4217 4218 4219 4220 4221 4222 4223 4224 4225 4226
 4227 4228 4229 4230 4231 4232 4233 4234 4236 4237 4238 4239 4240 4241
 4242 4243 4244 4245 4246 4247 4248 4249 4250 4251 4252 4253 4254 4255
 4256 4257 4258]
Inferred full-res scale: 29x

Mitochondria_S18_Ar6:   0%|          | 0/143 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar6\Mitochondria_S18_Ar6_measurements.csv

Processing Mitolysosome1-Contents_S18_Ar6.tif
Labels in Mitolysosome1-Contents_S18_Ar6.tif: [1 2]
Inferred full-res scale: 29x

Mitolysosome1-Contents_S18_Ar6:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar6\Mitolysosome1-Contents_S18_Ar6_measurements.csv

Processing Mitolysosome2-Contents_S18_Ar6.tif
Labels in Mitolysosome2-Contents_S18_Ar6.tif: [1 2]
Inferred full-res scale: 29x

Mitolysosome2-Contents_S18_Ar6:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar6\Mitolysosome2-Contents_S18_Ar6_measurements.csv

Processing Mitolysosome2-WMB_S18_Ar6.tif
Labels in Mitolysosome2-WMB_S18_Ar6.tif: [1]
Inferred full-res scale: 29x

Mitolysosome2-WMB_S18_Ar6:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar6\Mitolysosome2-WMB_S18_Ar6_measurements.csv

Processing Mitolysosome3-Contents_S18_Ar6.tif
Labels in Mitolysosome3-Contents_S18_Ar6.tif: [1]
Inferred full-res scale: 29x

Mitolysosome3-Contents_S18_Ar6:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar6\Mitolysosome3-Contents_S18_Ar6_measurements.csv

Processing Mitolysosome4-Contents_S18_Ar6.tif
Labels in Mitolysosome4-Contents_S18_Ar6.tif: [1]
Inferred full-res scale: 29x

Mitolysosome4-Contents_S18_Ar6:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar6\Mitolysosome4-Contents_S18_Ar6_measurements.csv

Processing Mitolysosome5-Contents_S18_Ar6.tif
Labels in Mitolysosome5-Contents_S18_Ar6.tif: [1 2]
Inferred full-res scale: 29x

Mitolysosome5-Contents_S18_Ar6:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar6\Mitolysosome5-Contents_S18_Ar6_measurements.csv

Processing Mitolysosome6-Contents_S18_Ar6.tif
Labels in Mitolysosome6-Contents_S18_Ar6.tif: [1 2 3 4 5]
Inferred full-res scale: 29x

Mitolysosome6-Contents_S18_Ar6:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar6\Mitolysosome6-Contents_S18_Ar6_measurements.csv

Processing Mitolysosome_S18_Ar6.tif
Labels in Mitolysosome_S18_Ar6.tif: [1 2 3 4 5 6]
Inferred full-res scale: 29x

Mitolysosome_S18_Ar6:   0%|          | 0/6 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar6\Mitolysosome_S18_Ar6_measurements.csv

Processing Mitoplast_S18_Ar6.tif
Labels in Mitoplast_S18_Ar6.tif: [1]
Inferred full-res scale: 29x

Mitoplast_S18_Ar6:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar6\Mitoplast_S18_Ar6_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S18_Ar6\S18_Ar6_label_measurements_mean_norm_strict_names.csv

=== Sample: S20_Ar1 ===
Using stack: 030625-DNp3e2c9-S20-ROI1.nrrd.tif
Using EM image: S20 Ar1 EM aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)
Detected binary cell mask in Cell_S20_Ar1.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S20_Ar1.tif

Whole-field mean normalization factors:
16O: 318.050476
12C21H: 568.744339
12C14N: 3529.970810
12C15N: 280.514877
29Si: 0.001755
31P: 0.417831
32S: 14.654022

QC Whole-field 15N:
Pixels: 65536
Mean:   0.069868
Median: 0.074508
Std:    0.022874

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S20_Ar1,030625-DNp3e2c9-S20-ROI1.nrrd.tif,S20 Ar1 EM aligned.tif,65536,3810.485687,65536,0.069868,0.074508,0.022874,0.0,...,0.409444,65536,1.0,1.084901,0.273374,0.001837,1.531301,0.99856,1.143949,0.145388

S20_Ar1 label images:   0%|          | 0/16 [00:00<?, ?it/s]

Processing Mitlysosome_S20_Ar1.tif
Labels in Mitlysosome_S20_Ar1.tif: [ 1  2  3  4  5  6  7  8  9 10]
Inferred full-res scale: 38x

Mitlysosome_S20_Ar1:   0%|          | 0/10 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitlysosome_S20_Ar1_measurements.csv

Processing Mitochondria_S20_Ar1.tif
Labels in Mitochondria_S20_Ar1.tif: [4001 4002 4003 4004 4006 4008 4010 4012 4013 4014 4015 4016 4017 4018
 4019 4020 4021 4022 4023 4024 4025 4027 4028 4029 4030 4031 4034 4035
 4040 4041 4042 4043 4044 4045 4050 4051 4052 4053 4055 4056 4058 4059
 4060 4061 4062 4064 4066 4068 4070 4071 4072 4073 4074 4076 4077 4078
 4081 4083 4084 4085 4086 4089 4092 4093 4094 4095 4098 4099 4101 4102
 4103 4104 4106 4107 4109 4113 4114 4115 4116 4117 4120 4121 4122 4123
 4124 4127 4130 4132 4133 4134 4135 4136 4142 4143 4146 4150 4151 4152
 4161 4163 4172 4173 4174 4175 4176 4177 4179 4180 4184 4185 4187 4189
 4190 4192 4195 4196 4200 4201 4202 4204 4209 4210 4213 4215 4216 4225
 4226 4227 4229 4231 4232 4234 4237 4240 4242 4246 4248 4249 4250 4251
 4252 4253 4254 4261 4263 4265 4266 4267 4268 4269 4270 4271 4277 4279
 4283 4284 4287 4288 4289 4291 4292 4294 4297 4298 4300 4302 4303 4310
 4311 4312 4314 4315 4316 4317 4318 4319 4320 4321 4322 4323 4324 4325
 4326 4327 4328 4329 4330 4331 4332 4333 4335 4336 4337 4338 4339 4340
 4341 4342 4343 4344 4345 4346 4347 4348 4349 4350 4351 4352 4353 4354
 4355 4356 4357 4358 4359 4360 4361 4362 4363 4364 4365 4366 4367 4368
 4369 4370 4371 4372 4374 4375 4376]
Inferred full-res scale: 38x

Mitochondria_S20_Ar1:   0%|          | 0/231 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitochondria_S20_Ar1_measurements.csv

Processing Mitolysosome1-Contents_S20_Ar1.tif
Labels in Mitolysosome1-Contents_S20_Ar1.tif: [1 2 3]
Inferred full-res scale: 38x

Mitolysosome1-Contents_S20_Ar1:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitolysosome1-Contents_S20_Ar1_measurements.csv

Processing Mitolysosome10-Contents_S20_Ar1.tif
Labels in Mitolysosome10-Contents_S20_Ar1.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome10-Contents_S20_Ar1:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitolysosome10-Contents_S20_Ar1_measurements.csv

Processing Mitolysosome2-Contents_S20_Ar1.tif
Labels in Mitolysosome2-Contents_S20_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome2-Contents_S20_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitolysosome2-Contents_S20_Ar1_measurements.csv

Processing Mitolysosome3-Contents_S20_Ar1.tif
Labels in Mitolysosome3-Contents_S20_Ar1.tif: [1 2 3]
Inferred full-res scale: 38x

Mitolysosome3-Contents_S20_Ar1:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitolysosome3-Contents_S20_Ar1_measurements.csv

Processing Mitolysosome3-WMB_S20_Ar1.tif
Labels in Mitolysosome3-WMB_S20_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome3-WMB_S20_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitolysosome3-WMB_S20_Ar1_measurements.csv

Processing Mitolysosome4-Contents_S20_Ar1.tif
Labels in Mitolysosome4-Contents_S20_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome4-Contents_S20_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitolysosome4-Contents_S20_Ar1_measurements.csv

Processing Mitolysosome5-Contents_S20_Ar1.tif
Labels in Mitolysosome5-Contents_S20_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome5-Contents_S20_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitolysosome5-Contents_S20_Ar1_measurements.csv

Processing Mitolysosome6-Contents_S20_Ar1.tif
Labels in Mitolysosome6-Contents_S20_Ar1.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome6-Contents_S20_Ar1:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitolysosome6-Contents_S20_Ar1_measurements.csv

Processing Mitolysosome7-Contents_S20_Ar1.tif
Labels in Mitolysosome7-Contents_S20_Ar1.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome7-Contents_S20_Ar1:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitolysosome7-Contents_S20_Ar1_measurements.csv

Processing Mitolysosome7-WMB_S20_Ar1.tif
Labels in Mitolysosome7-WMB_S20_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome7-WMB_S20_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitolysosome7-WMB_S20_Ar1_measurements.csv

Processing Mitolysosome8-Contents_S20_Ar1.tif
Labels in Mitolysosome8-Contents_S20_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome8-Contents_S20_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitolysosome8-Contents_S20_Ar1_measurements.csv

Processing Mitolysosome9-Contents_S20_Ar1.tif
Labels in Mitolysosome9-Contents_S20_Ar1.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome9-Contents_S20_Ar1:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\Mitolysosome9-Contents_S20_Ar1_measurements.csv

Processing PL-Whorl_S20_Ar1.tif
Labels in PL-Whorl_S20_Ar1.tif: [1]
Inferred full-res scale: 38x

PL-Whorl_S20_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\PL-Whorl_S20_Ar1_measurements.csv

Processing SL_S20_Ar1.tif
Labels in SL_S20_Ar1.tif: [1]
Inferred full-res scale: 38x

SL_S20_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\SL_S20_Ar1_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar1\S20_Ar1_label_measurements_mean_norm_strict_names.csv

=== Sample: S20_Ar2 ===
Using stack: 030625-DNp3e2c9-S20-ROI2.nrrd.tif
Using EM image: S20 Ar2 EM aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar2
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S20_Ar2.tif

Whole-field mean normalization factors:
16O: 600.843826
12C21H: 1009.799484
12C14N: 3038.854355
12C15N: 159.100662
29Si: 0.025940
31P: 1.118790
32S: 18.309662

QC Whole-field 15N:
Pixels: 65536
Mean:   0.043525
Median: 0.046279
Std:    0.020637

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S20_Ar2,030625-DNp3e2c9-S20-ROI2.nrrd.tif,S20 Ar2 EM aligned.tif,65536,3197.955017,65536,0.043525,0.046279,0.020637,0.0,...,0.710008,65536,1.0,1.110084,0.505389,0.004378,2.415294,0.655419,1.326473,0.671054

S20_Ar2 label images:   0%|          | 0/6 [00:00<?, ?it/s]

Processing Mitochondrial_S20_Ar2.tif
Labels in Mitochondrial_S20_Ar2.tif: [4001 4002 4003 4004 4005 4007 4008 4009 4011 4015 4021 4022 4023 4024
 4025 4026 4027 4028 4029 4030 4031 4032 4034 4035 4036 4037 4038 4039
 4040 4042 4043 4044 4046 4047 4048 4049 4050 4052 4053 4054 4056 4059
 4061 4064 4065 4067 4070 4072 4075 4076 4078 4079 4080 4081 4085 4088
 4089 4090 4091 4092 4093 4095 4096 4097 4098 4101 4102 4103 4104 4105
 4108 4113 4114 4115 4116 4117 4118 4119 4120 4122 4123 4126 4127 4130
 4131 4132 4133 4137 4138 4139 4147 4148 4149 4150 4151 4152 4154 4155
 4156 4157 4159 4161 4162 4163 4166 4167 4170 4171 4174 4175 4176 4177
 4178 4179 4180 4181 4182 4183 4184 4185 4186 4187 4188 4189 4190 4191
 4192 4193 4194 4195 4196 4197 4198 4199]
Inferred full-res scale: 38x

Mitochondrial_S20_Ar2:   0%|          | 0/134 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar2\Mitochondrial_S20_Ar2_measurements.csv

Processing Mitolysosome1-Contents_S20_Ar2.tif
Labels in Mitolysosome1-Contents_S20_Ar2.tif: [1]
Inferred full-res scale: 38x

Mitolysosome1-Contents_S20_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar2\Mitolysosome1-Contents_S20_Ar2_measurements.csv

Processing Mitolysosome2-Contents_S20_Ar2.tif
Labels in Mitolysosome2-Contents_S20_Ar2.tif: [1]
Inferred full-res scale: 38x

Mitolysosome2-Contents_S20_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar2\Mitolysosome2-Contents_S20_Ar2_measurements.csv

Processing Mitolysosome_S20_Ar2.tif
Labels in Mitolysosome_S20_Ar2.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome_S20_Ar2:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar2\Mitolysosome_S20_Ar2_measurements.csv

Processing PL-Speckled_S20_Ar2.tif
Labels in PL-Speckled_S20_Ar2.tif: [1]
Inferred full-res scale: 38x

PL-Speckled_S20_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar2\PL-Speckled_S20_Ar2_measurements.csv

Processing SL_S20_Ar2.tif
Labels in SL_S20_Ar2.tif: [1]
Inferred full-res scale: 38x

SL_S20_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar2\SL_S20_Ar2_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar2\S20_Ar2_label_measurements_mean_norm_strict_names.csv

=== Sample: S20_Ar3 ===
Using stack: 030625-DNp3e2c9-S20-ROI3.nrrd.tif
Using EM image: S20 Ar3 em aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S20_Ar3.tif

Whole-field mean normalization factors:
16O: 552.470978
12C21H: 972.553680
12C14N: 3948.390839
12C15N: 245.520676
29Si: 0.003265
31P: 0.821854
32S: 19.159286

QC Whole-field 15N:
Pixels: 65536
Mean:   0.053068
Median: 0.053801
Std:    0.028451

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S20_Ar3,030625-DNp3e2c9-S20-ROI3.nrrd.tif,S20 Ar3 em aligned.tif,65536,4193.911514,65536,0.053068,0.053801,0.028451,0.0,...,0.626328,65536,1.0,1.166214,0.407686,0.000954,1.791645,0.915553,1.270413,0.35486

S20_Ar3 label images:   0%|          | 0/11 [00:00<?, ?it/s]

Processing Mitochondria_S20_Ar3.tif
Labels in Mitochondria_S20_Ar3.tif: [4001 4002 4003 4004 4005 4007 4008 4009 4011 4015 4021 4022 4023 4024
 4025 4026 4027 4028 4029 4030 4031 4032 4034 4035 4036 4037 4038 4039
 4040 4042 4043 4044 4046 4047 4048 4049 4050 4052 4053 4054 4056 4059
 4061 4064 4065 4067 4070 4072 4075 4076 4078 4079 4080 4081 4085 4088
 4089 4090 4091 4092 4093 4095 4096 4097 4098 4101 4102 4103 4104 4105
 4108 4113 4114 4115 4116 4117 4118 4119 4120 4122 4123 4126 4127 4130
 4131 4132 4133 4137 4138 4139 4147 4148 4149 4150 4151 4152 4154 4155
 4156 4157 4159 4161 4162 4163 4166 4167 4170 4171 4174 4175 4176 4177
 4178 4179 4180 4181 4182 4183 4184 4185 4186 4187 4188 4189 4190 4191
 4192 4193 4194 4195 4196 4197 4198 4199]
Inferred full-res scale: 38x

Mitochondria_S20_Ar3:   0%|          | 0/134 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3\Mitochondria_S20_Ar3_measurements.csv

Processing Mitolysosome1-Contents_S20_Ar3.tif
Labels in Mitolysosome1-Contents_S20_Ar3.tif: [1]
Inferred full-res scale: 38x

Mitolysosome1-Contents_S20_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3\Mitolysosome1-Contents_S20_Ar3_measurements.csv

Processing Mitolysosome2-Contents_S20_Ar3.tif
Labels in Mitolysosome2-Contents_S20_Ar3.tif: [1 2 3 4 5 6 7 8]
Inferred full-res scale: 38x

Mitolysosome2-Contents_S20_Ar3:   0%|          | 0/8 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3\Mitolysosome2-Contents_S20_Ar3_measurements.csv

Processing Mitolysosome3-Contents_S20_Ar3.tif
Labels in Mitolysosome3-Contents_S20_Ar3.tif: [1 2 3]
Inferred full-res scale: 38x

Mitolysosome3-Contents_S20_Ar3:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3\Mitolysosome3-Contents_S20_Ar3_measurements.csv

Processing Mitolysosome3-WMB_S20_Ar3.tif
Labels in Mitolysosome3-WMB_S20_Ar3.tif: [1]
Inferred full-res scale: 38x

Mitolysosome3-WMB_S20_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3\Mitolysosome3-WMB_S20_Ar3_measurements.csv

Processing Mitolysosome4-CM_S20_Ar3.tif
Labels in Mitolysosome4-CM_S20_Ar3.tif: [1]
Inferred full-res scale: 38x

Mitolysosome4-CM_S20_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3\Mitolysosome4-CM_S20_Ar3_measurements.csv

Processing Mitolysosome4-Contents_S20_Ar3.tif
Labels in Mitolysosome4-Contents_S20_Ar3.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome4-Contents_S20_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3\Mitolysosome4-Contents_S20_Ar3_measurements.csv

Processing Mitolysosome5-CM_S20_Ar3.tif
Labels in Mitolysosome5-CM_S20_Ar3.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome5-CM_S20_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3\Mitolysosome5-CM_S20_Ar3_measurements.csv

Processing Mitolysosome5-Contents_S20_Ar3.tif
Labels in Mitolysosome5-Contents_S20_Ar3.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome5-Contents_S20_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3\Mitolysosome5-Contents_S20_Ar3_measurements.csv

Processing Mitolysosome_S20_Ar3.tif
Labels in Mitolysosome_S20_Ar3.tif: [1 2 3 4 5]
Inferred full-res scale: 38x

Mitolysosome_S20_Ar3:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3\Mitolysosome_S20_Ar3_measurements.csv

Processing SL_S20_Ar3.tif
Labels in SL_S20_Ar3.tif: [1 2]
Inferred full-res scale: 38x

SL_S20_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3\SL_S20_Ar3_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar3\S20_Ar3_label_measurements_mean_norm_strict_names.csv

=== Sample: S20_Ar4 ===
Using stack: 030625-DNp3e2c9-S20-ROI4.nrrd.tif
Using EM image: S20 Ar4 em aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (8567, 8567)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S20_Ar4.tif

Whole-field mean normalization factors:
16O: 393.167145
12C21H: 705.901779
12C14N: 3275.483521
12C15N: 171.154770
29Si: 0.002258
31P: 0.812546
32S: 15.023254

QC Whole-field 15N:
Pixels: 65536
Mean:   0.044183
Median: 0.046882
Std:    0.022238

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S20_Ar4,030625-DNp3e2c9-S20-ROI4.nrrd.tif,S20 Ar4 em aligned.tif,65536,3446.63829,65536,0.044183,0.046882,0.022238,0.0,...,0.732198,65536,1.0,1.148946,0.425862,0.001451,1.867907,0.912773,1.292636,0.379863

S20_Ar4 label images:   0%|          | 0/14 [00:00<?, ?it/s]

Processing Mitochondria_S20_Ar4.tif
Labels in Mitochondria_S20_Ar4.tif: [4001 4002 4003 4005 4007 4016 4020 4023 4025 4027 4028 4029 4030 4033
 4036 4037 4038 4039 4040 4041 4042 4043 4044 4045 4046 4047 4048 4050
 4052 4053 4055 4058 4060 4061 4062 4063 4064 4065 4066 4067 4068 4069
 4070 4071 4072 4073 4074 4077 4078 4079 4083 4084 4087 4088 4090 4091
 4095 4096 4097 4100 4101 4102 4103 4104 4105 4108 4110 4111 4112 4113
 4114 4115 4116 4118 4121 4122 4123 4124 4126 4129 4134 4136 4138 4142
 4143 4144 4145 4146 4149 4154 4158 4160 4162 4164 4166 4168 4169 4170
 4172 4173 4175 4178 4179 4181 4182 4183 4184 4185 4186 4187 4189 4190
 4191 4192 4193 4204 4205 4206 4207 4208 4209 4210 4211 4212 4214 4215
 4220 4222 4226 4233 4234 4235 4236 4238 4239 4244 4245 4246 4247 4248
 4249 4250 4251 4252 4253 4254 4255 4256 4258 4261 4262 4263 4264 4265
 4266 4268 4270 4271 4273 4274 4275 4276 4277 4278 4279 4280 4281 4282
 4283 4284 4285 4286 4287 4288 4289 4290 4291 4292 4293 4294 4295 4296
 4297 4298 4299 4300 4301 4302 4303 4304 4305 4306 4307 4308 4309 4310
 4311 4312 4313]
Inferred full-res scale: 33x

Mitochondria_S20_Ar4:   0%|          | 0/199 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Mitochondria_S20_Ar4_measurements.csv

Processing Mitolysosome1-Contents_S20_Ar4.tif
Labels in Mitolysosome1-Contents_S20_Ar4.tif: [1 2]
Inferred full-res scale: 33x

Mitolysosome1-Contents_S20_Ar4:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Mitolysosome1-Contents_S20_Ar4_measurements.csv

Processing Mitolysosome2-Contents_S20_Ar4.tif
Labels in Mitolysosome2-Contents_S20_Ar4.tif: [1 2 3 4]
Inferred full-res scale: 33x

Mitolysosome2-Contents_S20_Ar4:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Mitolysosome2-Contents_S20_Ar4_measurements.csv

Processing Mitolysosome3-Contents_S20_Ar4.tif
Labels in Mitolysosome3-Contents_S20_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitolysosome3-Contents_S20_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Mitolysosome3-Contents_S20_Ar4_measurements.csv

Processing Mitolysosome4-Contents_S20_Ar4.tif
Labels in Mitolysosome4-Contents_S20_Ar4.tif: [1 2]
Inferred full-res scale: 33x

Mitolysosome4-Contents_S20_Ar4:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Mitolysosome4-Contents_S20_Ar4_measurements.csv

Processing Mitolysosome5-Contents_S20_Ar4.tif
Labels in Mitolysosome5-Contents_S20_Ar4.tif: [1 2]
Inferred full-res scale: 33x

Mitolysosome5-Contents_S20_Ar4:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Mitolysosome5-Contents_S20_Ar4_measurements.csv

Processing Mitolysosome_S20_Ar4.tif
Labels in Mitolysosome_S20_Ar4.tif: [1 2 3 4 5]
Inferred full-res scale: 33x

Mitolysosome_S20_Ar4:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Mitolysosome_S20_Ar4_measurements.csv

Processing Mitophagophore1-Contents_S20_Ar4.tif
Labels in Mitophagophore1-Contents_S20_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitophagophore1-Contents_S20_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Mitophagophore1-Contents_S20_Ar4_measurements.csv

Processing Mitophagophore2-Contents_S20_Ar4.tif
Labels in Mitophagophore2-Contents_S20_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitophagophore2-Contents_S20_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Mitophagophore2-Contents_S20_Ar4_measurements.csv

Processing Mitophagophore3-Contents_S20_Ar4.tif
Labels in Mitophagophore3-Contents_S20_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitophagophore3-Contents_S20_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Mitophagophore3-Contents_S20_Ar4_measurements.csv

Processing Mitophagophore_S20_Ar4.tif
Labels in Mitophagophore_S20_Ar4.tif: [1 2 3]
Inferred full-res scale: 33x

Mitophagophore_S20_Ar4:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Mitophagophore_S20_Ar4_measurements.csv

Processing PL-Whorl_S20_Ar4.tif
Labels in PL-Whorl_S20_Ar4.tif: [1 2]
Inferred full-res scale: 33x

PL-Whorl_S20_Ar4:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\PL-Whorl_S20_Ar4_measurements.csv

Processing Rupture-UW_S20_Ar4.tif
Labels in Rupture-UW_S20_Ar4.tif: [1]
Inferred full-res scale: 33x

Rupture-UW_S20_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Rupture-UW_S20_Ar4_measurements.csv

Processing Rupture-W_S20_Ar4.tif
Labels in Rupture-W_S20_Ar4.tif: [1]
Inferred full-res scale: 33x

Rupture-W_S20_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\Rupture-W_S20_Ar4_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar4\S20_Ar4_label_measurements_mean_norm_strict_names.csv

=== Sample: S20_Ar5 ===
Using stack: 030625-DNp3e2c9-S20-ROI5.nrrd.tif
Using EM image: S20 Ar5 em aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (6854, 6854)
Detected binary cell mask in Cell_S20_Ar5.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S20_Ar5.tif

Whole-field mean normalization factors:
16O: 593.747986
12C21H: 950.027267
12C14N: 4043.646027
12C15N: 227.382156
29Si: 0.002960
31P: 2.007263
32S: 26.303055

QC Whole-field 15N:
Pixels: 65536
Mean:   0.051518
Median: 0.053272
Std:    0.014076

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S20_Ar5,030625-DNp3e2c9-S20-ROI5.nrrd.tif,S20 Ar5 em aligned.tif,65536,4271.028183,65536,0.051518,0.053272,0.014076,0.0,...,0.418202,65536,1.0,1.033709,0.253042,0.004214,1.831175,0.900252,1.143987,0.243735

S20_Ar5 label images:   0%|          | 0/13 [00:00<?, ?it/s]

Processing Cut-Through_S20_Ar5.tif
Labels in Cut-Through_S20_Ar5.tif: [1]
Inferred full-res scale: 27x

Cut-Through_S20_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\Cut-Through_S20_Ar5_measurements.csv

Processing Lysosome-NOS_S20_Ar5.tif
Labels in Lysosome-NOS_S20_Ar5.tif: [1]
Inferred full-res scale: 27x

Lysosome-NOS_S20_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\Lysosome-NOS_S20_Ar5_measurements.csv

Processing Mitochondria_S20_Ar5.tif
Labels in Mitochondria_S20_Ar5.tif: [4001 4002 4003 4005 4006 4007 4008 4011 4012 4013 4015 4016 4017 4019
 4020 4021 4022 4023 4024 4025 4026 4027 4031 4032 4033 4035 4038 4039
 4042 4043 4044 4045 4046 4048 4051 4052 4053 4054 4058 4059 4060 4066
 4069 4072 4077 4081 4082 4084 4085 4086 4088 4089 4090 4091 4092 4093
 4094 4096 4097 4099 4100 4101 4102 4103 4105 4115 4116 4118 4119 4121
 4122 4126 4129 4131 4132 4133 4137 4138 4139 4140 4141 4142 4143 4144
 4145 4146 4147 4148 4149 4150 4151 4152 4154 4155 4157 4159 4160 4162
 4164 4165 4166 4167 4168 4169 4174 4175 4178 4179 4180 4181 4183 4185
 4187 4189 4191 4192 4196 4202 4204 4208 4213 4223 4226 4229 4231 4240
 4242 4249 4254 4261 4266 4268 4272 4273 4274 4277 4278 4281 4284 4286
 4289 4290 4291 4292 4293 4294 4295 4296 4297 4298 4299 4300 4301 4302
 4303 4304 4305 4306 4307 4308 4309 4310 4311 4312 4313 4314]
Inferred full-res scale: 27x

Mitochondria_S20_Ar5:   0%|          | 0/166 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\Mitochondria_S20_Ar5_measurements.csv

Processing Mitolysosome1-Contents_S20_Ar5.tif
Labels in Mitolysosome1-Contents_S20_Ar5.tif: [1]
Inferred full-res scale: 27x

Mitolysosome1-Contents_S20_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\Mitolysosome1-Contents_S20_Ar5_measurements.csv

Processing Mitolysosome1-WMB_S20_Ar5.tif
Labels in Mitolysosome1-WMB_S20_Ar5.tif: [1]
Inferred full-res scale: 27x

Mitolysosome1-WMB_S20_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\Mitolysosome1-WMB_S20_Ar5_measurements.csv

Processing Mitolysosome2-Contents_S20_Ar5.tif
Labels in Mitolysosome2-Contents_S20_Ar5.tif: [1]
Inferred full-res scale: 27x

Mitolysosome2-Contents_S20_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\Mitolysosome2-Contents_S20_Ar5_measurements.csv

Processing Mitolysosome3-Contents_S20_Ar5.tif
Labels in Mitolysosome3-Contents_S20_Ar5.tif: [1 2 3]
Inferred full-res scale: 27x

Mitolysosome3-Contents_S20_Ar5:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\Mitolysosome3-Contents_S20_Ar5_measurements.csv

Processing Mitolysosome_S20_Ar5.tif
Labels in Mitolysosome_S20_Ar5.tif: [1 2 3]
Inferred full-res scale: 27x

Mitolysosome_S20_Ar5:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\Mitolysosome_S20_Ar5_measurements.csv

Processing Mitophagophore1-Contents_S20_Ar5.tif
Labels in Mitophagophore1-Contents_S20_Ar5.tif: [1]
Inferred full-res scale: 27x

Mitophagophore1-Contents_S20_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\Mitophagophore1-Contents_S20_Ar5_measurements.csv

Processing Mitophagophore2-Contents_S20_Ar5.tif
Labels in Mitophagophore2-Contents_S20_Ar5.tif: [1]
Inferred full-res scale: 27x

Mitophagophore2-Contents_S20_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\Mitophagophore2-Contents_S20_Ar5_measurements.csv

Processing Mitophagophore_S20_Ar5.tif
Labels in Mitophagophore_S20_Ar5.tif: [1 2]
Inferred full-res scale: 27x

Mitophagophore_S20_Ar5:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\Mitophagophore_S20_Ar5_measurements.csv

Processing PL-Whorl_S20_Ar5.tif
Labels in PL-Whorl_S20_Ar5.tif: [1 2 3]
Inferred full-res scale: 27x

PL-Whorl_S20_Ar5:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\PL-Whorl_S20_Ar5_measurements.csv

Processing Rupture-W_S20_Ar5.tif
Labels in Rupture-W_S20_Ar5.tif: [1]
Inferred full-res scale: 27x

Rupture-W_S20_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\Rupture-W_S20_Ar5_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S20_Ar5\S20_Ar5_label_measurements_mean_norm_strict_names.csv

=== Sample: S21_Ar1 ===
Using stack: 030825-DNp3e2c10-S21-ROI1.nrrd.tif
Using EM image: EM aligned to 14N.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar1
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (5139, 5139)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S21_Ar1.tif

Whole-field mean normalization factors:
16O: 852.329605
12C21H: 1441.657898
12C14N: 5368.158615
12C15N: 1796.549515
29Si: 0.006485
31P: 2.312256
32S: 30.045883

QC Whole-field 15N:
Pixels: 65536
Mean:   0.241952
Median: 0.260022
Std:    0.070390

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S21_Ar1,030825-DNp3e2c10-S21-ROI1.nrrd.tif,EM aligned to 14N.tif,65536,7164.70813,65536,0.241952,0.260022,0.07039,0.0,...,0.499236,65536,1.0,1.063267,0.304939,0.000558,1.508645,0.92673,1.176601,0.249871

S21_Ar1 label images:   0%|          | 0/3 [00:00<?, ?it/s]

Processing Mitochondria_S21_Ar1.tif
Labels in Mitochondria_S21_Ar1.tif: [201 210 211 212 213 218 221 222 223 224 232 236 240 245 248 249 250 253
 255 256 257 258 266 267 269 271 273 274 275 283 285 286 287 288 289 290
 291 297 301 303 304 306 307 311 312 315 316 318 322 325 326 333 339 340
 341 342 346 355 356 357 359 360 362 363 366 369 370 371 375 385 386 392
 398 400 401 402 404 413 417 418 421 426 435 444 445 449 453 454 455 456
 457 459 460 462 463 464 465 466 467 468 469 470 471 472]
Inferred full-res scale: 20x

Mitochondria_S21_Ar1:   0%|          | 0/104 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar1\Mitochondria_S21_Ar1_measurements.csv

Processing PL-Whorl_S21_Ar1.tif
Labels in PL-Whorl_S21_Ar1.tif: [1]
Inferred full-res scale: 20x

PL-Whorl_S21_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar1\PL-Whorl_S21_Ar1_measurements.csv

Processing Sarcomere_S21_Ar1.tif
Labels in Sarcomere_S21_Ar1.tif: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32]
Inferred full-res scale: 20x

Sarcomere_S21_Ar1:   0%|          | 0/32 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar1\Sarcomere_S21_Ar1_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar1\S21_Ar1_label_measurements_mean_norm_strict_names.csv

=== Sample: S21_Ar2 ===
Using stack: 030725-DNp3e2c10-S21-ROI2.nrrd.tif
Using EM image: S21_Ar2_EM aligned to 14N.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar2
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)
Detected binary cell mask in Cell_S21_Ar2.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S21_Ar2.tif

Whole-field mean normalization factors:
16O: 993.492889
12C21H: 1724.089325
12C14N: 5990.531372
12C15N: 2164.904495
29Si: 0.034576
31P: 2.900284
32S: 34.412140

QC Whole-field 15N:
Pixels: 65536
Mean:   0.247432
Median: 0.261083
Std:    0.087046

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S21_Ar2,030725-DNp3e2c10-S21-ROI2.nrrd.tif,S21_Ar2_EM aligned to 14N.tif,65536,8155.435867,65536,0.247432,0.261083,0.087046,0.0,...,0.552131,65536,1.0,1.110793,0.353902,0.000368,1.684521,0.981063,1.222743,0.241679

S21_Ar2 label images:   0%|          | 0/4 [00:00<?, ?it/s]

Processing Lysosome-NOS_S21_Ar2.tif
Labels in Lysosome-NOS_S21_Ar2.tif: [1 2 3]
Inferred full-res scale: 38x

Lysosome-NOS_S21_Ar2:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar2\Lysosome-NOS_S21_Ar2_measurements.csv

Processing Mitochondria_S21_Ar2.tif
Labels in Mitochondria_S21_Ar2.tif: [ 501  502  503  504  507  509  513  514  516  519  522  523  526  532
  534  536  538  541  542  553  554  556  557  559  568  570  574  579
  580  581  583  587  588  589  604  605  608  609  611  613  615  621
  629  634  635  651  657  659  663  664  668  671  674  677  686  689
  690  692  715  716  725  726  728  729  735  739  740  741  744  745
  747  748  749  750  751  752  753  754  755  757  760  761  771  783
  784  785  786  787  788  789  790  792  795  813  816  817  820  826
  828  830  834  835  841  844  846  849  853  854  856  857  864  868
  874  879  883  885  886  889  896  897  900  902  904  905  906  908
  909  912  919  922  923  924  928  934  935  937  938  940  941  942
  948  986  987  988  989  990  993  994  995  996  997  998  999 1000
 1002 1004 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020
 1021 1022]
Inferred full-res scale: 38x

Mitochondria_S21_Ar2:   0%|          | 0/170 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar2\Mitochondria_S21_Ar2_measurements.csv

Processing PL-Speckled_S21_Ar2.tif
Labels in PL-Speckled_S21_Ar2.tif: [3]
Inferred full-res scale: 38x

PL-Speckled_S21_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar2\PL-Speckled_S21_Ar2_measurements.csv

Processing Sarcomere_S21_Ar2.tif
Labels in Sarcomere_S21_Ar2.tif: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]
Inferred full-res scale: 38x

Sarcomere_S21_Ar2:   0%|          | 0/41 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar2\Sarcomere_S21_Ar2_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar2\S21_Ar2_label_measurements_mean_norm_strict_names.csv

=== Sample: S21_Ar3 ===
Using stack: 030725-DNp3e2c10-S21-ROI3.nrrd.tif
Using EM image: S21_Ar3_EM aligned to MIMS.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar3
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S21_Ar3.tif

Whole-field mean normalization factors:
16O: 211.413025
12C21H: 376.018066
12C14N: 2298.166183
12C15N: 595.135971
29Si: 0.001755
31P: 0.298691
32S: 6.565765

QC Whole-field 15N:
Pixels: 65536
Mean:   0.185776
Median: 0.169374
Std:    0.091464

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S21_Ar3,030725-DNp3e2c10-S21-ROI3.nrrd.tif,S21_Ar3_EM aligned to MIMS.tif,65536,2893.302155,65536,0.185776,0.169374,0.091464,0.0,...,0.761526,65536,1.0,1.148515,0.431806,0.012097,1.893338,0.888604,1.320636,0.432032

S21_Ar3 label images:   0%|          | 0/3 [00:00<?, ?it/s]

Processing Lysosome-NOS_S21_Ar3.tif
Labels in Lysosome-NOS_S21_Ar3.tif: [3 4]
Inferred full-res scale: 38x

Lysosome-NOS_S21_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar3\Lysosome-NOS_S21_Ar3_measurements.csv

Processing Mitochondria_S21_Ar3.tif
Labels in Mitochondria_S21_Ar3.tif: [1001 1002 1003 1004 1005 1006 1007 1008 1010 1012 1015 1017 1019 1021
 1022 1026 1028 1029 1032 1038 1041 1047 1048 1057 1063 1064 1066 1067
 1068 1069 1070 1074 1082 1087 1092 1097 1101 1102 1104 1108 1116 1119
 1122 1123 1124 1126 1129 1134 1135 1137 1138 1141 1145 1153 1154 1156
 1160 1161 1162 1171 1174 1176 1177 1186 1187 1190 1192 1193 1194 1209
 1211 1212 1219 1223 1225 1226 1227 1228 1233 1235 1242 1246 1247 1248
 1249]
Inferred full-res scale: 38x

Mitochondria_S21_Ar3:   0%|          | 0/85 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar3\Mitochondria_S21_Ar3_measurements.csv

Processing Sarcomere_S21_Ar3.tif
Labels in Sarcomere_S21_Ar3.tif: [1 2]
Inferred full-res scale: 38x

Sarcomere_S21_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar3\Sarcomere_S21_Ar3_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar3\S21_Ar3_label_measurements_mean_norm_strict_names.csv

=== Sample: S21_Ar4 ===
Using stack: 030725-DNp3e2c10-S21-ROI4.nrrd.tif
Using EM image: EM aligned to 14N.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar4
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)
Detected binary cell mask in Cell_S21_Ar4.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S21_Ar4.tif

Whole-field mean normalization factors:
16O: 238.841309
12C21H: 368.309906
12C14N: 2342.340027
12C15N: 696.346603
29Si: 0.000702
31P: 0.308014
32S: 7.528458

QC Whole-field 15N:
Pixels: 65536
Mean:   0.217085
Median: 0.218933
Std:    0.073742

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S21_Ar4,030725-DNp3e2c10-S21-ROI4.nrrd.tif,EM aligned to 14N.tif,65536,3038.68663,65536,0.217085,0.218933,0.073742,0.0,...,0.664147,65536,1.0,1.086325,0.35464,0.000987,1.999219,0.930994,1.257122,0.326128

S21_Ar4 label images:   0%|          | 0/2 [00:00<?, ?it/s]

Processing Mitochondria_S21_Ar4.tif
Labels in Mitochondria_S21_Ar4.tif: [1001 1008 1011 1013 1016 1022 1030 1031 1033 1034 1039 1041 1046 1051
 1053 1059 1060 1068 1070 1076 1078 1086 1087 1090 1094 1095 1096 1097
 1103 1106 1107 1111 1112 1114 1116 1120 1126 1142 1143 1144 1146 1157
 1159 1162 1163 1166 1167 1169 1172 1177 1182 1191 1194 1207 1209 1210
 1215 1216 1219 1222 1223 1226 1227 1229 1233 1234 1235 1236 1240 1242
 1247 1249 1250 1251 1253 1255 1261 1263 1265 1266 1268 1274 1280 1283
 1284 1287 1293 1294 1298 1300 1301 1304 1305 1306 1308 1309 1310 1312
 1313 1314 1323 1328 1329 1331 1336 1339 1340 1341 1342 1345 1348 1351
 1353 1354 1360 1363 1364 1365 1366 1372 1376 1377 1378 1379 1380 1381
 1382 1383 1384]
Inferred full-res scale: 38x

Mitochondria_S21_Ar4:   0%|          | 0/129 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar4\Mitochondria_S21_Ar4_measurements.csv

Processing Sarcomere_S21_Ar4.tif
Labels in Sarcomere_S21_Ar4.tif: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28]
Inferred full-res scale: 38x

Sarcomere_S21_Ar4:   0%|          | 0/28 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar4\Sarcomere_S21_Ar4_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar4\S21_Ar4_label_measurements_mean_norm_strict_names.csv

=== Sample: S21_Ar5 ===
Using stack: 030725-DNp3e2c10-S21-ROI5_1.nrrd.tif
Using EM image: EM aligned to 14N.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar5
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)
Detected binary cell mask in Cell_S21_Ar5.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S21_Ar5.tif

Whole-field mean normalization factors:
16O: 367.802002
12C21H: 535.300461
12C14N: 3164.808594
12C15N: 1067.151718
29Si: 0.003281
31P: 0.607925
32S: 14.906784

QC Whole-field 15N:
Pixels: 65536
Mean:   0.255882
Median: 0.268567
Std:    0.052602

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S21_Ar5,030725-DNp3e2c10-S21-ROI5_1.nrrd.tif,EM aligned to 14N.tif,65536,4231.960312,65536,0.255882,0.268567,0.052602,0.037162,...,0.402501,65536,1.0,1.000718,0.160826,0.032136,1.592879,0.915888,1.119339,0.203452

S21_Ar5 label images:   0%|          | 0/2 [00:00<?, ?it/s]

Processing Mitochondria_S21_Ar5.tif
Labels in Mitochondria_S21_Ar5.tif: [1003 1006 1014 1016 1018 1019 1022 1035 1037 1038 1040 1044 1048 1050
 1053 1054 1055 1056 1063 1064 1070 1072 1073 1074 1075 1076 1078 1080
 1081 1082 1084 1093 1094 1100 1101 1104 1105 1106 1107 1108 1109 1112
 1114 1115 1119 1120 1125 1130 1133 1134 1136 1137 1140 1146 1158 1159
 1160 1161 1162 1163 1164 1171 1173 1180 1186 1190 1199 1203 1204 1205
 1206 1214 1216 1218 1220 1221 1224 1226 1230 1233 1243 1244 1246 1248
 1249 1251 1252 1254 1255 1256 1264 1267 1273 1274 1280 1287 1288 1291
 1294 1295 1297 1298 1299 1301 1303 1305 1308 1309 1310 1311 1312 1313
 1316 1317 1323 1324 1325 1331 1333 1334 1335 1338 1339 1340 1343 1348
 1349 1350 1353 1354 1361 1363 1364 1370 1372 1373 1377 1381 1382 1383
 1387 1390 1393 1401 1404 1406 1409 1412 1414 1417 1418 1419 1420 1421
 1423 1426 1433 1434 1437 1438 1440 1443 1446 1447 1448 1459 1461 1462
 1467 1470 1472 1473 1474 1475 1476 1477 1478 1479 1480 1481]
Inferred full-res scale: 38x

Mitochondria_S21_Ar5:   0%|          | 0/180 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar5\Mitochondria_S21_Ar5_measurements.csv

Processing Sarcomere_S21_Ar5.tif
Labels in Sarcomere_S21_Ar5.tif: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Inferred full-res scale: 38x

Sarcomere_S21_Ar5:   0%|          | 0/24 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar5\Sarcomere_S21_Ar5_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S21_Ar5\S21_Ar5_label_measurements_mean_norm_strict_names.csv

=== Sample: S23_Ar1 ===
Using stack: test-S23-ROI1.nrrd.tif
Using EM image: S23_Ar1 EM non linear alignment to 14N 17um.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S23_Ar1.tif

Whole-field mean normalization factors:
16O: 511.625534
12C21H: 988.925049
12C14N: 2450.422714
12C15N: 2140.493729
29Si: 0.003128
31P: 1.719589
32S: 31.245255

QC Whole-field 15N:
Pixels: 65536
Mean:   0.454143
Median: 0.469309
Std:    0.099744

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S23_Ar1,test-S23-ROI1.nrrd.tif,S23_Ar1 EM non linear alignment to 14N 17um.tif,65536,4590.916443,65536,0.454143,0.469309,0.099744,0.034739,...,0.448068,65536,1.0,1.073206,0.28943,0.012198,1.907898,0.888004,1.185602,0.297599

S23_Ar1 label images:   0%|          | 0/32 [00:00<?, ?it/s]

Processing Mitochondria_S23_Ar1.tif
Labels in Mitochondria_S23_Ar1.tif: [1001 1003 1004 1005 1007 1008 1011 1013 1017 1018 1019 1020 1021 1023
 1024 1026 1028 1029 1031 1032 1033 1037 1046 1047 1048 1049 1050 1051
 1052 1054 1056 1057 1060 1062 1065 1072 1073 1079 1080 1082 1083 1087
 1088 1093 1094 1095 1103 1104 1106 1115 1121 1123 1133 1142 1147 1148
 1151 1154 1155 1158 1159 1161 1162 1173 1174 1177 1180 1181 1182 1183
 1185 1186 1199 1203 1211 1226 1227 1229 1230 1231 1232 1233 1234 1237
 1238 1239 1242 1244 1245 1253 1256 1259 1260 1263 1264 1272 1273 1279
 1285 1291 1294 1295 1298 1299 1300 1307 1308 1310 1313 1314 1317 1319
 1320 1322 1323 1325 1329 1330 1331 1332 1333 1334 1339 1348 1352 1355
 1360 1367 1372 1373 1374 1377 1378 1382 1383 1391 1392 1393 1395 1399
 1400 1403 1404 1406 1408 1409 1415 1418 1423 1430 1433 1438 1445 1449
 1452 1453 1454 1457 1458 1460 1462 1464 1466 1467 1472 1475 1476 1478
 1479 1480 1481 1482 1483 1484 1485 1488 1490 1499 1500 1502 1504 1505
 1518 1520 1521 1522 1523 1526 1529 1530 1531 1532 1533 1534 1535 1536
 1537 1538 1539 1540 1541 1542 1543 1544 1545 1546 1547 1548 1549 1550
 1551 1552 1553 1554]
Inferred full-res scale: 38x

Mitochondria_S23_Ar1:   0%|          | 0/214 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitochondria_S23_Ar1_measurements.csv

Processing Mitolysosome1-Contents_S23_Ar1.tif
Labels in Mitolysosome1-Contents_S23_Ar1.tif: [1 2 3 4 5 6 7]
Inferred full-res scale: 38x

Mitolysosome1-Contents_S23_Ar1:   0%|          | 0/7 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome1-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome10-Contents_S23_Ar1.tif
Labels in Mitolysosome10-Contents_S23_Ar1.tif: [1 2 3 4 5 6 7]
Inferred full-res scale: 38x

Mitolysosome10-Contents_S23_Ar1:   0%|          | 0/7 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome10-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome10-WMB_S23_Ar1.tif
Labels in Mitolysosome10-WMB_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome10-WMB_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome10-WMB_S23_Ar1_measurements.csv

Processing Mitolysosome11-Contents_S23_Ar1.tif
Labels in Mitolysosome11-Contents_S23_Ar1.tif: [ 1  2  3  4  5  6  7  8  9 10 11 12 13]
Inferred full-res scale: 38x

Mitolysosome11-Contents_S23_Ar1:   0%|          | 0/13 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome11-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome11-MLS_S23_Ar1.tif
Labels in Mitolysosome11-MLS_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome11-MLS_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome11-MLS_S23_Ar1_measurements.csv

Processing Mitolysosome12-Contents_S23_Ar1.tif
Labels in Mitolysosome12-Contents_S23_Ar1.tif: [1 2 3 4]
Inferred full-res scale: 38x

Mitolysosome12-Contents_S23_Ar1:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome12-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome13-Contents_S23_Ar1.tif
Labels in Mitolysosome13-Contents_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome13-Contents_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome13-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome14-Contents_S23_Ar1.tif
Labels in Mitolysosome14-Contents_S23_Ar1.tif: [1 2 3 4]
Inferred full-res scale: 38x

Mitolysosome14-Contents_S23_Ar1:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome14-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome2-Contents_S23_Ar1.tif
Labels in Mitolysosome2-Contents_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome2-Contents_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome2-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome2-WMB_S23_Ar1.tif
Labels in Mitolysosome2-WMB_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome2-WMB_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome2-WMB_S23_Ar1_measurements.csv

Processing Mitolysosome3-CM_S23_Ar1.tif
Labels in Mitolysosome3-CM_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome3-CM_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome3-CM_S23_Ar1_measurements.csv

Processing Mitolysosome3-Contents_S23_Ar1.tif
Labels in Mitolysosome3-Contents_S23_Ar1.tif: [1 2 3]
Inferred full-res scale: 38x

Mitolysosome3-Contents_S23_Ar1:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome3-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome4-CM_S23_Ar1.tif
Labels in Mitolysosome4-CM_S23_Ar1.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome4-CM_S23_Ar1:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome4-CM_S23_Ar1_measurements.csv

Processing Mitolysosome4-Contents_S23_Ar1.tif
Labels in Mitolysosome4-Contents_S23_Ar1.tif: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Inferred full-res scale: 38x

Mitolysosome4-Contents_S23_Ar1:   0%|          | 0/12 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome4-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome5-Contents_S23_Ar1.tif
Labels in Mitolysosome5-Contents_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome5-Contents_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome5-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome6-Contents_S23_Ar1.tif
Labels in Mitolysosome6-Contents_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome6-Contents_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome6-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome7-Contents_S23_Ar1.tif
Labels in Mitolysosome7-Contents_S23_Ar1.tif: [1 2 3 4]
Inferred full-res scale: 38x

Mitolysosome7-Contents_S23_Ar1:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome7-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome7-WMB_S23_Ar1.tif
Labels in Mitolysosome7-WMB_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome7-WMB_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome7-WMB_S23_Ar1_measurements.csv

Processing Mitolysosome8-Contents_S23_Ar1.tif
Labels in Mitolysosome8-Contents_S23_Ar1.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome8-Contents_S23_Ar1:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome8-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome8-WMB_S23_Ar1.tif
Labels in Mitolysosome8-WMB_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome8-WMB_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome8-WMB_S23_Ar1_measurements.csv

Processing Mitolysosome9-Contents_S23_Ar1.tif
Labels in Mitolysosome9-Contents_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitolysosome9-Contents_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome9-Contents_S23_Ar1_measurements.csv

Processing Mitolysosome_S23_Ar1.tif
Labels in Mitolysosome_S23_Ar1.tif: [ 1  2  3  4  5  6  7  9 10 11 12 13 18 19 20]
Inferred full-res scale: 38x

Mitolysosome_S23_Ar1:   0%|          | 0/15 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitolysosome_S23_Ar1_measurements.csv

Processing Mitophagophore1-Contents_S23_Ar1.tif
Labels in Mitophagophore1-Contents_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Mitophagophore1-Contents_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitophagophore1-Contents_S23_Ar1_measurements.csv

Processing Mitophagophore_S23_Ar1.tif
Labels in Mitophagophore_S23_Ar1.tif: [2 3]
Inferred full-res scale: 38x

Mitophagophore_S23_Ar1:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Mitophagophore_S23_Ar1_measurements.csv

Processing PL-Speckled_S23_Ar1.tif
Labels in PL-Speckled_S23_Ar1.tif: [1 3 4 5 6]
Inferred full-res scale: 38x

PL-Speckled_S23_Ar1:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\PL-Speckled_S23_Ar1_measurements.csv

Processing PL-Whorl_S23_Ar1.tif
Labels in PL-Whorl_S23_Ar1.tif: [2 3 4]
Inferred full-res scale: 38x

PL-Whorl_S23_Ar1:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\PL-Whorl_S23_Ar1_measurements.csv

Processing PW-Cluster-Contents_S23_Ar1.tif
Labels in PW-Cluster-Contents_S23_Ar1.tif: [1 2]
Inferred full-res scale: 38x

PW-Cluster-Contents_S23_Ar1:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\PW-Cluster-Contents_S23_Ar1_measurements.csv

Processing PW-Cluster_S23_Ar1.tif
Labels in PW-Cluster_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

PW-Cluster_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\PW-Cluster_S23_Ar1_measurements.csv

Processing Rupture-UW_S23_Ar1.tif
Labels in Rupture-UW_S23_Ar1.tif: [1]
Inferred full-res scale: 38x

Rupture-UW_S23_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Rupture-UW_S23_Ar1_measurements.csv

Processing Rupture-W_S23_Ar1.tif
Labels in Rupture-W_S23_Ar1.tif: [1 2]
Inferred full-res scale: 38x

Rupture-W_S23_Ar1:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Rupture-W_S23_Ar1_measurements.csv

Processing Sarcomere_S23_Ar1.tif
Labels in Sarcomere_S23_Ar1.tif: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28]
Inferred full-res scale: 38x

Sarcomere_S23_Ar1:   0%|          | 0/28 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\Sarcomere_S23_Ar1_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar1\S23_Ar1_label_measurements_mean_norm_strict_names.csv

=== Sample: S23_Ar2 ===
Using stack: 031225-DNp3e2c11-S23-ROI2.nrrd.tif
Using EM image: S23_Ar2_ EM aligned to 14N NS.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S23_Ar2.tif

Whole-field mean normalization factors:
16O: 774.096375
12C21H: 1433.037354
12C14N: 2638.771515
12C15N: 2416.404999
29Si: 0.007843
31P: 4.406723
32S: 51.809952

QC Whole-field 15N:
Pixels: 65536
Mean:   0.466047
Median: 0.481783
Std:    0.103198

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S23_Ar2,031225-DNp3e2c11-S23-ROI2.nrrd.tif,S23_Ar2_ EM aligned to 14N NS.tif,65536,5055.176514,65536,0.466047,0.481783,0.103198,0.0,...,0.405328,65536,1.0,1.057332,0.264028,0.00178,1.817147,0.922025,1.153471,0.231446

S23_Ar2 label images:   0%|          | 0/15 [00:00<?, ?it/s]

Processing Mitochondria_S23_Ar2.tif
Labels in Mitochondria_S23_Ar2.tif: [1001 1002 1006 1007 1011 1014 1016 1018 1024 1026 1027 1028 1029 1030
 1032 1033 1035 1036 1037 1038 1040 1041 1043 1044 1046 1051 1052 1055
 1065 1066 1067 1069 1071 1072 1073 1077 1082 1084 1088 1089 1094 1096
 1100 1102 1106 1110 1113 1117 1119 1120 1124 1126 1127 1130 1141 1143
 1150 1157 1160 1169 1172 1175 1180 1182 1197 1198 1199 1200 1201 1203
 1207 1209 1212 1215 1218 1223 1227 1236 1239 1241 1242 1243 1249 1252
 1259 1269 1276 1277 1278 1279 1281 1282 1284 1285 1286 1289 1293 1294
 1296 1299 1300 1301 1302 1303 1304 1313 1316 1325 1326 1333 1335 1337
 1339 1340 1341 1343 1344 1349 1351 1352 1353 1354 1355 1357 1358 1362
 1364 1365 1372 1374 1376 1378 1379 1381 1382 1383 1385 1386 1387 1388
 1389 1391 1401 1402 1406 1409 1414 1416 1419 1424 1437 1450 1454 1462
 1464 1468 1470 1475 1476 1478 1481 1483 1484 1485 1486 1487 1493 1494
 1495 1498 1500 1503 1505 1506 1507 1511 1515 1517 1519 1522 1528 1532
 1533 1535 1544 1545 1546 1547 1549 1555 1557 1559 1560 1562 1564 1565
 1566 1567 1577 1579 1581 1582 1583 1592 1593 1594 1595 1599 1604 1605
 1607 1609 1610 1611 1612 1613 1614 1615 1616 1617 1620 1621 1624 1629
 1634 1635 1636 1637 1638 1639 1640 1641 1642 1643 1644 1645 1646 1647
 1648 1649 1650 1651 1652 1653 1654 1655 1656 1657 1658 1659 1660 1661
 1662 1663 1664 1665 1666 1667 1668]
Inferred full-res scale: 38x

Mitochondria_S23_Ar2:   0%|          | 0/259 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitochondria_S23_Ar2_measurements.csv

Processing Mitolysosome1-Contents_S23_Ar2.tif
Labels in Mitolysosome1-Contents_S23_Ar2.tif: [1]
Inferred full-res scale: 38x

Mitolysosome1-Contents_S23_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitolysosome1-Contents_S23_Ar2_measurements.csv

Processing Mitolysosome1-WMB_S23_Ar2.tif
Labels in Mitolysosome1-WMB_S23_Ar2.tif: [1]
Inferred full-res scale: 38x

Mitolysosome1-WMB_S23_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitolysosome1-WMB_S23_Ar2_measurements.csv

Processing Mitolysosome2-Contents_S23_Ar2.tif
Labels in Mitolysosome2-Contents_S23_Ar2.tif: [1 3 4 5]
Inferred full-res scale: 38x

Mitolysosome2-Contents_S23_Ar2:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitolysosome2-Contents_S23_Ar2_measurements.csv

Processing Mitolysosome2-WMB_S23_Ar2.tif
Labels in Mitolysosome2-WMB_S23_Ar2.tif: [1]
Inferred full-res scale: 38x

Mitolysosome2-WMB_S23_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitolysosome2-WMB_S23_Ar2_measurements.csv

Processing Mitolysosome3-Contents_S23_Ar2.tif
Labels in Mitolysosome3-Contents_S23_Ar2.tif: [1 2 4 6 7]
Inferred full-res scale: 38x

Mitolysosome3-Contents_S23_Ar2:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitolysosome3-Contents_S23_Ar2_measurements.csv

Processing Mitolysosome3-WMB_S23_Ar2.tif
Labels in Mitolysosome3-WMB_S23_Ar2.tif: [1]
Inferred full-res scale: 38x

Mitolysosome3-WMB_S23_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitolysosome3-WMB_S23_Ar2_measurements.csv

Processing Mitolysosome4-Contents_S23_Ar2.tif
Labels in Mitolysosome4-Contents_S23_Ar2.tif: [1 2 3 4]
Inferred full-res scale: 38x

Mitolysosome4-Contents_S23_Ar2:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitolysosome4-Contents_S23_Ar2_measurements.csv

Processing Mitolysosome5-CM_S23_Ar2.tif
Labels in Mitolysosome5-CM_S23_Ar2.tif: [1 2 3]
Inferred full-res scale: 38x

Mitolysosome5-CM_S23_Ar2:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitolysosome5-CM_S23_Ar2_measurements.csv

Processing Mitolysosome5-Contents_S23_Ar2.tif
Labels in Mitolysosome5-Contents_S23_Ar2.tif: [1 2 3 4 6 7 8 9]
Inferred full-res scale: 38x

Mitolysosome5-Contents_S23_Ar2:   0%|          | 0/8 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitolysosome5-Contents_S23_Ar2_measurements.csv

Processing Mitolysosome6-Contents_S23_Ar2.tif
Labels in Mitolysosome6-Contents_S23_Ar2.tif: [1 2 3 5 6 7]
Inferred full-res scale: 38x

Mitolysosome6-Contents_S23_Ar2:   0%|          | 0/6 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitolysosome6-Contents_S23_Ar2_measurements.csv

Processing Mitolysosome_S23_Ar2.tif
Labels in Mitolysosome_S23_Ar2.tif: [ 1  2  5  6  8 11]
Inferred full-res scale: 38x

Mitolysosome_S23_Ar2:   0%|          | 0/6 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitolysosome_S23_Ar2_measurements.csv

Processing Mitoplast_S23_Ar2.tif
Labels in Mitoplast_S23_Ar2.tif: [1]
Inferred full-res scale: 38x

Mitoplast_S23_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Mitoplast_S23_Ar2_measurements.csv

Processing PL-Speckled_S23_Ar2.tif
Labels in PL-Speckled_S23_Ar2.tif: [1 2]
Inferred full-res scale: 38x

PL-Speckled_S23_Ar2:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\PL-Speckled_S23_Ar2_measurements.csv

Processing Sarcomere_S23_Ar2.tif
Labels in Sarcomere_S23_Ar2.tif: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
Inferred full-res scale: 38x

Sarcomere_S23_Ar2:   0%|          | 0/39 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\Sarcomere_S23_Ar2_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar2\S23_Ar2_label_measurements_mean_norm_strict_names.csv

=== Sample: S23_Ar3 ===
Using stack: 031125-DNp3e2c11-S23-ROI3.nrrd.tif
Using EM image: S23_ar3_EM aligned to 14N.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (4111, 4111)
Detected binary cell mask in Cell_S23_Ar3.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S23_Ar3.tif

Whole-field mean normalization factors:
16O: 1040.779861
12C21H: 1886.012131
12C14N: 3538.819305
12C15N: 3096.401520
29Si: 0.009979
31P: 7.142395
32S: 65.033218

QC Whole-field 15N:
Pixels: 65536
Mean:   0.462474
Median: 0.468608
Std:    0.076174

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S23_Ar3,031125-DNp3e2c11-S23-ROI3.nrrd.tif,S23_ar3_EM aligned to 14N.tif,65536,6635.220825,65536,0.462474,0.468608,0.076174,0.060452,...,0.384419,65536,1.0,1.050153,0.231201,0.009796,1.789842,0.946163,1.130332,0.184169

S23_Ar3 label images:   0%|          | 0/16 [00:00<?, ?it/s]

Processing Mitochondria_S23_Ar3.tif
Labels in Mitochondria_S23_Ar3.tif: [100001 100002 100003 100004 100005 100006 100008 100009 100010 100011
 100012 100013 100014 100015 100019 100021 100022 100025 100026 100027
 100028 100031 100032 100033 100034 100035 100036 100037 100038 100040
 100041 100042 100043 100044 100045 100046 100047 100048 100049 100050
 100051 100053 100054 100055 100056 100057 100058 100059 100060 100061
 100062 100063 100064 100065 100066 100067 100068 100070 100071 100072
 100073 100074 100075 100076 100077 100078 100079 100080 100081 100082
 100083 100084 100085 100086 100087 100088 100089 100090 100093 100094
 100095 100096 100097 100099 100100 100101 100103 100104 100105 100106
 100107 100108 100110 100111 100112 100113 100114 100115 100117 100118
 100119 100120 100121 100122 100123 100125 100126 100127 100128 100129
 100130 100132 100133 100134 100135 100136 100138 100139 100140 100142
 100143 100145 100146 100147 100148 100150 100152 100154 100155 100156
 100157 100158 100159 100160 100161 100162 100163 100164 100165 100166
 100167 100168 100169 100170 100171 100172 100173 100175 100176 100177
 100178 100179 100180 100181 100182 100183 100184 100185 100186 100187
 100188 100190 100191 100192 100193 100194 100195 100196 100197 100201
 100203 100204 100205 100207 100208 100210 100212 100213 100214 100215
 100216 100218 100219 100220 100221 100222 100223 100224 100225 100226
 100227 100228 100230 100232 100234 100235 100236 100239 100240 100241
 100242 100243 100245 100246 100247 100248 100249 100251 100264 100265
 100266 100267 100268 100269 100272 100274 100275 100276 100281 100283
 100284 100286 100287 100290 100291 100292 100294 100301 100303 100304
 100307 100308 100310 100311 100312 100313 100315 100316 100321 100322
 100323 100324 100326 100328 100329 100331 100332 100334 100335 100336
 100337 100343 100344 100345 100347 100349 100351 100352]
Inferred full-res scale: 16x

Mitochondria_S23_Ar3:   0%|          | 0/258 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Mitochondria_S23_Ar3_measurements.csv

Processing Mitolysosom3-Contents_S23_Ar3.tif
Labels in Mitolysosom3-Contents_S23_Ar3.tif: [1 2]
Inferred full-res scale: 16x

Mitolysosom3-Contents_S23_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Mitolysosom3-Contents_S23_Ar3_measurements.csv

Processing Mitolysosome1-Contents_S23_Ar3.tif
Labels in Mitolysosome1-Contents_S23_Ar3.tif: [1 2 3 4 5 6 7 8]
Inferred full-res scale: 16x

Mitolysosome1-Contents_S23_Ar3:   0%|          | 0/8 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Mitolysosome1-Contents_S23_Ar3_measurements.csv

Processing Mitolysosome1-WMB_S23_Ar3.tif
Labels in Mitolysosome1-WMB_S23_Ar3.tif: [1 2]
Inferred full-res scale: 16x

Mitolysosome1-WMB_S23_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Mitolysosome1-WMB_S23_Ar3_measurements.csv

Processing Mitolysosome2-Contents_S23_Ar3.tif
Labels in Mitolysosome2-Contents_S23_Ar3.tif: [1 2]
Inferred full-res scale: 16x

Mitolysosome2-Contents_S23_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Mitolysosome2-Contents_S23_Ar3_measurements.csv

Processing Mitolysosome4-Contents_S23_Ar3.tif
Labels in Mitolysosome4-Contents_S23_Ar3.tif: [1]
Inferred full-res scale: 16x

Mitolysosome4-Contents_S23_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Mitolysosome4-Contents_S23_Ar3_measurements.csv

Processing Mitolysosome5-Contents_S23_Ar3.tif
Labels in Mitolysosome5-Contents_S23_Ar3.tif: [1 2 3 4 5 6 7]
Inferred full-res scale: 16x

Mitolysosome5-Contents_S23_Ar3:   0%|          | 0/7 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Mitolysosome5-Contents_S23_Ar3_measurements.csv

Processing Mitolysosome5-MLS_S23_Ar3.tif
Labels in Mitolysosome5-MLS_S23_Ar3.tif: [1]
Inferred full-res scale: 16x

Mitolysosome5-MLS_S23_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Mitolysosome5-MLS_S23_Ar3_measurements.csv

Processing Mitolysosome6-Contents_S23_Ar3.tif
Labels in Mitolysosome6-Contents_S23_Ar3.tif: [1 3 4 5]
Inferred full-res scale: 16x

Mitolysosome6-Contents_S23_Ar3:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Mitolysosome6-Contents_S23_Ar3_measurements.csv

Processing Mitolysosome6-MLS_S23_Ar3.tif
Labels in Mitolysosome6-MLS_S23_Ar3.tif: [1 2]
Inferred full-res scale: 16x

Mitolysosome6-MLS_S23_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Mitolysosome6-MLS_S23_Ar3_measurements.csv

Processing Mitolysosome7-Contents_S23_Ar3.tif
Labels in Mitolysosome7-Contents_S23_Ar3.tif: [1 2 3 4]
Inferred full-res scale: 16x

Mitolysosome7-Contents_S23_Ar3:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Mitolysosome7-Contents_S23_Ar3_measurements.csv

Processing Mitolysosome_S23_Ar3.tif
Labels in Mitolysosome_S23_Ar3.tif: [2 3 4 5 7 8 9]
Inferred full-res scale: 16x

Mitolysosome_S23_Ar3:   0%|          | 0/7 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Mitolysosome_S23_Ar3_measurements.csv

Processing PL-Speckled_S23_Ar3.tif
Labels in PL-Speckled_S23_Ar3.tif: [1 2 3 4 5 6 7 8]
Inferred full-res scale: 16x

PL-Speckled_S23_Ar3:   0%|          | 0/8 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\PL-Speckled_S23_Ar3_measurements.csv

Processing PL-Whorl_S23_Ar3.tif
Labels in PL-Whorl_S23_Ar3.tif: [1 2]
Inferred full-res scale: 16x

PL-Whorl_S23_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\PL-Whorl_S23_Ar3_measurements.csv

Processing Sarcomere_S23_Ar3.tif
Labels in Sarcomere_S23_Ar3.tif: [ 5958 11915 17873 23831 29789 35746 41704 47662 53620 59577 65535]
Inferred full-res scale: 16x

Sarcomere_S23_Ar3:   0%|          | 0/11 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\Sarcomere_S23_Ar3_measurements.csv

Processing SL_S23_Ar3.tif
Labels in SL_S23_Ar3.tif: [1 2 3]
Inferred full-res scale: 16x

SL_S23_Ar3:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\SL_S23_Ar3_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar3\S23_Ar3_label_measurements_mean_norm_strict_names.csv

=== Sample: S23_Ar4 ===
Using stack: 031225-DNp3e2c11-S23-ROI4.nrrd.tif
Using EM image: S23_Ar4_ EM alone aligned to NS.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar4
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)
Detected binary cell mask in Cell_S23_Ar4.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S23_Ar4.tif

Whole-field mean normalization factors:
16O: 681.893219
12C21H: 1186.390625
12C14N: 1976.778992
12C15N: 1399.184723
29Si: 0.008118
31P: 3.180725
32S: 36.516495

QC Whole-field 15N:
Pixels: 65536
Mean:   0.354460
Median: 0.415606
Std:    0.156810

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S23_Ar4,031225-DNp3e2c11-S23-ROI4.nrrd.tif,S23_Ar4_ EM alone aligned to NS.tif,65536,3375.963715,65536,0.35446,0.415606,0.15681,0.0,...,1.068011,65536,1.0,1.179219,0.521122,0.00237,2.376803,0.62434,1.401081,0.776741

S23_Ar4 label images:   0%|          | 0/10 [00:00<?, ?it/s]

Processing Mitochondria_S23_Ar4.tif
Labels in Mitochondria_S23_Ar4.tif: [1002 1003 1006 1015 1017 1021 1023 1025 1030 1037 1040 1050 1051 1052
 1053 1054 1055 1056 1060 1068 1070 1071 1072 1074 1075 1076 1077 1079
 1080 1082 1083 1084 1086 1096 1099 1100 1105 1107 1108 1109 1110 1115
 1118 1120 1121 1124 1125 1126 1127 1128 1134 1135 1138 1139 1140 1144
 1145 1148 1149 1151 1152 1154 1155 1158 1165 1166 1167 1169 1170 1176
 1183 1188 1190 1191 1194 1195 1196 1201 1203 1207 1212 1213 1216 1217
 1218 1232 1233 1234 1235 1237 1240 1241 1243 1247 1250 1253 1256 1258
 1260 1261 1266 1268 1269 1271 1272 1273 1274 1276 1277 1278 1284 1288
 1291 1292 1295 1296 1304 1305 1308 1309 1310 1311 1312 1313 1314 1315
 1317 1318 1319 1320 1321 1322 1323 1324 1325 1326 1327 1328 1329 1330
 1331 1332 1333 1334 1335 1336 1337 1338 1339 1340 1341 1342 1344 1345
 1346 1347 1348 1349]
Inferred full-res scale: 38x

Mitochondria_S23_Ar4:   0%|          | 0/158 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar4\Mitochondria_S23_Ar4_measurements.csv

Processing Mitolysosome1-Contents_S23_Ar4.tif
Labels in Mitolysosome1-Contents_S23_Ar4.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome1-Contents_S23_Ar4:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar4\Mitolysosome1-Contents_S23_Ar4_measurements.csv

Processing Mitolysosome2-Contents_S23_Ar4.tif
Labels in Mitolysosome2-Contents_S23_Ar4.tif: [1 2 3]
Inferred full-res scale: 38x

Mitolysosome2-Contents_S23_Ar4:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar4\Mitolysosome2-Contents_S23_Ar4_measurements.csv

Processing Mitolysosome3-Contents_S23_Ar4.tif
Labels in Mitolysosome3-Contents_S23_Ar4.tif: [ 1  2  4  5  6  7  8  9 10]
Inferred full-res scale: 38x

Mitolysosome3-Contents_S23_Ar4:   0%|          | 0/9 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar4\Mitolysosome3-Contents_S23_Ar4_measurements.csv

Processing Mitolysosome3-MLS_S23_Ar4.tif
Labels in Mitolysosome3-MLS_S23_Ar4.tif: [1]
Inferred full-res scale: 38x

Mitolysosome3-MLS_S23_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar4\Mitolysosome3-MLS_S23_Ar4_measurements.csv

Processing Mitolysosome4-Contents_S23_Ar4.tif
Labels in Mitolysosome4-Contents_S23_Ar4.tif: [1 2 3 4 5]
Inferred full-res scale: 38x

Mitolysosome4-Contents_S23_Ar4:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar4\Mitolysosome4-Contents_S23_Ar4_measurements.csv

Processing Mitolysosome_S23_Ar4.tif
Labels in Mitolysosome_S23_Ar4.tif: [ 3  4  6 15]
Inferred full-res scale: 38x

Mitolysosome_S23_Ar4:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar4\Mitolysosome_S23_Ar4_measurements.csv

Processing Mitoplast_S23_Ar4.tif
Labels in Mitoplast_S23_Ar4.tif: [1]
Inferred full-res scale: 38x

Mitoplast_S23_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar4\Mitoplast_S23_Ar4_measurements.csv

Processing PL-Speckled_S23_Ar4.tif
Labels in PL-Speckled_S23_Ar4.tif: [2 3 4 5]
Inferred full-res scale: 38x

PL-Speckled_S23_Ar4:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar4\PL-Speckled_S23_Ar4_measurements.csv

Processing Sarcomere_S23_Ar4.tif
Labels in Sarcomere_S23_Ar4.tif: [1]
Inferred full-res scale: 38x

Sarcomere_S23_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar4\Sarcomere_S23_Ar4_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar4\S23_Ar4_label_measurements_mean_norm_strict_names.csv

=== Sample: S23_Ar7 ===
Using stack: 031225-DNp3e2c11-S23-ROI7.nrrd.tif
Using EM image: S23_Ar7 EM non linear aligned to 14N 17um better.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S23_Ar7.tif

Whole-field mean normalization factors:
16O: 956.822342
12C21H: 1651.519974
12C14N: 3371.528122
12C15N: 3006.041168
29Si: 0.005920
31P: 4.516617
32S: 53.187607

QC Whole-field 15N:
Pixels: 65536
Mean:   0.466726
Median: 0.474647
Std:    0.063958

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S23_Ar7,031225-DNp3e2c11-S23-ROI7.nrrd.tif,S23_Ar7 EM non linear aligned to 14N 17um bett...,65536,6377.56929,65536,0.466726,0.474647,0.063958,0.064865,...,0.376027,65536,1.0,1.042403,0.24667,0.027283,1.789083,0.908653,1.160473,0.25182

S23_Ar7 label images:   0%|          | 0/25 [00:00<?, ?it/s]

Processing Mitochondria_S23_Ar7.tif
Labels in Mitochondria_S23_Ar7.tif: [1001 1002 1006 1009 1014 1015 1016 1017 1018 1019 1022 1023 1024 1026
 1035 1036 1038 1042 1047 1050 1051 1052 1053 1054 1056 1061 1062 1066
 1068 1070 1071 1073 1075 1076 1077 1079 1082 1083 1086 1089 1095 1096
 1100 1110 1111 1113 1118 1119 1120 1121 1123 1125 1126 1132 1133 1134
 1147 1148 1154 1161 1163 1166 1168 1169 1172 1173 1176 1190 1195 1196
 1215 1220 1222 1225 1227 1235 1236 1240 1244 1250 1251 1253 1258 1259
 1261 1263 1266 1269 1270 1271 1272 1273 1274 1275 1279 1280 1281 1284
 1291 1298 1300 1307 1308 1311 1313 1314 1315 1316 1321 1323 1325 1331
 1342 1343 1345 1346 1353 1357 1360 1361 1363 1367 1369 1370 1378 1379
 1382 1384 1385 1386 1387 1389 1392 1405 1406 1407 1413 1416 1420 1423
 1426 1427 1429 1430 1434 1439 1441 1442 1445 1448 1451 1452 1456 1458
 1460 1461 1475 1482 1485 1486 1487 1488 1490 1493 1494 1495 1496 1497
 1498 1499 1503 1504 1505 1506 1511 1514 1515 1516 1518 1520 1521 1524
 1526 1527 1529 1531 1532 1533 1538 1541 1543 1545 1549 1551 1553 1558
 1559 1560 1562 1563 1566 1577 1579 1585 1586 1587 1588 1589 1595 1600
 1605 1614 1620 1624 1625 1626 1627 1629 1630 1631 1634 1635 1636 1637
 1639 1642 1649 1650 1651 1653 1656 1665 1666 1667 1668 1669 1674 1676
 1677 1679 1682 1684 1685 1687 1692 1695 1697 1699 1700 1702 1703 1704
 1707 1711 1713 1715 1716 1717 1718 1719 1720 1721 1722 1723 1724 1725
 1726 1727 1728 1729 1730 1731 1732 1733 1734 1735 1736 1737 1738 1739
 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 1751 1752 1753]
Inferred full-res scale: 38x

Mitochondria_S23_Ar7:   0%|          | 0/294 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitochondria_S23_Ar7_measurements.csv

Processing Mitolysosome1-Contents_S23_Ar7.tif
Labels in Mitolysosome1-Contents_S23_Ar7.tif: [1]
Inferred full-res scale: 38x

Mitolysosome1-Contents_S23_Ar7:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome1-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome10-Contents_S23_Ar7.tif
Labels in Mitolysosome10-Contents_S23_Ar7.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome10-Contents_S23_Ar7:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome10-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome11-Contents_S23_Ar7.tif
Labels in Mitolysosome11-Contents_S23_Ar7.tif: [1 2 3]
Inferred full-res scale: 38x

Mitolysosome11-Contents_S23_Ar7:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome11-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome11-WMB_S23_Ar7.tif
Labels in Mitolysosome11-WMB_S23_Ar7.tif: [1]
Inferred full-res scale: 38x

Mitolysosome11-WMB_S23_Ar7:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome11-WMB_S23_Ar7_measurements.csv

Processing Mitolysosome12-Contents_S23_Ar7.tif
Labels in Mitolysosome12-Contents_S23_Ar7.tif: [1 2 3]
Inferred full-res scale: 38x

Mitolysosome12-Contents_S23_Ar7:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome12-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome13-Contents_S23_Ar7.tif
Labels in Mitolysosome13-Contents_S23_Ar7.tif: [1 2 3]
Inferred full-res scale: 38x

Mitolysosome13-Contents_S23_Ar7:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome13-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome14-Contents_S23_Ar7.tif
Labels in Mitolysosome14-Contents_S23_Ar7.tif: [1 2 3]
Inferred full-res scale: 38x

Mitolysosome14-Contents_S23_Ar7:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome14-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome2-Contents_S23_Ar7.tif
Labels in Mitolysosome2-Contents_S23_Ar7.tif: [1]
Inferred full-res scale: 38x

Mitolysosome2-Contents_S23_Ar7:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome2-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome3-Contents_S23_Ar7.tif
Labels in Mitolysosome3-Contents_S23_Ar7.tif: [1 3]
Inferred full-res scale: 38x

Mitolysosome3-Contents_S23_Ar7:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome3-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome4-Contents_S23_Ar7.tif
Labels in Mitolysosome4-Contents_S23_Ar7.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome4-Contents_S23_Ar7:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome4-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome5-Contents_S23_Ar7.tif
Labels in Mitolysosome5-Contents_S23_Ar7.tif: [1 2 3 4 5 6]
Inferred full-res scale: 38x

Mitolysosome5-Contents_S23_Ar7:   0%|          | 0/6 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome5-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome6-Contents_S23_Ar7.tif
Labels in Mitolysosome6-Contents_S23_Ar7.tif: [1]
Inferred full-res scale: 38x

Mitolysosome6-Contents_S23_Ar7:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome6-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome7-Contents_S23_Ar7.tif
Labels in Mitolysosome7-Contents_S23_Ar7.tif: [1]
Inferred full-res scale: 38x

Mitolysosome7-Contents_S23_Ar7:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome7-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome7-WMB_S23_Ar7.tif
Labels in Mitolysosome7-WMB_S23_Ar7.tif: [1]
Inferred full-res scale: 38x

Mitolysosome7-WMB_S23_Ar7:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome7-WMB_S23_Ar7_measurements.csv

Processing Mitolysosome8-Contents_S23_Ar7.tif
Labels in Mitolysosome8-Contents_S23_Ar7.tif: [1]
Inferred full-res scale: 38x

Mitolysosome8-Contents_S23_Ar7:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome8-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome9-Contents_S23_Ar7.tif
Labels in Mitolysosome9-Contents_S23_Ar7.tif: [1 2 3]
Inferred full-res scale: 38x

Mitolysosome9-Contents_S23_Ar7:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome9-Contents_S23_Ar7_measurements.csv

Processing Mitolysosome_S23_Ar7.tif
Labels in Mitolysosome_S23_Ar7.tif: [ 1  2  3  5  7  9 10 11 13 14 15 16 17 18]
Inferred full-res scale: 38x

Mitolysosome_S23_Ar7:   0%|          | 0/14 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitolysosome_S23_Ar7_measurements.csv

Processing Mitophagophore1-Contents_S23_Ar7.tif
Labels in Mitophagophore1-Contents_S23_Ar7.tif: [1]
Inferred full-res scale: 38x

Mitophagophore1-Contents_S23_Ar7:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitophagophore1-Contents_S23_Ar7_measurements.csv

Processing Mitophagophore_S23_Ar7.tif
Labels in Mitophagophore_S23_Ar7.tif: [1]
Inferred full-res scale: 38x

Mitophagophore_S23_Ar7:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitophagophore_S23_Ar7_measurements.csv

Processing Mitoplast_S23_Ar7.tif
Labels in Mitoplast_S23_Ar7.tif: [1 2 3 4 5]
Inferred full-res scale: 38x

Mitoplast_S23_Ar7:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Mitoplast_S23_Ar7_measurements.csv

Processing PL-Speckled_S23_Ar7.tif
Labels in PL-Speckled_S23_Ar7.tif: [1 2]
Inferred full-res scale: 38x

PL-Speckled_S23_Ar7:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\PL-Speckled_S23_Ar7_measurements.csv

Processing PL-Whorl_S23_Ar7.tif
Labels in PL-Whorl_S23_Ar7.tif: [1 2 5]
Inferred full-res scale: 38x

PL-Whorl_S23_Ar7:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\PL-Whorl_S23_Ar7_measurements.csv

Processing Sarcomere_S23_Ar7.tif
Labels in Sarcomere_S23_Ar7.tif: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Inferred full-res scale: 38x

Sarcomere_S23_Ar7:   0%|          | 0/15 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\Sarcomere_S23_Ar7_measurements.csv

Processing SL_S23_Ar7.tif
Labels in SL_S23_Ar7.tif: [1 2]
Inferred full-res scale: 38x

SL_S23_Ar7:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\SL_S23_Ar7_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S23_Ar7\S23_Ar7_label_measurements_mean_norm_strict_names.csv

=== Sample: S24_Ar1 ===
Using stack: 031025-DNp3e2c12-S24-ROI1.nrrd.tif
Using EM image: S24 Ar1 EM aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar1
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9138, 9138)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S24_Ar1.tif

Whole-field mean normalization factors:
16O: 432.712753
12C21H: 929.506943
12C14N: 3416.122101
12C15N: 558.626831
29Si: 0.008606
31P: 1.206116
32S: 20.216171

QC Whole-field 15N:
Pixels: 65536
Mean:   0.136871
Median: 0.143567
Std:    0.034118

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S24_Ar1,031025-DNp3e2c12-S24-ROI1.nrrd.tif,S24 Ar1 EM aligned.tif,65536,3974.748932,65536,0.136871,0.143567,0.034118,0.0,...,0.544119,65536,1.0,1.072269,0.302212,0.00478,3.828166,0.886848,1.198315,0.311466

S24_Ar1 label images:   0%|          | 0/10 [00:00<?, ?it/s]

Processing Lysosome-NOS_S24_Ar1.tif
Labels in Lysosome-NOS_S24_Ar1.tif: [1 2 3]
Inferred full-res scale: 36x

Lysosome-NOS_S24_Ar1:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar1\Lysosome-NOS_S24_Ar1_measurements.csv

Processing Mitochondria_S24_Ar1.tif
Labels in Mitochondria_S24_Ar1.tif: [4001 4002 4003 4004 4005 4006 4007 4008 4010 4014 4017 4018 4021 4022
 4023 4027 4028 4030 4034 4036 4037 4038 4039 4040 4041 4043 4046 4047
 4048 4050 4051 4052 4056 4057 4058 4059 4062 4063 4065 4067 4068 4070
 4078 4079 4080 4081 4090 4094 4095 4096 4097 4102 4103 4104 4105 4106
 4107 4110 4122 4123 4124 4125 4127 4132 4133 4136 4138 4139 4142 4144
 4146 4147 4153 4154 4155 4157 4158 4159 4160 4162 4166 4167 4169 4172
 4175 4177 4182 4184 4186 4191 4196 4201 4202 4203 4206 4211 4212 4213
 4217 4218 4223 4224 4225 4226 4227 4228 4230 4250 4251 4252 4253 4254
 4255 4256 4257 4258 4264 4265 4266 4267 4273 4274 4279 4280 4281 4282
 4283 4284 4285 4287 4288 4289 4290 4291 4292 4293 4294 4295 4296 4297
 4298 4299 4300 4301 4302 4303 4304 4305 4306]
Inferred full-res scale: 36x

Mitochondria_S24_Ar1:   0%|          | 0/149 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar1\Mitochondria_S24_Ar1_measurements.csv

Processing Mitolysosome1-Contents_S24_Ar1.tif
Labels in Mitolysosome1-Contents_S24_Ar1.tif: [1]
Inferred full-res scale: 36x

Mitolysosome1-Contents_S24_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar1\Mitolysosome1-Contents_S24_Ar1_measurements.csv

Processing Mitolysosome2-Contents_S24_Ar1.tif
Labels in Mitolysosome2-Contents_S24_Ar1.tif: [1]
Inferred full-res scale: 36x

Mitolysosome2-Contents_S24_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar1\Mitolysosome2-Contents_S24_Ar1_measurements.csv

Processing Mitolysosome3-Contents_S24_Ar1.tif
Labels in Mitolysosome3-Contents_S24_Ar1.tif: [1]
Inferred full-res scale: 36x

Mitolysosome3-Contents_S24_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar1\Mitolysosome3-Contents_S24_Ar1_measurements.csv

Processing Mitolysosome_S24_Ar1.tif
Labels in Mitolysosome_S24_Ar1.tif: [1 2 4]
Inferred full-res scale: 36x

Mitolysosome_S24_Ar1:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar1\Mitolysosome_S24_Ar1_measurements.csv

Processing PL-Speckled_S24_Ar1.tif
Labels in PL-Speckled_S24_Ar1.tif: [1 2]
Inferred full-res scale: 36x

PL-Speckled_S24_Ar1:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar1\PL-Speckled_S24_Ar1_measurements.csv

Processing Rupture-UW_S24_Ar1.tif
Labels in Rupture-UW_S24_Ar1.tif: [1]
Inferred full-res scale: 36x

Rupture-UW_S24_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar1\Rupture-UW_S24_Ar1_measurements.csv

Processing Rupture-W_S24_Ar1.tif
Labels in Rupture-W_S24_Ar1.tif: [1]
Inferred full-res scale: 36x

Rupture-W_S24_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar1\Rupture-W_S24_Ar1_measurements.csv

Processing SL_S24_Ar1.tif
Labels in SL_S24_Ar1.tif: [1]
Inferred full-res scale: 36x

SL_S24_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar1\SL_S24_Ar1_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar1\S24_Ar1_label_measurements_mean_norm_strict_names.csv

=== Sample: S24_Ar2 ===
Using stack: 031025-DNp3e2c12-S24-ROI2.nrrd.tif
Using EM image: S24 Ar2 EM aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar2
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (8567, 8567)
Detected binary cell mask in Cell_S24_Ar2.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S24_Ar2.tif

Whole-field mean normalization factors:
16O: 242.857468
12C21H: 479.244049
12C14N: 1708.510117
12C15N: 314.499481
29Si: 0.003464
31P: 0.309708
32S: 9.580124

QC Whole-field 15N:
Pixels: 65536
Mean:   0.153546
Median: 0.158052
Std:    0.028479

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S24_Ar2,031025-DNp3e2c12-S24-ROI2.nrrd.tif,S24 Ar2 EM aligned.tif,65536,2023.009598,65536,0.153546,0.158052,0.028479,0.0,...,0.521914,65536,1.0,1.042506,0.244214,0.014335,1.871469,0.913985,1.146806,0.232821

S24_Ar2 label images:   0%|          | 0/8 [00:00<?, ?it/s]

Processing Mitochondria_S24_Ar2.tif
Labels in Mitochondria_S24_Ar2.tif: [4001 4002 4003 4005 4007 4008 4011 4014 4017 4019 4020 4021 4022 4024
 4027 4028 4029 4030 4036 4037 4045 4046 4050 4051 4052 4055 4057 4058
 4059 4060 4061 4063 4065 4068 4069 4070 4071 4072 4075 4079 4083 4084
 4085 4086 4088 4090 4093 4095 4098 4105 4108 4109 4113 4122 4126 4127
 4129 4131 4132 4133 4134 4135 4144 4150 4155 4158 4159 4170 4171 4173
 4177 4178 4179 4185 4186 4187 4192 4196 4200 4201 4202 4203 4205 4215
 4216 4218 4220 4222 4223 4224 4232 4234 4236 4237 4238 4240 4241 4242
 4243 4244 4245 4249 4252 4256 4257 4259 4260 4261 4262 4263 4264 4265
 4266 4267 4268 4269 4270 4271 4273 4274 4275 4276 4278 4279 4280 4281
 4286 4287 4289 4298 4299 4308 4309 4310 4313 4315 4320 4321 4322 4327
 4328 4330 4331 4332 4333 4336 4337 4343 4346 4347 4349 4352 4353 4354
 4358 4362 4364 4366 4368 4369 4371 4372 4376 4383 4384 4385 4396 4407
 4412 4413 4422 4425 4427 4428 4431 4433 4437 4438 4443 4452 4454 4458
 4459 4460 4461 4462 4463 4464]
Inferred full-res scale: 33x

Mitochondria_S24_Ar2:   0%|          | 0/188 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar2\Mitochondria_S24_Ar2_measurements.csv

Processing Mitophagophore1-Contents_S24_Ar2.tif
Labels in Mitophagophore1-Contents_S24_Ar2.tif: [1]
Inferred full-res scale: 33x

Mitophagophore1-Contents_S24_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar2\Mitophagophore1-Contents_S24_Ar2_measurements.csv

Processing Mitophagophore_S24_Ar2.tif
Labels in Mitophagophore_S24_Ar2.tif: [1]
Inferred full-res scale: 33x

Mitophagophore_S24_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar2\Mitophagophore_S24_Ar2_measurements.csv

Processing Mitoplast_S24_Ar2.tif
Labels in Mitoplast_S24_Ar2.tif: [1 2 3 4]
Inferred full-res scale: 33x

Mitoplast_S24_Ar2:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar2\Mitoplast_S24_Ar2_measurements.csv

Processing NOS-Lysosome_S24_Ar2.tif
Labels in NOS-Lysosome_S24_Ar2.tif: [1 2 3]
Inferred full-res scale: 33x

NOS-Lysosome_S24_Ar2:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar2\NOS-Lysosome_S24_Ar2_measurements.csv

Processing PL-Speckled_S24_Ar2.tif
Labels in PL-Speckled_S24_Ar2.tif: [1]
Inferred full-res scale: 33x

PL-Speckled_S24_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar2\PL-Speckled_S24_Ar2_measurements.csv

Processing PL-Whorl_S24_Ar2.tif
Labels in PL-Whorl_S24_Ar2.tif: [1]
Inferred full-res scale: 33x

PL-Whorl_S24_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar2\PL-Whorl_S24_Ar2_measurements.csv

Processing Rupture-UW_S24_Ar2.tif
Labels in Rupture-UW_S24_Ar2.tif: [1 2]
Inferred full-res scale: 33x

Rupture-UW_S24_Ar2:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar2\Rupture-UW_S24_Ar2_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar2\S24_Ar2_label_measurements_mean_norm_strict_names.csv

=== Sample: S24_Ar3 ===
Using stack: 031025-DNp3e2c12-S24-ROI3-concatenate.nrrd.tif
Using EM image: S24 Ar3 EM aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar3
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (6854, 6854)
Detected binary cell mask in Cell_S24_Ar3.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S24_Ar3.tif

Whole-field mean normalization factors:
16O: 609.192444
12C21H: 957.367081
12C14N: 3284.204529
12C15N: 561.920364
29Si: 0.007309
31P: 1.917038
32S: 27.270721

QC Whole-field 15N:
Pixels: 65536
Mean:   0.143412
Median: 0.151230
Std:    0.029808

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S24_Ar3,031025-DNp3e2c12-S24-ROI3-concatenate.nrrd.tif,S24 Ar3 EM aligned.tif,65536,3846.124893,65536,0.143412,0.15123,0.029808,0.019417,...,0.513371,65536,1.0,1.028308,0.247386,0.04732,2.067276,0.856706,1.172349,0.315642

S24_Ar3 label images:   0%|          | 0/6 [00:00<?, ?it/s]

Processing Mitochondria_S24_Ar3.tif
Labels in Mitochondria_S24_Ar3.tif: [4001 4002 4003 4004 4006 4007 4008 4009 4010 4011 4012 4021 4024 4030
 4032 4033 4034 4037 4038 4039 4040 4044 4045 4046 4048 4054 4057 4058
 4060 4067 4068 4069 4075 4078 4079 4081 4083 4084 4085 4086 4087 4089
 4097 4098 4101 4102 4104 4105 4106 4107 4108 4109 4111 4112 4113 4118
 4120 4123 4124 4125 4127 4129 4130 4131 4132 4133 4134 4135 4136 4140
 4143 4145 4146 4147 4152 4153 4154 4156 4157 4165 4167 4168 4169 4171
 4172 4174 4175 4177 4179 4180 4182 4193 4197 4198 4202 4205 4208 4209
 4210 4214 4220 4222 4223 4224 4226 4230 4231 4232 4233 4234 4238 4243
 4249 4250 4256 4258 4259 4264 4265 4267 4277 4279 4285 4287 4288 4292
 4297 4298 4304 4307 4310 4328 4329 4330 4331 4332 4336 4337 4340 4342
 4344 4346 4350 4353 4354 4358 4359 4360 4362 4364 4366 4367 4368 4369
 4370 4379 4382 4383 4384 4385 4387 4391 4392 4393 4394 4395 4396 4397
 4398 4399 4400 4401 4402 4403 4404 4405 4406 4407]
Inferred full-res scale: 27x

Mitochondria_S24_Ar3:   0%|          | 0/178 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar3\Mitochondria_S24_Ar3_measurements.csv

Processing Mitolysosome1-Contents_S24_Ar3.tif
Labels in Mitolysosome1-Contents_S24_Ar3.tif: [1 2 3]
Inferred full-res scale: 27x

Mitolysosome1-Contents_S24_Ar3:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar3\Mitolysosome1-Contents_S24_Ar3_measurements.csv

Processing Mitolysosome2-Contents_S24_Ar3.tif
Labels in Mitolysosome2-Contents_S24_Ar3.tif: [1 2 3 4]
Inferred full-res scale: 27x

Mitolysosome2-Contents_S24_Ar3:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar3\Mitolysosome2-Contents_S24_Ar3_measurements.csv

Processing Mitolysosome_S24_Ar3.tif
Labels in Mitolysosome_S24_Ar3.tif: [1 2]
Inferred full-res scale: 27x

Mitolysosome_S24_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar3\Mitolysosome_S24_Ar3_measurements.csv

Processing PL-Speckled_S24_Ar3.tif
Labels in PL-Speckled_S24_Ar3.tif: [1 2]
Inferred full-res scale: 27x

PL-Speckled_S24_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar3\PL-Speckled_S24_Ar3_measurements.csv

Processing SL_S24_Ar3.tif
Labels in SL_S24_Ar3.tif: [1 2 3]
Inferred full-res scale: 27x

SL_S24_Ar3:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar3\SL_S24_Ar3_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar3\S24_Ar3_label_measurements_mean_norm_strict_names.csv

=== Sample: S24_Ar4 ===
Using stack: 031125-DNp3e2c12-S24-ROI4.nrrd.tif
Using EM image: S24 Ar4 EM aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar4
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (8567, 8567)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S24_Ar4.tif

Whole-field mean normalization factors:
16O: 451.295563
12C21H: 1242.731445
12C14N: 2471.579758
12C15N: 474.547180
29Si: 0.016357
31P: 1.918137
32S: 28.841507

QC Whole-field 15N:
Pixels: 65536
Mean:   0.149487
Median: 0.162305
Std:    0.042305

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S24_Ar4,031125-DNp3e2c12-S24-ROI4.nrrd.tif,S24 Ar4 EM aligned.tif,65536,2946.126938,65536,0.149487,0.162305,0.042305,0.0,...,0.450739,65536,1.0,1.098391,0.351813,0.001697,1.712078,0.87912,1.251134,0.372014

S24_Ar4 label images:   0%|          | 0/2 [00:00<?, ?it/s]

Processing Mitochondria_S24_Ar4.tif
Labels in Mitochondria_S24_Ar4.tif: [4001 4002 4006 4007 4013 4022 4023 4031 4034 4035 4036 4038 4043 4045
 4046 4047 4048 4049 4050 4052 4053 4054 4059 4060 4061 4063 4064 4065
 4066 4068 4069 4070 4072 4076 4077 4078 4079 4082 4083 4084 4089 4092
 4093 4094 4095 4096 4099 4101 4102 4106 4108 4113 4116 4117 4118 4120
 4122 4127 4128 4129 4132 4133 4134 4135 4136 4139 4140 4142 4145 4147
 4148 4149 4155 4158 4159 4160 4161 4162 4163 4164 4170 4173 4174 4176
 4179 4181 4183 4186 4188 4189 4192 4197 4199 4203 4204 4208 4209 4211
 4213 4214 4215 4225 4228 4230 4232 4235 4239 4243 4246 4247 4249 4257
 4258 4259 4260 4261 4262 4263 4264 4265 4266 4267 4268 4269 4270 4271
 4272 4273 4274 4275 4276 4277]
Inferred full-res scale: 33x

Mitochondria_S24_Ar4:   0%|          | 0/132 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar4\Mitochondria_S24_Ar4_measurements.csv

Processing PL-Whorl_S24_Ar4.tif
Labels in PL-Whorl_S24_Ar4.tif: [1]
Inferred full-res scale: 33x

PL-Whorl_S24_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar4\PL-Whorl_S24_Ar4_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar4\S24_Ar4_label_measurements_mean_norm_strict_names.csv

=== Sample: S24_Ar6 ===
Using stack: 031125-DNp3e2c12-S24-ROI6.nrrd.tif
Using EM image: S24 Ar6 EM aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar6
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (8567, 8567)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S24_Ar6.tif

Whole-field mean normalization factors:
16O: 264.689041
12C21H: 500.598358
12C14N: 1695.438553
12C15N: 359.007172
29Si: 0.003128
31P: 0.835083
32S: 15.151428

QC Whole-field 15N:
Pixels: 65536
Mean:   0.164164
Median: 0.176093
Std:    0.047912

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S24_Ar6,031125-DNp3e2c12-S24-ROI6.nrrd.tif,S24 Ar6 EM aligned.tif,65536,2054.445724,65536,0.164164,0.176093,0.047912,0.0,...,0.726004,65536,1.0,1.111735,0.408808,0.00146,2.093022,0.752028,1.307895,0.555868

S24_Ar6 label images:   0%|          | 0/5 [00:00<?, ?it/s]

Processing Mitochondria_S24_Ar6.tif
Labels in Mitochondria_S24_Ar6.tif: [4001 4002 4003 4004 4005 4006 4007 4008 4010 4011 4012 4014 4020 4024
 4033 4035 4036 4037 4038 4039 4040 4041 4043 4044 4047 4050 4053 4056
 4057 4058 4059 4062 4065 4066 4069 4070 4071 4072 4073 4076 4077 4080
 4082 4084 4086 4087 4088 4090 4091 4093 4094 4095 4096 4097 4098 4099
 4100 4101 4102 4104 4105 4106 4107 4108 4109 4115 4116 4117 4118 4121
 4122 4123 4124 4125 4126 4127 4128 4129 4130 4131 4133 4135 4136 4137
 4138 4139 4140 4144 4146 4148 4149 4152 4153 4154 4155 4156 4157 4161
 4162 4164 4165 4168 4169 4170 4171 4172 4173 4174 4176 4177 4178 4179
 4180 4181 4182 4183 4184 4185 4186 4187 4188 4189 4190 4191]
Inferred full-res scale: 33x

Mitochondria_S24_Ar6:   0%|          | 0/124 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar6\Mitochondria_S24_Ar6_measurements.csv

Processing Mitolysosome1-Contents_S24_Ar6.tif
Labels in Mitolysosome1-Contents_S24_Ar6.tif: [1]
Inferred full-res scale: 33x

Mitolysosome1-Contents_S24_Ar6:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar6\Mitolysosome1-Contents_S24_Ar6_measurements.csv

Processing Mitolysosome1-WMB_S24_Ar6.tif
Labels in Mitolysosome1-WMB_S24_Ar6.tif: [1 2]
Inferred full-res scale: 33x

Mitolysosome1-WMB_S24_Ar6:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar6\Mitolysosome1-WMB_S24_Ar6_measurements.csv

Processing Mitolysosome_S24_Ar6.tif
Labels in Mitolysosome_S24_Ar6.tif: [1]
Inferred full-res scale: 33x

Mitolysosome_S24_Ar6:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar6\Mitolysosome_S24_Ar6_measurements.csv

Processing PL-Speckled_S24_Ar6.tif
Labels in PL-Speckled_S24_Ar6.tif: [1]
Inferred full-res scale: 33x

PL-Speckled_S24_Ar6:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar6\PL-Speckled_S24_Ar6_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S24_Ar6\S24_Ar6_label_measurements_mean_norm_strict_names.csv

=== Sample: S25_Ar1 ===
Using stack: 032125-DNp3e2c13-S25-ROI1.nrrd.tif
Using EM image: S25Ar1 em aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar1
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (8567, 8567)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S25_Ar1.tif

Whole-field mean normalization factors:
16O: 539.328598
12C21H: 774.037842
12C14N: 2856.969254
12C15N: 817.196899
29Si: 0.004547
31P: 2.456757
32S: 21.487137

QC Whole-field 15N:
Pixels: 65536
Mean:   0.211854
Median: 0.222330
Std:    0.052004

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S25_Ar1,032125-DNp3e2c13-S25-ROI1.nrrd.tif,S25Ar1 em aligned.tif,65536,3674.166153,65536,0.211854,0.22233,0.052004,0.0,...,0.651553,65536,1.0,1.048401,0.378526,0.002722,2.134634,0.779224,1.252801,0.473577

S25_Ar1 label images:   0%|          | 0/6 [00:00<?, ?it/s]

Processing Mitochondria_S25_Ar1.tif
Labels in Mitochondria_S25_Ar1.tif: [4001 4002 4003 4004 4005 4006 4007 4008 4009 4011 4017 4018 4020 4021
 4023 4024 4025 4026 4027 4029 4031 4033 4036 4037 4038 4039 4040 4041
 4046 4049 4050 4052 4055 4056 4057 4058 4059 4060 4062 4065 4066 4070
 4071 4072 4073 4074 4075 4076 4077 4078 4079 4080 4081 4082 4084 4085
 4086 4088 4089 4091 4092 4093 4094 4095 4097 4098 4099 4100 4101 4102
 4103 4104 4105 4106 4107 4108 4111 4113 4114 4115 4116 4119 4120 4121
 4122 4124 4125 4128 4129 4134 4138 4139 4140 4141 4142 4146 4147 4148
 4151 4152 4154 4155 4156 4157 4159 4160 4163 4164 4165 4166 4167 4168
 4169 4173 4175 4176 4178 4179 4180 4182 4185 4186 4187 4188 4191 4192
 4195 4197 4198 4199 4200 4207 4208 4212 4213 4214 4215 4216 4217 4219
 4220 4221 4222 4225 4227 4228 4229 4230 4232 4234 4236 4238 4239 4242
 4243 4244 4245 4246 4248 4251 4252 4253 4254 4256 4257 4259 4262 4263
 4264 4265 4266 4267 4269 4270 4272 4274 4277 4284 4287 4288 4289 4294
 4295 4296 4297 4298 4299 4302 4303 4304 4307 4313 4314 4315 4317 4318
 4319 4320 4321 4322 4323 4324 4325 4327 4329 4330 4332 4333 4334 4339
 4341 4343 4346 4347 4348 4351 4352 4353 4356 4357 4358 4359 4360 4361
 4362 4363 4364 4365 4366 4367 4368 4369 4370 4371 4372 4373 4374 4375
 4376 4377 4378 4379]
Inferred full-res scale: 33x

Mitochondria_S25_Ar1:   0%|          | 0/242 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar1\Mitochondria_S25_Ar1_measurements.csv

Processing Mitoplast_S25_Ar1.tif
Labels in Mitoplast_S25_Ar1.tif: [1]
Inferred full-res scale: 33x

Mitoplast_S25_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar1\Mitoplast_S25_Ar1_measurements.csv

Processing PL-Speckled_S25_Ar1.tif
Labels in PL-Speckled_S25_Ar1.tif: [1]
Inferred full-res scale: 33x

PL-Speckled_S25_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar1\PL-Speckled_S25_Ar1_measurements.csv

Processing PL-Whorl_S25_Ar1.tif
Labels in PL-Whorl_S25_Ar1.tif: [1]
Inferred full-res scale: 33x

PL-Whorl_S25_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar1\PL-Whorl_S25_Ar1_measurements.csv

Processing Rupture-UW_S25_Ar1.tif
Labels in Rupture-UW_S25_Ar1.tif: [1]
Inferred full-res scale: 33x

Rupture-UW_S25_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar1\Rupture-UW_S25_Ar1_measurements.csv

Processing Rupture-W_S25_Ar1.tif
Labels in Rupture-W_S25_Ar1.tif: [1 2 3]
Inferred full-res scale: 33x

Rupture-W_S25_Ar1:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar1\Rupture-W_S25_Ar1_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar1\S25_Ar1_label_measurements_mean_norm_strict_names.csv

=== Sample: S25_Ar2 ===
Using stack: 032625-DNp3e2c13-S25-ROI2_1.nrrd.tif
Using EM image: S25Ar2 em aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar2
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S25_Ar2.tif

Whole-field mean normalization factors:
16O: 279.091858
12C21H: 468.739120
12C14N: 1738.655792
12C15N: 545.868408
29Si: 0.002090
31P: 0.580154
32S: 10.979324

QC Whole-field 15N:
Pixels: 65536
Mean:   0.234926
Median: 0.243629
Std:    0.047529

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S25_Ar2,032625-DNp3e2c13-S25-ROI2_1.nrrd.tif,S25Ar2 em aligned.tif,65536,2284.5242,65536,0.234926,0.243629,0.047529,0.003788,...,0.546482,65536,1.0,1.030849,0.194981,0.028015,1.637102,0.924044,1.118395,0.194351

S25_Ar2 label images:   0%|          | 0/10 [00:00<?, ?it/s]

Processing Mitochondria_S25_Ar2.tif
Labels in Mitochondria_S25_Ar2.tif: [4001 4003 4004 4005 4006 4009 4012 4015 4025 4026 4027 4028 4030 4033
 4036 4037 4038 4041 4058 4059 4060 4065 4066 4071 4075 4076 4077 4084
 4089 4090 4092 4093 4095 4096 4097 4098 4100 4101 4102 4103 4104 4107
 4108 4109 4110 4112 4114 4116 4117 4118 4119 4120 4121 4122 4123 4127
 4129 4130 4131 4135 4136 4137 4139 4142 4144 4148 4151 4156 4164 4165
 4166 4167 4168 4170 4172 4173 4175 4176 4178 4179 4180 4181 4184 4185
 4187 4188 4191 4192 4193 4194 4195 4197 4198 4199 4200 4201 4202 4207
 4210 4211 4212 4215 4220 4224 4229 4230 4231 4232 4233 4235 4237 4241
 4242 4244 4246 4247 4248 4249 4251 4252 4253 4254 4255 4257 4258 4259
 4260 4264 4265 4267 4271 4272 4273 4274 4276 4277 4279 4280 4281 4282
 4283 4287 4289 4294 4296 4298 4301 4303 4304 4307 4308 4310 4312 4316
 4317 4318 4320 4327 4330 4333 4334 4336 4337 4339 4343 4348 4351 4353
 4354 4356 4359 4360 4363 4364 4365 4366 4367 4368 4369 4370 4372 4373
 4375 4377 4379 4386 4387 4388 4389 4390 4391 4392 4393 4394 4396 4404
 4406 4407 4408 4409 4410 4411 4412 4413 4414 4415 4416 4417 4418 4419
 4420 4421 4422 4423 4424 4425 4426 4427 4428 4429 4430 4431 4432 4433
 4434 4435 4436 4437 4438 4439 4440 4441]
Inferred full-res scale: 38x

Mitochondria_S25_Ar2:   0%|          | 0/232 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar2\Mitochondria_S25_Ar2_measurements.csv

Processing Mitolysosome1-Contents_S25_Ar2.tif
Labels in Mitolysosome1-Contents_S25_Ar2.tif: [1]
Inferred full-res scale: 38x

Mitolysosome1-Contents_S25_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar2\Mitolysosome1-Contents_S25_Ar2_measurements.csv

Processing Mitolysosome2-Contents_S25_Ar2.tif
Labels in Mitolysosome2-Contents_S25_Ar2.tif: [1 2 3]
Inferred full-res scale: 38x

Mitolysosome2-Contents_S25_Ar2:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar2\Mitolysosome2-Contents_S25_Ar2_measurements.csv

Processing Mitolysosome3-Contents_S25_Ar2.tif
Labels in Mitolysosome3-Contents_S25_Ar2.tif: [1]
Inferred full-res scale: 38x

Mitolysosome3-Contents_S25_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar2\Mitolysosome3-Contents_S25_Ar2_measurements.csv

Processing Mitolysosome4-Contents_S25_Ar2.tif
Labels in Mitolysosome4-Contents_S25_Ar2.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome4-Contents_S25_Ar2:   0%|          | 0/2 [00:00<?, ?it/s]

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar2\Mitolysosome4-Contents_S25_Ar2_measurements.csv

Processing Mitolysosome5-Contents_S25_Ar2.tif
Labels in Mitolysosome5-Contents_S25_Ar2.tif: [ 1  2  3  4  5  6  7  8  9 10]
Inferred full-res scale: 38x

Mitolysosome5-Contents_S25_Ar2:   0%|          | 0/10 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar2\Mitolysosome5-Contents_S25_Ar2_measurements.csv

Processing Mitolysosome5-WMB_S25_Ar2.tif
Labels in Mitolysosome5-WMB_S25_Ar2.tif: [1 2]
Inferred full-res scale: 38x

Mitolysosome5-WMB_S25_Ar2:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar2\Mitolysosome5-WMB_S25_Ar2_measurements.csv

Processing Mitolysosome_S25_Ar2.tif
Labels in Mitolysosome_S25_Ar2.tif: [1 2 3 4 5]
Inferred full-res scale: 38x

Mitolysosome_S25_Ar2:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar2\Mitolysosome_S25_Ar2_measurements.csv

Processing PL-Speckled_S25_Ar2.tif
Labels in PL-Speckled_S25_Ar2.tif: [1]
Inferred full-res scale: 38x

PL-Speckled_S25_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar2\PL-Speckled_S25_Ar2_measurements.csv

Processing Rupture-UW_S25_Ar2.tif
Labels in Rupture-UW_S25_Ar2.tif: [1]
Inferred full-res scale: 38x

Rupture-UW_S25_Ar2:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar2\Rupture-UW_S25_Ar2_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar2\S25_Ar2_label_measurements_mean_norm_strict_names.csv

=== Sample: S25_Ar3 ===
Using stack: 032625-DNp3e2c13-S25-ROI3.nrrd.tif
Using EM image: S25Ar3 em aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S25_Ar3.tif

Whole-field mean normalization factors:
16O: 313.015976
12C21H: 414.665039
12C14N: 1672.663422
12C15N: 464.555618
29Si: 0.001892
31P: 0.872253
32S: 10.975342

QC Whole-field 15N:
Pixels: 65536
Mean:   0.210208
Median: 0.221875
Std:    0.049533

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S25_Ar3,032625-DNp3e2c13-S25-ROI3.nrrd.tif,S25Ar3 em aligned.tif,65536,2137.21904,65536,0.210208,0.221875,0.049533,0.0,...,0.54668,65536,1.0,1.037797,0.247945,0.016844,1.810764,0.920355,1.153368,0.233013

S25_Ar3 label images:   0%|          | 0/11 [00:00<?, ?it/s]

Processing CutThroughMito_S25_Ar3.tif
Labels in CutThroughMito_S25_Ar3.tif: [1]
Inferred full-res scale: 38x

CutThroughMito_S25_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3\CutThroughMito_S25_Ar3_measurements.csv

Processing Mitochondria_S25_Ar3.tif
Labels in Mitochondria_S25_Ar3.tif: [4001 4002 4003 4004 4005 4006 4007 4009 4010 4011 4012 4014 4015 4017
 4018 4019 4022 4024 4025 4029 4030 4031 4032 4033 4034 4035 4036 4038
 4043 4044 4054 4055 4056 4057 4059 4064 4065 4067 4070 4071 4072 4074
 4079 4084 4085 4086 4089 4091 4093 4094 4096 4097 4104 4107 4114 4117
 4118 4120 4121 4123 4127 4134 4135 4136 4139 4141 4143 4151 4160 4164
 4167 4168 4172 4173 4174 4176 4177 4178 4179 4186 4188 4190 4193 4194
 4195 4196 4197 4206 4209 4210 4211 4214 4216 4217 4218 4219 4224 4225
 4227 4228 4229 4230 4232 4235 4239 4244 4245 4246 4249 4250 4251 4255
 4257 4258 4259 4261 4262 4265 4267 4269 4270 4273 4276 4277 4279 4280
 4281 4287 4291 4295 4296 4301 4306 4307 4308 4309 4310 4314 4316 4318
 4320 4321 4328 4329 4333 4334 4338 4342 4343 4348 4358 4359 4360 4365
 4368 4369 4371 4372 4379 4380 4382 4384 4387 4391 4398 4401 4403 4406
 4407 4409 4410 4412 4413 4414 4416 4417 4418 4419 4421 4422 4427 4429
 4431 4432 4433 4434 4435 4437 4440 4441 4442 4443 4444 4445 4446 4447
 4449 4451 4453 4454 4456 4458 4459 4460 4461 4462 4463 4464 4465 4466
 4467 4470 4473 4477 4482 4487 4488 4489 4490 4494 4496 4497 4499 4500
 4501 4502 4503 4505 4506 4508 4509 4512 4513 4514 4517 4518 4519 4520
 4521 4522 4523 4525 4529 4530 4534 4535 4538 4540 4541 4542 4543 4544
 4545 4546 4547 4548 4549 4550 4551 4552 4553 4554 4555 4556 4557 4558
 4559 4560 4561 4562 4563 4564 4565 4566 4567 4568 4569 4570 4571 4572
 4573 4574 4575 4576 4577 4578 4579 4580 4581 4582 4583 4584 4585 4586]
Inferred full-res scale: 38x

Mitochondria_S25_Ar3:   0%|          | 0/294 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3\Mitochondria_S25_Ar3_measurements.csv

Processing Mitolysosome1-Contents_S25_Ar3.tif
Labels in Mitolysosome1-Contents_S25_Ar3.tif: [1 2 3 4 5 6 7]
Inferred full-res scale: 38x

Mitolysosome1-Contents_S25_Ar3:   0%|          | 0/7 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3\Mitolysosome1-Contents_S25_Ar3_measurements.csv

Processing Mitolysosome2-Contents_S25_Ar3.tif
Labels in Mitolysosome2-Contents_S25_Ar3.tif: [1]
Inferred full-res scale: 38x

Mitolysosome2-Contents_S25_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3\Mitolysosome2-Contents_S25_Ar3_measurements.csv

Processing Mitolysosome3-Contents_S25_Ar3.tif
Labels in Mitolysosome3-Contents_S25_Ar3.tif: [1]
Inferred full-res scale: 38x

Mitolysosome3-Contents_S25_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3\Mitolysosome3-Contents_S25_Ar3_measurements.csv

Processing Mitolysosome4-Contents_S25_Ar3.tif
Labels in Mitolysosome4-Contents_S25_Ar3.tif: [1]
Inferred full-res scale: 38x

Mitolysosome4-Contents_S25_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3\Mitolysosome4-Contents_S25_Ar3_measurements.csv

Processing Mitolysosome4-WMB_S25_Ar3.tif
Labels in Mitolysosome4-WMB_S25_Ar3.tif: [1]
Inferred full-res scale: 38x

Mitolysosome4-WMB_S25_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3\Mitolysosome4-WMB_S25_Ar3_measurements.csv

Processing Mitolysosome5-Contents_S25_Ar3.tif
Labels in Mitolysosome5-Contents_S25_Ar3.tif: [1]
Inferred full-res scale: 38x

Mitolysosome5-Contents_S25_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3\Mitolysosome5-Contents_S25_Ar3_measurements.csv

Processing Mitolysosome_S25_Ar3.tif
Labels in Mitolysosome_S25_Ar3.tif: [1 2 3 4 5]
Inferred full-res scale: 38x

Mitolysosome_S25_Ar3:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3\Mitolysosome_S25_Ar3_measurements.csv

Processing Mitoplast_S25_Ar3.tif
Labels in Mitoplast_S25_Ar3.tif: [1 2 3]
Inferred full-res scale: 38x

Mitoplast_S25_Ar3:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3\Mitoplast_S25_Ar3_measurements.csv

Processing Rupture-W_S25_Ar3.tif
Labels in Rupture-W_S25_Ar3.tif: [1 2]
Inferred full-res scale: 38x

Rupture-W_S25_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3\Rupture-W_S25_Ar3_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S25_Ar3\S25_Ar3_label_measurements_mean_norm_strict_names.csv

=== Sample: S26_Ar1 ===
Using stack: 031425-DNp3e2c1-S26-ROI1.nrrd.tif
Using EM image: S26_Ar1 EM non linear aligned to 14N.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar1
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S26_Ar1.tif

Whole-field mean normalization factors:
16O: 479.271790
12C21H: 919.596603
12C14N: 2907.208267
12C15N: 839.717346
29Si: 0.008377
31P: 1.121094
32S: 14.126953

QC Whole-field 15N:
Pixels: 65536
Mean:   0.222186
Median: 0.225754
Std:    0.072065

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S26_Ar1,031425-DNp3e2c1-S26-ROI1.nrrd.tif,S26_Ar1 EM non linear aligned to 14N.tif,65536,3746.925613,65536,0.222186,0.225754,0.072065,0.0,...,0.991013,65536,1.0,1.009094,0.404894,0.005871,1.798808,0.759823,1.335228,0.575405

S26_Ar1 label images:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Mitochondria_S26_Ar1.tif
Labels in Mitochondria_S26_Ar1.tif: [4001 4002 4003 4004 4005 4006 4007 4009 4011 4014 4015 4016 4018 4020
 4021 4022 4023 4024 4027 4032 4034 4035 4038 4041 4042 4044 4045 4052
 4055 4058 4061 4062 4064 4066 4067 4069 4071 4073 4076 4080 4084 4085
 4086 4087 4089 4091 4092 4094 4095 4099 4102 4103 4106 4107 4111 4112
 4113 4115 4116 4122 4127 4128 4129 4130 4131 4133 4135 4136 4140 4147
 4148 4151 4153 4155 4156 4157 4159 4162 4164 4165 4167 4170 4171 4172
 4174 4175 4176 4177 4179 4180 4181 4182 4183 4184 4185 4186 4189 4191
 4193 4194 4195 4196 4197 4198 4199 4200 4201 4202 4203 4204 4206 4207
 4209 4210 4211 4213 4214 4215 4217 4218 4219 4222 4223 4224 4225 4226
 4227 4235 4236 4239 4241 4242 4243 4244 4245 4246 4248 4249 4252 4254
 4257 4258 4259 4261 4262 4263 4264 4265 4267 4268 4269 4271 4272 4273
 4275 4277 4278 4280 4281 4282 4283 4284 4285 4286 4287 4288 4289 4291
 4294 4295 4296 4300 4302 4305 4306 4307 4313 4314 4317 4318 4319]
Inferred full-res scale: 38x

Mitochondria_S26_Ar1:   0%|          | 0/181 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar1\Mitochondria_S26_Ar1_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar1\S26_Ar1_label_measurements_mean_norm_strict_names.csv

=== Sample: S26_Ar2 ===
Using stack: 031425-DNp3e2c1-S26-ROI2.nrrd.tif
Using EM image: S26_Ar2 EM non linear aligned to 14N.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar2
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)
Detected binary cell mask in Cell_S26_Ar2.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S26_Ar2.tif

Whole-field mean normalization factors:
16O: 603.277710
12C21H: 1119.544342
12C14N: 2637.898697
12C15N: 645.699356
29Si: 0.006287
31P: 1.073380
32S: 13.067795

QC Whole-field 15N:
Pixels: 65536
Mean:   0.157750
Median: 0.163007
Std:    0.103208

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S26_Ar2,031425-DNp3e2c1-S26-ROI2.nrrd.tif,S26_Ar2 EM non linear aligned to 14N.tif,65536,3283.598053,65536,0.15775,0.163007,0.103208,0.0,...,1.453956,65536,1.0,1.09849,0.658815,0.007005,2.380316,0.172676,1.608601,1.435925

S26_Ar2 label images:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Mitochondria_S26_Ar2.tif
Labels in Mitochondria_S26_Ar2.tif: [4001 4002 4003 4004 4005 4006 4008 4009 4010 4018 4019 4021 4025 4026
 4027 4028 4030 4031 4032 4033 4034 4035 4036 4037 4038 4040 4041 4042
 4043 4046 4047 4048 4049 4050 4051 4052 4055 4057 4058 4060 4063 4064
 4066 4068 4069 4070 4077 4083 4086 4089 4090 4099 4109 4110 4114 4116
 4117 4123 4129 4130 4131 4133 4140 4143 4144 4148 4151 4152 4154 4157
 4158 4160 4165 4166 4170 4171 4172 4174 4177 4185 4186 4189 4192 4193
 4196 4198 4199 4200 4205 4211 4212 4214 4215 4218 4223 4227 4228 4230
 4232 4234 4237 4243 4245 4249 4250 4254 4255 4257 4259 4264 4267]
Inferred full-res scale: 38x

Mitochondria_S26_Ar2:   0%|          | 0/111 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar2\Mitochondria_S26_Ar2_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar2\S26_Ar2_label_measurements_mean_norm_strict_names.csv

=== Sample: S26_Ar3 ===
Using stack: 031425-DNp3e2c1-S26-ROI3.nrrd.tif
Using EM image: S26_Ar3 EM non linear aligned to NIMS.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar3
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)
Detected binary cell mask in Cell_S26_Ar3.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S26_Ar3.tif

Whole-field mean normalization factors:
16O: 632.488403
12C21H: 1285.678848
12C14N: 2731.023392
12C15N: 636.318588
29Si: 0.004700
31P: 2.185211
32S: 16.539154

QC Whole-field 15N:
Pixels: 65536
Mean:   0.185348
Median: 0.182850
Std:    0.068025

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S26_Ar3,031425-DNp3e2c1-S26-ROI3.nrrd.tif,S26_Ar3 EM non linear aligned to NIMS.tif,65536,3367.34198,65536,0.185348,0.18285,0.068025,0.0,...,1.027864,65536,1.0,0.989801,0.474922,0.002673,2.555725,0.664619,1.372596,0.707977

S26_Ar3 label images:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Mitochondria_S26_Ar3.tif
Labels in Mitochondria_S26_Ar3.tif: [4001 4002 4003 4004 4005 4006 4007 4008 4009 4010 4011 4012 4013 4014
 4015 4017 4018 4019 4020 4021 4024 4025 4026 4027 4028 4029 4030 4031
 4032 4033 4034 4035 4037 4039 4040 4041 4047 4048 4051 4052 4053 4054
 4060 4062 4064 4065 4067 4069 4072 4073 4074 4076 4077 4078 4079 4081
 4082 4085 4086 4089 4090 4091 4092 4094 4095 4096 4098 4099 4100 4102
 4105 4106 4107 4108 4110 4111 4112 4113 4114 4115 4116 4117 4118 4119
 4120 4121 4122 4123 4124 4125 4126 4127 4128 4129 4130 4131 4134 4135
 4136 4138 4139 4140 4141 4143 4144 4145 4146 4147 4149 4150 4151 4152
 4154 4155 4157 4158 4160 4161 4162 4163 4164 4169 4170 4171 4174 4175
 4177 4178 4179 4180 4182 4184 4185 4187 4188 4189 4192 4193 4194 4196
 4197 4198 4199 4201 4202 4204 4207 4210 4211 4212]
Inferred full-res scale: 38x

Mitochondria_S26_Ar3:   0%|          | 0/150 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar3\Mitochondria_S26_Ar3_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar3\S26_Ar3_label_measurements_mean_norm_strict_names.csv

=== Sample: S26_Ar4 ===
Using stack: 031725-DNp3e2c1-S26-ROI4.nrrd.tif
Using EM image: S26_Ar4 EM non linear aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar4
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)
Detected binary cell mask in Cell_S26_Ar4.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S26_Ar4.tif

Whole-field mean normalization factors:
16O: 418.567535
12C21H: 804.079208
12C14N: 1838.076752
12C15N: 441.379944
29Si: 0.003387
31P: 1.077133
32S: 10.007462

QC Whole-field 15N:
Pixels: 65536
Mean:   0.192902
Median: 0.178046
Std:    0.063680

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S26_Ar4,031725-DNp3e2c1-S26-ROI4.nrrd.tif,S26_Ar4 EM non linear aligned.tif,65536,2279.456696,65536,0.192902,0.178046,0.06368,0.00625,...,1.09918,65536,1.0,0.989271,0.438656,0.007458,2.129894,0.673406,1.396385,0.722979

S26_Ar4 label images:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Mitochondria_S26_Ar4.tif
Labels in Mitochondria_S26_Ar4.tif: [4001 4002 4003 4004 4005 4006 4007 4008 4009 4010 4011 4012 4013 4018
 4019 4022 4023 4028 4031 4032 4034 4036 4037 4038 4039 4040 4041 4042
 4045 4047 4048 4049 4052 4053 4054 4056 4057 4061 4062 4066 4070 4071
 4074 4075 4076 4077 4079 4081 4082 4083 4084 4087 4088 4089 4090 4091
 4092 4093 4095 4097 4098 4099 4100 4101 4102 4105 4106 4109 4110 4111
 4112 4115 4116 4119 4120 4122 4123 4128 4131 4134 4135 4136 4137 4138
 4139 4140 4141 4143 4144 4145 4146 4148 4149 4151 4152 4154 4155 4159
 4164 4165 4166 4167]
Inferred full-res scale: 38x

Mitochondria_S26_Ar4:   0%|          | 0/102 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar4\Mitochondria_S26_Ar4_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar4\S26_Ar4_label_measurements_mean_norm_strict_names.csv

=== Sample: S26_Ar5 ===
Using stack: 031725-DNp3e2c1-S26-ROI5.nrrd.tif
Using EM image: S26_Ar5 EM non linear aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar5
Stack shape: (7, 256, 256)
Number of original channels: 7
EM shape: (9709, 9709)
Detected binary cell mask in Cell_S26_Ar5.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S26_Ar5.tif

Whole-field mean normalization factors:
16O: 477.205856
12C21H: 829.004593
12C14N: 2290.127472
12C15N: 630.578171
29Si: 0.005859
31P: 1.544022
32S: 14.368240

QC Whole-field 15N:
Pixels: 65536
Mean:   0.203423
Median: 0.214537
Std:    0.083394

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S26_Ar5,031725-DNp3e2c1-S26-ROI5.nrrd.tif,S26_Ar5 EM non linear aligned.tif,65536,2920.705643,65536,0.203423,0.214537,0.083394,0.0,...,1.043969,65536,1.0,1.042899,0.447741,0.007875,1.903992,0.768992,1.385282,0.616289

S26_Ar5 label images:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Mitochondria_S26_Ar5.tif
Labels in Mitochondria_S26_Ar5.tif: [4001 4002 4003 4004 4005 4006 4007 4008 4012 4013 4015 4016 4017 4018
 4019 4020 4023 4024 4025 4026 4027 4028 4030 4031 4037 4042 4043 4047
 4048 4051 4054 4055 4056 4058 4061 4063 4064 4067 4068 4071 4077 4080
 4081 4082 4083 4090 4092 4094 4097 4099 4100 4104 4105 4108 4110 4111
 4112 4113 4114 4115 4116 4117 4119 4121 4122 4124 4125 4127 4131 4135
 4138 4139 4140 4142 4143 4144 4150 4151 4155 4156 4161 4162 4163 4168
 4170 4171 4172 4176 4180 4183 4184 4186 4190 4192 4195 4197 4199 4202
 4203 4205 4206 4210 4213 4214 4215 4221 4229 4236 4242 4244 4245 4246
 4251 4254 4256 4257 4259 4261 4262 4264 4265 4269 4270 4271 4272 4273
 4277 4278 4279 4281 4285 4286 4287 4288 4291 4293 4295 4300 4305 4307
 4309 4313 4315 4322 4332 4333 4336 4338 4342 4343 4351 4352 4353 4356
 4357 4360 4364 4369 4372 4374 4377 4378 4382 4383 4384 4387 4390 4393
 4394 4395 4396 4397 4398 4400 4401 4402 4403 4405 4406 4407 4409 4414
 4421 4422 4425 4427 4429 4432 4433 4434 4435 4436 4438 4439 4443 4444]
Inferred full-res scale: 38x

Mitochondria_S26_Ar5:   0%|          | 0/196 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar5\Mitochondria_S26_Ar5_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S26_Ar5\S26_Ar5_label_measurements_mean_norm_strict_names.csv

=== Sample: S2_Ar1 ===
Using stack: 051024-DN-p3e1c5-sample2-Ar1.nrrd.tif
Using EM image: S2Ar1 thin EM aligned to MIMS.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1
Stack shape: (6, 256, 256)
Number of original channels: 6
EM shape: (7425, 7425)
Detected binary cell mask in Cell_S2_Ar1.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S2_Ar1.tif
Detected 6-channel TIFF; assuming '29Si' is the missing channel.

Whole-field mean normalization factors:
16O: 342.883972
12C21H: 1523.028183
12C14N: 2561.755310
12C15N: 1996.577866
31P: 7.172928
32S: 30.364517

QC Whole-field 15N:
Pixels: 65536
Mean:   0.429929
Median: 0.452328
Std:    0.106437

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S2_Ar1,051024-DN-p3e1c5-sample2-Ar1.nrrd.tif,S2Ar1 thin EM aligned to MIMS.tif,65536,4558.333176,65536,0.429929,0.452328,0.106437,0.014941,...,0.428131,65536,1.0,1.033272,0.196078,0.059232,1.485192,0.927313,1.126508,0.199196

S2_Ar1 label images:   0%|          | 0/11 [00:00<?, ?it/s]

Processing Mitolysosome1-Contents_S2_Ar1.tif
Labels in Mitolysosome1-Contents_S2_Ar1.tif: [1 2 3]
Inferred full-res scale: 29x

Mitolysosome1-Contents_S2_Ar1:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1\Mitolysosome1-Contents_S2_Ar1_measurements.csv

Processing Mitolysosome2-Contents_S2_Ar1.tif
Labels in Mitolysosome2-Contents_S2_Ar1.tif: [1 2 3]
Inferred full-res scale: 29x

Mitolysosome2-Contents_S2_Ar1:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1\Mitolysosome2-Contents_S2_Ar1_measurements.csv

Processing Mitolysosome2-WMB_S2_Ar1.tif
Labels in Mitolysosome2-WMB_S2_Ar1.tif: [1]
Inferred full-res scale: 29x

Mitolysosome2-WMB_S2_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1\Mitolysosome2-WMB_S2_Ar1_measurements.csv

Processing Mitolysosome3-Contents_S2_Ar1.tif
Labels in Mitolysosome3-Contents_S2_Ar1.tif: [ 1  2  3  4  5  6  7  8  9 10 11]
Inferred full-res scale: 29x

Mitolysosome3-Contents_S2_Ar1:   0%|          | 0/11 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1\Mitolysosome3-Contents_S2_Ar1_measurements.csv

Processing Mitolysosome3-WMB_S2_Ar1.tif
Labels in Mitolysosome3-WMB_S2_Ar1.tif: [1 2 3]
Inferred full-res scale: 29x

Mitolysosome3-WMB_S2_Ar1:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1\Mitolysosome3-WMB_S2_Ar1_measurements.csv

Processing Mitolysosome4-Contents_S2_Ar1.tif
Labels in Mitolysosome4-Contents_S2_Ar1.tif: [1 2 3]
Inferred full-res scale: 29x

Mitolysosome4-Contents_S2_Ar1:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1\Mitolysosome4-Contents_S2_Ar1_measurements.csv

Processing Mitolysosome5-Contents_S2_Ar1.tif
Labels in Mitolysosome5-Contents_S2_Ar1.tif: [1]
Inferred full-res scale: 29x

Mitolysosome5-Contents_S2_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1\Mitolysosome5-Contents_S2_Ar1_measurements.csv

Processing Mitolysosome6-Contents_S2_Ar1.tif
Labels in Mitolysosome6-Contents_S2_Ar1.tif: [1]
Inferred full-res scale: 29x

Mitolysosome6-Contents_S2_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1\Mitolysosome6-Contents_S2_Ar1_measurements.csv

Processing Mitolysosome_S2_Ar1.tif
Labels in Mitolysosome_S2_Ar1.tif: [1 2 3 4 5 6]
Inferred full-res scale: 29x

Mitolysosome_S2_Ar1:   0%|          | 0/6 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1\Mitolysosome_S2_Ar1_measurements.csv

Processing Mitoplast_S2_Ar1.tif
Labels in Mitoplast_S2_Ar1.tif: [1 2]
Inferred full-res scale: 29x

Mitoplast_S2_Ar1:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1\Mitoplast_S2_Ar1_measurements.csv

Processing PL-Speckled_S2_Ar1.tif
Labels in PL-Speckled_S2_Ar1.tif: [1]
Inferred full-res scale: 29x

PL-Speckled_S2_Ar1:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1\PL-Speckled_S2_Ar1_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar1\S2_Ar1_label_measurements_mean_norm_strict_names.csv

=== Sample: S2_Ar2 ===
Using stack: 050124-DN-p3e1c5-sample2-Ar2.nrrd.tif
Using EM image: S2Ar2 thin aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar2
Stack shape: (6, 256, 256)
Number of original channels: 6
EM shape: (6854, 6854)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S2_Ar2.tif
Detected 6-channel TIFF; assuming '29Si' is the missing channel.

Whole-field mean normalization factors:
16O: 818.313019
12C21H: 3343.851685
12C14N: 4501.779648
12C15N: 2999.259781
31P: 15.858932
32S: 75.520935

QC Whole-field 15N:
Pixels: 65536
Mean:   0.389887
Median: 0.421520
Std:    0.106225

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S2_Ar2,050124-DN-p3e1c5-sample2-Ar2.nrrd.tif,S2Ar2 thin aligned.tif,65536,7501.039429,65536,0.389887,0.42152,0.106225,0.027027,...,0.344275,65536,1.0,1.05852,0.290471,0.009065,1.762156,0.936537,1.165572,0.229035

S2_Ar2 label images:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Lysosome-NOS_S2_Ar2.tif
Labels in Lysosome-NOS_S2_Ar2.tif: [1 2 3 4 5 6 7]
Inferred full-res scale: 27x

Lysosome-NOS_S2_Ar2:   0%|          | 0/7 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar2\Lysosome-NOS_S2_Ar2_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar2\S2_Ar2_label_measurements_mean_norm_strict_names.csv

=== Sample: S2_Ar3 ===
Using stack: 051024-DN-p3e1c5-sample2-Ar3.nrrd.tif
Using EM image: S2Ar3 thin em aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3
Stack shape: (6, 256, 256)
Number of original channels: 6
EM shape: (7425, 7425)

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S2_Ar3.tif
Detected 6-channel TIFF; assuming '29Si' is the missing channel.

Whole-field mean normalization factors:
16O: 600.718262
12C21H: 2477.246017
12C14N: 3798.904129
12C15N: 2563.397598
31P: 8.453354
32S: 50.579178

QC Whole-field 15N:
Pixels: 65536
Mean:   0.400989
Median: 0.412249
Std:    0.064480

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S2_Ar3,051024-DN-p3e1c5-sample2-Ar3.nrrd.tif,S2Ar3 thin em aligned.tif,65536,6362.301727,65536,0.400989,0.412249,0.06448,0.062541,...,0.375649,65536,1.0,1.015199,0.183494,0.057841,1.576159,0.916178,1.108718,0.19254

S2_Ar3 label images:   0%|          | 0/11 [00:00<?, ?it/s]

Processing Mitolysosome1-Contents_S2_Ar3.tif
Labels in Mitolysosome1-Contents_S2_Ar3.tif: [1]
Inferred full-res scale: 29x

Mitolysosome1-Contents_S2_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3\Mitolysosome1-Contents_S2_Ar3_measurements.csv

Processing Mitolysosome2-Contents_S2_Ar3.tif
Labels in Mitolysosome2-Contents_S2_Ar3.tif: [1 2 3]
Inferred full-res scale: 29x

Mitolysosome2-Contents_S2_Ar3:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3\Mitolysosome2-Contents_S2_Ar3_measurements.csv

Processing Mitolysosome3-Contents_S2_Ar3.tif
Labels in Mitolysosome3-Contents_S2_Ar3.tif: [1]
Inferred full-res scale: 29x

Mitolysosome3-Contents_S2_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3\Mitolysosome3-Contents_S2_Ar3_measurements.csv

Processing Mitolysosome4-Contents_S2_Ar3.tif
Labels in Mitolysosome4-Contents_S2_Ar3.tif: [1 2]
Inferred full-res scale: 29x

Mitolysosome4-Contents_S2_Ar3:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3\Mitolysosome4-Contents_S2_Ar3_measurements.csv

Processing Mitolysosome5-Contents_S2_Ar3.tif
Labels in Mitolysosome5-Contents_S2_Ar3.tif: [1 2 3]
Inferred full-res scale: 29x

Mitolysosome5-Contents_S2_Ar3:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3\Mitolysosome5-Contents_S2_Ar3_measurements.csv

Processing Mitolysosome6-Contents_S2_Ar3.tif
Labels in Mitolysosome6-Contents_S2_Ar3.tif: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Inferred full-res scale: 29x

Mitolysosome6-Contents_S2_Ar3:   0%|          | 0/12 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3\Mitolysosome6-Contents_S2_Ar3_measurements.csv

Processing Mitolysosome7-Contents_S2_Ar3.tif
Labels in Mitolysosome7-Contents_S2_Ar3.tif: [1]
Inferred full-res scale: 29x

Mitolysosome7-Contents_S2_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3\Mitolysosome7-Contents_S2_Ar3_measurements.csv

Processing Mitolysosome8-Contents_S2_Ar3.tif
Labels in Mitolysosome8-Contents_S2_Ar3.tif: [1]
Inferred full-res scale: 29x

Mitolysosome8-Contents_S2_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3\Mitolysosome8-Contents_S2_Ar3_measurements.csv

Processing Mitolysosome_S2_Ar3.tif
Labels in Mitolysosome_S2_Ar3.tif: [1 2 3 5 6 7 8 9]
Inferred full-res scale: 29x

Mitolysosome_S2_Ar3:   0%|          | 0/8 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3\Mitolysosome_S2_Ar3_measurements.csv

Processing Mitoplast_S2_Ar3.tif
Labels in Mitoplast_S2_Ar3.tif: [1 2 3]
Inferred full-res scale: 29x

Mitoplast_S2_Ar3:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3\Mitoplast_S2_Ar3_measurements.csv

Processing Rupture-UW_S2_Ar3.tif
Labels in Rupture-UW_S2_Ar3.tif: [1]
Inferred full-res scale: 29x

Rupture-UW_S2_Ar3:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3\Rupture-UW_S2_Ar3_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar3\S2_Ar3_label_measurements_mean_norm_strict_names.csv

=== Sample: S2_Ar4 ===
Using stack: 050124-DN-p3e1c5-sample2-Ar4_1.nrrd.tif
Using EM image: S2Ar4 thin em aligned.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4
Stack shape: (6, 256, 256)
Number of original channels: 6
EM shape: (8567, 8567)
Detected binary cell mask in Cell_S2_Ar4.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S2_Ar4.tif
Detected 6-channel TIFF; assuming '29Si' is the missing channel.

Whole-field mean normalization factors:
16O: 923.875854
12C21H: 3036.938629
12C14N: 4692.063950
12C15N: 3872.226822
31P: 19.212128
32S: 88.843063

QC Whole-field 15N:
Pixels: 65536
Mean:   0.449859
Median: 0.473995
Std:    0.083401

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S2_Ar4,050124-DN-p3e1c5-sample2-Ar4_1.nrrd.tif,S2Ar4 thin em aligned.tif,65536,8564.290771,65536,0.449859,0.473995,0.083401,0.050627,...,0.360186,65536,1.0,1.021918,0.193553,0.015763,1.62547,0.945437,1.111943,0.166505

S2_Ar4 label images:   0%|          | 0/11 [00:00<?, ?it/s]

Processing Mitolysosome1-Contents_S2_Ar4.tif
Labels in Mitolysosome1-Contents_S2_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitolysosome1-Contents_S2_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4\Mitolysosome1-Contents_S2_Ar4_measurements.csv

Processing Mitolysosome1-WMB_S2_Ar4.tif
Labels in Mitolysosome1-WMB_S2_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitolysosome1-WMB_S2_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4\Mitolysosome1-WMB_S2_Ar4_measurements.csv

Processing Mitolysosome2-Contents_S2_Ar4.tif
Labels in Mitolysosome2-Contents_S2_Ar4.tif: [1 2 3]
Inferred full-res scale: 33x

Mitolysosome2-Contents_S2_Ar4:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4\Mitolysosome2-Contents_S2_Ar4_measurements.csv

Processing Mitolysosome3-Contents_S2_Ar4.tif
Labels in Mitolysosome3-Contents_S2_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitolysosome3-Contents_S2_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4\Mitolysosome3-Contents_S2_Ar4_measurements.csv

Processing Mitolysosome4-Contents_S2_Ar4.tif
Labels in Mitolysosome4-Contents_S2_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitolysosome4-Contents_S2_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4\Mitolysosome4-Contents_S2_Ar4_measurements.csv

Processing Mitolysosome5-Contents_S2_Ar4.tif
Labels in Mitolysosome5-Contents_S2_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitolysosome5-Contents_S2_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4\Mitolysosome5-Contents_S2_Ar4_measurements.csv

Processing Mitolysosome6-Contents_S2_Ar4.tif
Labels in Mitolysosome6-Contents_S2_Ar4.tif: [1]
Inferred full-res scale: 33x

Mitolysosome6-Contents_S2_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4\Mitolysosome6-Contents_S2_Ar4_measurements.csv

Processing Mitolysosome_S2_Ar4.tif
Labels in Mitolysosome_S2_Ar4.tif: [ 1  2  3  4  5  6  7  8 10 11 12 13 14 15]
Inferred full-res scale: 33x

Mitolysosome_S2_Ar4:   0%|          | 0/14 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4\Mitolysosome_S2_Ar4_measurements.csv

Processing Mitoplast_S2_Ar4.tif
Labels in Mitoplast_S2_Ar4.tif: [2]
Inferred full-res scale: 33x

Mitoplast_S2_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4\Mitoplast_S2_Ar4_measurements.csv

Processing PL-Speckled_S2_Ar4.tif
Labels in PL-Speckled_S2_Ar4.tif: [1]
Inferred full-res scale: 33x

PL-Speckled_S2_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4\PL-Speckled_S2_Ar4_measurements.csv

Processing PL-Whorl_S2_Ar4.tif
Labels in PL-Whorl_S2_Ar4.tif: [1]
Inferred full-res scale: 33x

PL-Whorl_S2_Ar4:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4\PL-Whorl_S2_Ar4_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar4\S2_Ar4_label_measurements_mean_norm_strict_names.csv
Warning: multiple TIFF files found in input\S2_Ar5\input_em, using Mitolysosome1-Contents_S2_Ar5.tif

=== Sample: S2_Ar5 ===
Using stack: 043024-DN-p3e1c5-sample2-Ar5.nrrd.tif
Using EM image: Mitolysosome1-Contents_S2_Ar5.tif
Outputs will be saved to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar5
Stack shape: (6, 256, 256)
Number of original channels: 6
EM shape: (6854, 6854)
Detected binary cell mask in Cell_S2_Ar5.tif; converting connected components to labels.

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:241: FutureWarning: Parameter `area_threshold` is deprecated since version 0.26.0 and will be removed in 2.0.0 (or later). To avoid this warning, please use the parameter `max_size` instead. For more details, see the documentation of `remove_small_holes`. Note that the new threshold removes objects smaller than **or equal to** its value, while the previous parameter only removed smaller ones.
  mask = remove_small_holes(mask, area_threshold=mask.size)

Using cell labels: Cell_S2_Ar5.tif
Detected 6-channel TIFF; assuming '29Si' is the missing channel.

Whole-field mean normalization factors:
16O: 3587.640762
12C21H: 12473.064499
12C14N: 14918.994995
12C15N: 12325.565125
31P: 67.297226
32S: 259.001297

QC Whole-field 15N:
Pixels: 65536
Mean:   0.453433
Median: 0.456623
Std:    0.041031

,sample,stack,em,fractional_15N_pixels,sum_12C14N_12C15N_mean,fractional_15N_n,fractional_15N_mean,fractional_15N_median,fractional_15N_std,fractional_15N_min,...,whole_field_mean_norm_32S_iqr,sum_12C14N_12C15N_mean_norm_n,sum_12C14N_12C15N_mean_norm_mean,sum_12C14N_12C15N_mean_norm_median,sum_12C14N_12C15N_mean_norm_std,sum_12C14N_12C15N_mean_norm_min,sum_12C14N_12C15N_mean_norm_max,sum_12C14N_12C15N_mean_norm_q1,sum_12C14N_12C15N_mean_norm_q3,sum_12C14N_12C15N_mean_norm_iqr
0,S2_Ar5,043024-DN-p3e1c5-sample2-Ar5.nrrd.tif,Mitolysosome1-Contents_S2_Ar5.tif,65536,27244.56012,65536,0.453433,0.456623,0.041031,0.092366,...,0.397681,65536,1.0,1.013487,0.181724,0.006937,1.534215,0.922239,1.108001,0.185762

S2_Ar5 label images:   0%|          | 0/8 [00:00<?, ?it/s]

Processing Mitolysosome1-Contents_S2_Ar5.tif
Labels in Mitolysosome1-Contents_S2_Ar5.tif: [1]
Inferred full-res scale: 27x

Mitolysosome1-Contents_S2_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar5\Mitolysosome1-Contents_S2_Ar5_measurements.csv

Processing Mitolysosome2-Contents_S2_Ar5.tif
Labels in Mitolysosome2-Contents_S2_Ar5.tif: [1 2 3 4]
Inferred full-res scale: 27x

Mitolysosome2-Contents_S2_Ar5:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar5\Mitolysosome2-Contents_S2_Ar5_measurements.csv

Processing Mitolysosome3-Contents_S2_Ar5.tif
Labels in Mitolysosome3-Contents_S2_Ar5.tif: [1 3 4 5]
Inferred full-res scale: 27x

Mitolysosome3-Contents_S2_Ar5:   0%|          | 0/4 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar5\Mitolysosome3-Contents_S2_Ar5_measurements.csv

Processing Mitolysosome_S2_Ar5.tif
Labels in Mitolysosome_S2_Ar5.tif: [1 2 3]
Inferred full-res scale: 27x

Mitolysosome_S2_Ar5:   0%|          | 0/3 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar5\Mitolysosome_S2_Ar5_measurements.csv

Processing Mitophagophore1-Contents_S2_Ar5.tif
Labels in Mitophagophore1-Contents_S2_Ar5.tif: [1]
Inferred full-res scale: 27x

Mitophagophore1-Contents_S2_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar5\Mitophagophore1-Contents_S2_Ar5_measurements.csv

Processing Mitophagophore_S2_Ar5.tif
Labels in Mitophagophore_S2_Ar5.tif: [1]
Inferred full-res scale: 27x

Mitophagophore_S2_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar5\Mitophagophore_S2_Ar5_measurements.csv

Processing Mitoplast_S2_Ar5.tif
Labels in Mitoplast_S2_Ar5.tif: [1]
Inferred full-res scale: 27x

Mitoplast_S2_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar5\Mitoplast_S2_Ar5_measurements.csv

Processing PL-Speckled_S2_Ar5.tif
Labels in PL-Speckled_S2_Ar5.tif: [2]
Inferred full-res scale: 27x

PL-Speckled_S2_Ar5:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:851: FutureWarning: `binary_erosion` is deprecated since version 0.26 and will be removed in version 0.28. Use `skimage.morphology.erosion` instead. Note the pixel shift by 1 for even-sized footprints (see docstring notes).
  eroded_mask = binary_erosion(strict_reduced_mask, footprint=footprint)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:873: FutureWarning: `RegionProperties.major_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_major_length` instead.
  major_px = float(prop.major_axis_length)
C:\Users\narendradp\AppData\Local\Temp\ipykernel_50916\3925331938.py:874: FutureWarning: `RegionProperties.minor_axis_length` is deprecated starting in version 0.26 and will be removed in version 2.0. Use `RegionProperties.axis_minor_length` instead.
  minor_px = float(prop.minor_axis_length)

Saved group dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar5\PL-Speckled_S2_Ar5_measurements.csv
Saved sample dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\S2_Ar5\S2_Ar5_label_measurements_mean_norm_strict_names.csv

,sample,label_id,source_label_file,source_stack_file,source_em_file,pixel_size_nm,normalization_method,original_label_pixel_count,strict_reduced_pixel_count,strict_eroded_pixel_count,...,strict_eroded_raw_fractional_15N_median,strict_eroded_raw_fractional_15N_std,source_cell_file,cell_label_id,cell_region_pixel_count,centroid_in_cell_mask,cell_12C14N_12C15N_mean,cell_normalization_method,strict_reduced_cell_norm_sum_12C14N_12C15N_mean,strict_eroded_cell_norm_sum_12C14N_12C15N_mean
0,S18_Ar2,10001,Mitochondria_S18_Ar2.tif,030625-DNp3e2c8-S18-ROI2.nrrd.tif,S18 Ar2 EM aligned.tif,1.751,whole_field_mean,31543,15,0,...,NaN,NaN,Cell_S18_Ar2.tif,1,73393489,True,4248.715286,cell_mean,1.092142,NaN
1,S18_Ar2,10003,Mitochondria_S18_Ar2.tif,030625-DNp3e2c8-S18-ROI2.nrrd.tif,S18 Ar2 EM aligned.tif,1.751,whole_field_mean,356559,257,132,...,0.232013,0.009143,Cell_S18_Ar2.tif,1,73393489,True,4248.715286,cell_mean,1.099715,1.104887
2,S18_Ar2,10005,Mitochondria_S18_Ar2.tif,030625-DNp3e2c8-S18-ROI2.nrrd.tif,S18 Ar2 EM aligned.tif,1.751,whole_field_mean,23263,12,0,...,NaN,NaN,Cell_S18_Ar2.tif,1,73393489,True,4248.715286,cell_mean,1.017916,NaN
3,S18_Ar2,10015,Mitochondria_S18_Ar2.tif,030625-DNp3e2c8-S18-ROI2.nrrd.tif,S18 Ar2 EM aligned.tif,1.751,whole_field_mean,34438,21,3,...,0.219369,0.006046,Cell_S18_Ar2.tif,1,73393489,True,4248.715286,cell_mean,1.072873,1.093193
4,S18_Ar2,10021,Mitochondria_S18_Ar2.tif,030625-DNp3e2c8-S18-ROI2.nrrd.tif,S18 Ar2 EM aligned.tif,1.751,whole_field_mean,239454,162,71,...,0.227756,0.009144,Cell_S18_Ar2.tif,1,73393489,True,4248.715286,cell_mean,1.156479,1.171741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6092,S2_Ar5,3,Mitolysosome_S2_Ar5.tif,043024-DN-p3e1c5-sample2-Ar5.nrrd.tif,Mitolysosome1-Contents_S2_Ar5.tif,1.751,whole_field_mean,487602,619,498,...,0.337275,0.067242,Cell_S2_Ar5.tif,1,46977316,True,27244.560120,cell_mean,1.005277,0.990401
6093,S2_Ar5,1,Mitophagophore1-Contents_S2_Ar5.tif,043024-DN-p3e1c5-sample2-Ar5.nrrd.tif,Mitolysosome1-Contents_S2_Ar5.tif,1.751,whole_field_mean,32715,32,10,...,0.478745,0.001254,Cell_S2_Ar5.tif,1,46977316,True,27244.560120,cell_mean,1.019948,1.009192
6094,S2_Ar5,1,Mitophagophore_S2_Ar5.tif,043024-DN-p3e1c5-sample2-Ar5.nrrd.tif,Mitolysosome1-Contents_S2_Ar5.tif,1.751,whole_field_mean,39627,42,16,...,0.478646,0.001127,Cell_S2_Ar5.tif,1,46977316,True,27244.560120,cell_mean,1.024276,1.014040
6095,S2_Ar5,1,Mitoplast_S2_Ar5.tif,043024-DN-p3e1c5-sample2-Ar5.nrrd.tif,Mitolysosome1-Contents_S2_Ar5.tif,1.751,whole_field_mean,26307,25,6,...,0.468198,0.003546,Cell_S2_Ar5.tif,1,46977316,True,27244.560120,cell_mean,1.000322,0.978587
6096,S2_Ar5,2,PL-Speckled_S2_Ar5.tif,043024-DN-p3e1c5-sample2-Ar5.nrrd.tif,Mitolysosome1-Contents_S2_Ar5.tif,1.751,whole_field_mean,33859,35,13,...,0.496096,0.002853,Cell_S2_Ar5.tif,1,46977316,True,27244.560120,cell_mean,1.438763,1.489353

Saved combined dataframe to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\all_samples_label_measurements_mean_norm_strict_names.csv
Saved combined QC summary to: C:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\output\all_samples_qc.csv

In [1]:
# =============================
# Combined annotation script
#   - keeps the SAME Mitolysosome<->contents mapping logic
#   - adds unique_ID using label_id
#   - annotates partially wrapped rows
#   - adds group names from key.csv
#   - writes combined_output.csv next to the script
# =============================

from pathlib import Path
import numpy as np
import pandas as pd

# -----------------------------
# Paths
# -----------------------------
SCRIPT_DIR = Path(__file__).resolve().parent if "__file__" in globals() else Path.cwd()
INPUT_PATH = SCRIPT_DIR / "output" / "all_samples_label_measurements_mean_norm_strict_names.csv"
KEY_PATH = SCRIPT_DIR / "key.csv"
PW_PATH = SCRIPT_DIR / "Partially_Wrapped_Masterlist.csv"
OUT_PATH = SCRIPT_DIR / "combined_output_before_annotation.csv"

# -----------------------------
# Load main dataframe
# -----------------------------
df = pd.read_csv(INPUT_PATH).copy()
df["__row_order__"] = np.arange(len(df))

if "sample" not in df.columns:
    raise ValueError("Expected a 'sample' column in the main input dataframe.")
if "source_label_file" not in df.columns:
    raise ValueError("Expected a 'source_label_file' column in the main input dataframe.")
if "label_id" not in df.columns:
    raise ValueError("Expected a 'label_id' column in the main input dataframe.")

df["sample"] = df["sample"].astype(str)
df["source_label_file"] = df["source_label_file"].astype(str)
df["label_id"] = pd.to_numeric(df["label_id"], errors="coerce").astype("Int64")

# -----------------------------
# Add group names from key.csv
# -----------------------------
key_df = pd.read_csv(KEY_PATH).copy()
key_df.columns = [c.strip() for c in key_df.columns]

if "sample" not in key_df.columns:
    raise ValueError("key.csv must contain a 'sample' column.")

key_df["sample"] = key_df["sample"].astype(str)
df = df.merge(key_df, on="sample", how="left", validate="m:1")

if "experiment_name" in df.columns:
    df["group_name"] = df["experiment_name"]
elif "sample_name" in df.columns:
    df["group_name"] = df["sample_name"]
else:
    df["group_name"] = df["sample"]

# -----------------------------
# unique_ID
# -----------------------------
base_name = df["source_label_file"].str.replace(r"\.tif$", "", regex=True)
df["unique_ID"] = base_name + "_" + df["label_id"].astype(str)

# -----------------------------
# Partially wrapped annotation
# -----------------------------
pw = pd.read_csv(PW_PATH).copy()
pw.columns = [c.strip() for c in pw.columns]

if "unique_ID" not in pw.columns:
    raise ValueError("Partially_Wrapped_Masterlist.csv must contain a 'unique_ID' column.")

pw["unique_ID"] = pw["unique_ID"].astype(str)

if "mask" in pw.columns:
    pw["partially_wrapped_group_name"] = (
        pw["mask"].astype(str)
        .str.replace(r"\d+", "", regex=True)
        .str.replace("-Contents", "", regex=False)
    )
else:
    pw["partially_wrapped_group_name"] = pd.NA

pw_keep_cols = ["unique_ID"]
for col in ["mask", "source_label_file", "label", "napari label", "partially_wrapped_group_name"]:
    if col in pw.columns:
        pw_keep_cols.append(col)

pw_annot = pw[pw_keep_cols].rename(columns={
    "mask": "pw_mask",
    "source_label_file": "pw_source_label_file",
    "label": "pw_label",
    "napari label": "pw_napari_label",
})

df = df.merge(pw_annot, on="unique_ID", how="left", validate="m:1")
df["partially_wrapped"] = df["pw_source_label_file"].notna()

# -----------------------------
# SAME Mitolysosome mapping logic as the prior composite script
# -----------------------------
src = df["source_label_file"].astype(str)

df["mito_kind"] = np.select(
    [
        src.str.match(r"^Mitolysosome\d+-Contents_.+\.tif$", na=False),
        src.str.match(r"^Mitolysosome_.+\.tif$", na=False),
        src.str.match(r"^Mitolysosome\d+-(?!Contents).+\.tif$", na=False),
    ],
    [
        "contents",
        "main",
        "other_mito_related",
    ],
    default="other",
)

# Create corrected_mito_rank column in df first
df["corrected_mito_rank"] = pd.Series(pd.NA, index=df.index, dtype="Int64")

# Main rows: sequential order within each sample, based on row order
main = df[df["mito_kind"] == "main"].copy()
main = main.sort_values(["sample", "__row_order__"])
main["corrected_mito_rank"] = main.groupby("sample").cumcount() + 1
df.loc[main.index, "corrected_mito_rank"] = main["corrected_mito_rank"].astype("Int64")

# Contents rows: rank comes from file name
contents = df[df["mito_kind"] == "contents"].copy()
contents_rank = (
    contents["source_label_file"]
    .str.extract(r"^Mitolysosome(?P<n>\d+)-Contents_.+\.tif$")["n"]
    .astype("Int64")
)
df.loc[contents.index, "corrected_mito_rank"] = contents_rank

# Parent lookup from main rows
main_lookup = main[[
    "sample",
    "corrected_mito_rank",
    "label_id",
    "source_label_file",
    "unique_ID",
    "group_name",
]].copy()

main_lookup = main_lookup.rename(columns={
    "label_id": "corrected_mito_label_id",
    "source_label_file": "corrected_mito_source_label_file",
    "unique_ID": "corrected_mito_unique_ID",
    "group_name": "corrected_mito_group_name",
})

main_lookup["corrected_mito_unique_ID"] = (
    main_lookup["corrected_mito_source_label_file"].astype(str).str.replace(r"\.tif$", "", regex=True)
    + "_"
    + main_lookup["corrected_mito_label_id"].astype(str)
)

# Merge parent annotations onto every row using sample + corrected_mito_rank
df = df.merge(
    main_lookup,
    on=["sample", "corrected_mito_rank"],
    how="left",
    validate="m:1"
)

# Parent rows map to themselves
main_rows = df["mito_kind"].eq("main")
df.loc[main_rows, "corrected_mito_label_id"] = df.loc[main_rows, "label_id"]
df.loc[main_rows, "corrected_mito_source_label_file"] = df.loc[main_rows, "source_label_file"]
df.loc[main_rows, "corrected_mito_unique_ID"] = df.loc[main_rows, "unique_ID"]
df.loc[main_rows, "corrected_mito_group_name"] = df.loc[main_rows, "group_name"]

# Convenience key
df["corrected_mito_key"] = np.where(
    df["corrected_mito_rank"].notna(),
    df["sample"].astype(str) + "_M" + df["corrected_mito_rank"].astype("Int64").astype(str),
    pd.NA
)

# Flags
df["is_main_mitolysosome"] = df["mito_kind"].eq("main")
df["is_mitolysosome_content"] = df["mito_kind"].eq("contents")

# -----------------------------
# Save
# -----------------------------
df.to_csv(OUT_PATH, index=False)
print(f"Saved annotated file to: {OUT_PATH}")

# -----------------------------
# Preview
# -----------------------------
preview_cols = [
    c for c in [
        "sample",
        "group_name",
        "source_label_file",
        "label_id",
        "unique_ID",
        "partially_wrapped",
        "partially_wrapped_group_name",
        "mito_kind",
        "corrected_mito_rank",
        "corrected_mito_label_id",
        "corrected_mito_source_label_file",
        "corrected_mito_unique_ID",
        "corrected_mito_group_name",
        "corrected_mito_key",
    ] if c in df.columns
]

display(df[preview_cols].head(30))

Saved annotated file to: c:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\combined_output_before_annotation.csv

,sample,group_name,source_label_file,label_id,unique_ID,partially_wrapped,partially_wrapped_group_name,mito_kind,corrected_mito_rank,corrected_mito_label_id,corrected_mito_source_label_file,corrected_mito_unique_ID,corrected_mito_group_name,corrected_mito_key
0,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10001,Mitochondria_S18_Ar2_10001,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
1,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10003,Mitochondria_S18_Ar2_10003,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
2,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10005,Mitochondria_S18_Ar2_10005,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
3,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10015,Mitochondria_S18_Ar2_10015,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
4,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10021,Mitochondria_S18_Ar2_10021,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
5,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10026,Mitochondria_S18_Ar2_10026,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
6,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10027,Mitochondria_S18_Ar2_10027,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
7,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10028,Mitochondria_S18_Ar2_10028,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
8,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10029,Mitochondria_S18_Ar2_10029,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
9,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10030,Mitochondria_S18_Ar2_10030,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
10,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10032,Mitochondria_S18_Ar2_10032,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
11,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10034,Mitochondria_S18_Ar2_10034,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
12,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10035,Mitochondria_S18_Ar2_10035,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
13,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10042,Mitochondria_S18_Ar2_10042,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
14,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10056,Mitochondria_S18_Ar2_10056,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
15,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10058,Mitochondria_S18_Ar2_10058,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
16,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10060,Mitochondria_S18_Ar2_10060,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
17,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10062,Mitochondria_S18_Ar2_10062,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
18,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10063,Mitochondria_S18_Ar2_10063,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
19,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10064,Mitochondria_S18_Ar2_10064,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
20,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10067,Mitochondria_S18_Ar2_10067,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
21,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10072,Mitochondria_S18_Ar2_10072,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
22,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10073,Mitochondria_S18_Ar2_10073,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
23,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10075,Mitochondria_S18_Ar2_10075,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
24,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10076,Mitochondria_S18_Ar2_10076,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
25,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10079,Mitochondria_S18_Ar2_10079,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
26,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10081,Mitochondria_S18_Ar2_10081,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
27,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10084,Mitochondria_S18_Ar2_10084,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
28,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10090,Mitochondria_S18_Ar2_10090,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN
29,S18_Ar2,SL_1wk-chase,Mitochondria_S18_Ar2.tif,10091,Mitochondria_S18_Ar2_10091,False,NaN,other,<NA>,<NA>,NaN,NaN,NaN,NaN

In [5]:
# =============================
# EM-only Mitolysosome content rating script
#   - starts at the beginning every time
#   - uses combined_output.csv
#   - uses npz_file for image loading
#   - uses corrected_mito_source_label_file + corrected_mito_label_id for parent lookup
#   - focuses only on Mitolysosome contents
#   - shows:
#       1) parent overview
#       2) parent EM crop
#       3) child EM crop
#   - 4-level morphology criteria
#   - records responses back into df
#   - saves progress after every response
# =============================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from IPython.display import display, clear_output, Javascript
import ipywidgets as widgets

# -----------------------------
# Paths
# -----------------------------
SCRIPT_DIR = Path(__file__).resolve().parent if "__file__" in globals() else Path.cwd()
CSV_PATH = SCRIPT_DIR / "combined_output.csv"
if not CSV_PATH.exists():
    alt = SCRIPT_DIR / "output" / "combined_output_before_annotation.csv"
    if alt.exists():
        CSV_PATH = alt
    else:
        raise FileNotFoundError("Could not find combined_output.csv in the script directory or output/ subfolder.")

CSV_DIR = CSV_PATH.parent

NPZ_SEARCH_DIRS = [
    CSV_DIR / "output_npz",
    CSV_DIR,
    SCRIPT_DIR / "output_npz",
    SCRIPT_DIR,
    Path("/mnt/data/output_npz"),
    Path("/mnt/data"),
]

OUT_PATH = CSV_DIR / "combined_output_morphology_rated.csv"

# -----------------------------
# Morphology criteria
# -----------------------------
MORPHOLOGY_SCORE_LABELS = {
    1: "apparently undigested",
    2: "partially digested",
    3: "moderately digested",
    4: "severely digested",
}

MORPHOLOGY_SCORE_HELP = (
    "1 – Apparently undigested. All cristae clear and distinguishable, similar to mitochondria outside mitolysosome\n"
    "2 – Partially digested. Some cristae with normal morphology still visible but clear disruption of morphology\n"
    "3 – Moderately digested. No normal cristae, but few remnants that could be cristae, can be very granular\n"
    "4 – Severely digested. No cristae recognizable, very granular"
)

# -----------------------------
# Load dataframe
# -----------------------------
df = pd.read_csv(CSV_PATH).copy()
df["__row_order__"] = np.arange(len(df))

required_cols = ["sample", "source_label_file", "label_id", "npz_file"]
for c in required_cols:
    if c not in df.columns:
        raise ValueError(f"Expected a '{c}' column in combined_output.csv.")

df["sample"] = df["sample"].astype(str)
df["source_label_file"] = df["source_label_file"].astype(str)
df["label_id"] = pd.to_numeric(df["label_id"], errors="coerce").astype("Int64")
df["npz_file"] = df["npz_file"].astype(str)

# stable key
df["annotation_uid"] = (
    df["sample"].astype(str)
    + "__"
    + df["source_label_file"].astype(str)
    + "__"
    + df["label_id"].astype(str)
)

# -----------------------------
# Focus only on Mitolysosome contents
# -----------------------------
src = df["source_label_file"].astype(str)

if "object_kind" in df.columns and "object_family" in df.columns:
    contents_mask = df["object_kind"].astype(str).eq("contents") & df["object_family"].astype(str).eq("Mitolysosome")
else:
    contents_mask = src.str.match(r"^Mitolysosome\d+-Contents_.+\.tif$", na=False)

# -----------------------------
# Parent lookup from combined_output columns
# -----------------------------
for c in ["corrected_mito_source_label_file", "corrected_mito_label_id", "corrected_mito_unique_ID", "corrected_mito_rank"]:
    if c not in df.columns:
        df[c] = pd.NA

df["corrected_mito_label_id"] = pd.to_numeric(df["corrected_mito_label_id"], errors="coerce").astype("Int64")
df["corrected_mito_rank"] = pd.to_numeric(df["corrected_mito_rank"], errors="coerce").astype("Int64")

# Build a direct parent key using the corrected mapping already present
df["parent_source_label_file"] = df["corrected_mito_source_label_file"]
df["parent_label_id"] = df["corrected_mito_label_id"]
df["parent_annotation_uid"] = pd.NA

uid_lookup = df.set_index("annotation_uid", drop=False)

for idx in df.index[contents_mask]:
    psrc = df.at[idx, "parent_source_label_file"]
    plabel = df.at[idx, "parent_label_id"]
    psample = df.at[idx, "sample"]
    if pd.notna(psrc) and pd.notna(plabel):
        parent_uid = f"{psample}__{psrc}__{int(plabel)}"
        if parent_uid in uid_lookup.index:
            df.at[idx, "parent_annotation_uid"] = parent_uid

# -----------------------------
# Start from the beginning every time
# -----------------------------
for c in [
    "content_morphology_response",
    "content_morphology_score",
    "content_morphology_label",
    "content_morphology_comment",
    "content_morphology_status",
    "content_morphology_rated",
]:
    if c not in df.columns:
        if c == "content_morphology_score":
            df[c] = pd.Series(pd.NA, index=df.index, dtype="Int64")
        elif c == "content_morphology_rated":
            df[c] = False
        else:
            df[c] = pd.Series(pd.NA, index=df.index, dtype="object")

# -----------------------------
# NPZ helpers
# -----------------------------
_npz_cache = {}

def find_npz_path(npz_file):
    p = Path(str(npz_file))
    if p.is_absolute() and p.exists():
        return p
    for root in NPZ_SEARCH_DIRS:
        cand = root / p.name
        if cand.exists():
            return cand
    return None

def load_npz(npz_file):
    if pd.isna(npz_file):
        return None
    key = str(npz_file)
    if key in _npz_cache:
        return _npz_cache[key]
    npz_path = find_npz_path(key)
    if npz_path is None:
        return None
    _npz_cache[key] = np.load(npz_path)
    return _npz_cache[key]

def load_em_and_bbox(npz_file):
    data = load_npz(npz_file)
    if data is None:
        return None, None
    return data["em"], data["bbox_strict"]

def make_overview_em(em, bbox):
    if em is None or bbox is None:
        return None
    y0, y1, x0, x1 = bbox
    full_em = np.zeros((256, 256))
    full_em[y0:y1, x0:x1] = em[:(y1 - y0), :(x1 - x0)]
    return full_em

def show_panel(ax, img, title, full_canvas=False):
    if img is None:
        ax.axis("off")
        ax.text(0.5, 0.5, "Missing NPZ", ha="center", va="center")
        return
    if full_canvas:
        ax.imshow(img, cmap="gray")
        ax.add_patch(
            plt.Rectangle((0, 0), 256, 256, edgecolor="black", facecolor="none", linewidth=2.5, clip_on=False)
        )
    else:
        vmin, vmax = np.percentile(img, 1), np.percentile(img, 99)
        ax.imshow(img, cmap="gray", vmin=vmin, vmax=vmax)
    ax.set_title(title)
    ax.axis("off")

# -----------------------------
# Hotkeys
# -----------------------------
def install_hotkeys():
    js = r"""
    (function() {
        if (window._morphologyHotkeysInstalled) return;
        window._morphologyHotkeysInstalled = true;

        document.addEventListener('keydown', function(ev) {
            if (!ev || !ev.key) return;
            const target = ev.target;
            if (target && (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA' || target.isContentEditable)) {
                return;
            }

            const map = {
                '1': '1',
                '2': '2',
                '3': '3',
                '4': '4',
                's': 'Skip',
                'S': 'Skip'
            };

            const wanted = map[ev.key];
            if (!wanted) return;

            const buttons = Array.from(document.querySelectorAll('button'));
            const btn = buttons.find(b => (b.innerText || '').trim() === wanted);
            if (btn) {
                ev.preventDefault();
                ev.stopPropagation();
                btn.click();
            }
        }, true);
    })();
    """
    display(Javascript(js))

# -----------------------------
# Annotator
# -----------------------------
class MorphologyAnnotator:
    def __init__(self, df):
        self.df = df
        self.row_by_uid = df.set_index("annotation_uid", drop=False)

        content_df = self.df.loc[contents_mask].copy()
        content_df = content_df.sort_values(["sample", "__row_order__"]).reset_index()

        self.queue = []
        for _, row in content_df.iterrows():
            status = self.df.at[row["index"], "content_morphology_status"]
            if pd.isna(status):
                self.queue.append({
                    "row_index": row["index"],
                    "row": self.df.loc[row["index"]].copy(),
                })

        self.total = int(len(content_df))
        self.done = int(self.df["content_morphology_status"].isin(["rated", "skipped"]).sum())
        self.i = 0

        self.progress = widgets.IntProgress(
            value=self.done,
            min=0,
            max=max(self.total, 1),
            description="Progress:",
            bar_style=""
        )
        self.progress_label = widgets.HTML()
        self.image_out = widgets.Output()
        self.control_out = widgets.Output()
        self.help_out = widgets.Output()

        self.ui = widgets.VBox([
            widgets.HBox([self.progress, self.progress_label]),
            self.help_out,
            self.image_out,
            self.control_out
        ])

    def start(self):
        install_hotkeys()
        display(self.ui)
        self.render_current()

    def save(self):
        self.df.to_csv(OUT_PATH, index=False)

    def update_progress(self):
        self.progress.value = self.done
        self.progress.max = max(self.total, 1)
        self.progress_label.value = f"<b>{self.done} / {self.total}</b> contents completed"

    def render_current(self):
        self.update_progress()

        with self.image_out:
            clear_output(wait=True)

            if self.i >= len(self.queue):
                print("Done. No more Mitolysosome contents to rate.")
                self.save()
                return

            case = self.queue[self.i]
            content_row = case["row"]

            parent_row = None
            parent_uid = content_row.get("parent_annotation_uid", pd.NA)
            if pd.notna(parent_uid) and parent_uid in self.row_by_uid.index:
                parent_row = self.row_by_uid.loc[parent_uid].copy()

            if parent_row is not None:
                parent_em, parent_bbox = load_em_and_bbox(parent_row["npz_file"])
                parent_overview = make_overview_em(parent_em, parent_bbox)
            else:
                parent_em, parent_bbox = None, None
                parent_overview = None

            child_em, child_bbox = load_em_and_bbox(content_row["npz_file"])

            fig, axes = plt.subplots(1, 3, figsize=(18, 6))

            show_panel(
                axes[0],
                parent_overview,
                "Parent overview\n(MISSING)" if parent_row is None else f"Parent overview\n{parent_row['source_label_file']}",
                full_canvas=True
            )
            show_panel(
                axes[1],
                parent_em,
                "Parent EM crop\n(MISSING)" if parent_row is None else f"Parent EM crop\n{parent_row['source_label_file']}",
                full_canvas=False
            )
            show_panel(
                axes[2],
                child_em,
                f"Child EM crop\n{content_row['source_label_file']}",
                full_canvas=False
            )

            parent_title = "MISSING" if parent_row is None else parent_row["source_label_file"]
            fig.suptitle(
                f"Sample: {content_row['sample']} | Parent: {parent_title} | "
                f"Content {self.i + 1} of {len(self.queue)}",
                fontsize=14,
                weight="bold"
            )
            plt.tight_layout(rect=[0, 0, 1, 0.92])
            plt.show()

        self.render_control_panel()

    def render_control_panel(self):
        with self.control_out:
            clear_output(wait=True)

            if self.i >= len(self.queue):
                display(widgets.HTML(value="<b>Annotation complete.</b>"))
                return

            content_row = self.queue[self.i]["row"]

            status = widgets.HTML(
                value=(
                    f"<b>Rate morphology for:</b> {content_row['source_label_file']}<br><br>"
                    f"<b>Criteria:</b><br>"
                    f"{MORPHOLOGY_SCORE_HELP.replace(chr(10), '<br>')}"
                )
            )

            comment = widgets.Text(
                value="",
                placeholder="Optional comment",
                description="Comment:",
                layout=widgets.Layout(width="500px")
            )

            buttons = [
                widgets.Button(description="1", button_style="success", layout=widgets.Layout(width="70px")),
                widgets.Button(description="2", button_style="warning", layout=widgets.Layout(width="70px")),
                widgets.Button(description="3", button_style="danger", layout=widgets.Layout(width="70px")),
                widgets.Button(description="4", button_style="info", layout=widgets.Layout(width="70px")),
                widgets.Button(description="Skip", button_style="", layout=widgets.Layout(width="90px")),
            ]

            def on_click_factory(score_value):
                def _handler(_):
                    self.handle_response(score_value, comment.value.strip())
                return _handler

            for b in buttons:
                if b.description == "Skip":
                    b.on_click(on_click_factory("skip"))
                else:
                    b.on_click(on_click_factory(b.description))

            display(
                widgets.VBox([
                    status,
                    widgets.HBox(buttons),
                    widgets.HTML(value="<i>Tip: use hotkeys 1–4 or s for Skip.</i>"),
                    comment
                ])
            )

    def handle_response(self, score_value, comment_text):
        if self.i >= len(self.queue):
            return

        case = self.queue[self.i]
        row_idx = case["row_index"]

        if score_value == "skip":
            response = "skip"
            score = pd.NA
            label = pd.NA
            status = "skipped"
            rated = False
        else:
            response = str(score_value)
            score = int(score_value)
            label = MORPHOLOGY_SCORE_LABELS[score]
            status = "rated"
            rated = True

        comment = pd.NA if comment_text == "" else comment_text

        self.df.at[row_idx, "content_morphology_response"] = response
        self.df.at[row_idx, "content_morphology_score"] = score
        self.df.at[row_idx, "content_morphology_label"] = label
        self.df.at[row_idx, "content_morphology_comment"] = comment
        self.df.at[row_idx, "content_morphology_status"] = status
        self.df.at[row_idx, "content_morphology_rated"] = rated

        self.done += 1
        self.save()

        self.i += 1
        self.render_current()

# -----------------------------
# Run
# -----------------------------
annotator = MorphologyAnnotator(df)
annotator.start()

# Final save
df.to_csv(OUT_PATH, index=False)
print(f"Saving to: {OUT_PATH}")

VBox(children=(HBox(children=(IntProgress(value=0, description='Progress:', max=283), HTML(value=''))), Output…

Saving to: c:\Users\narendradp\OneDrive - National Institutes of Health\Documents\Jennifer_Data\2D_measure_NanoSIMS_using_labels\combined_output_morphology_rated.csv